### ISSUE TITLE
Github backend requests both read and write access

### ISSUE THREAD

**Issue by ziyaointl** [greenpau/caddy-security#1]
When using the github backend, the scope requested is `user`, which includes both read and write permissions to user data: https://github.com/greenpau/caddy-auth-portal/blob/0f64ae51b30682557cfa1ffb9dedcc92dc689aaf/caddyfile.go#L270
This is not ideal, since caddy shouldn't be changing user data. Instead, we could use the scope `read:user` which requests only read access.

Github documentation: https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps

This issue was first opened here: https://github.com/greenpau/caddy-auth-portal/issues/230

**Comment by greenpau** [comment]
@ziyaointl , changed! Will be available next release.

---

❗ 💭  Please consider **promoting this project** on social media (Twitter, LinkedIn, HN), **sponsoring the project** (every $1 matters, because it means you vested!), and **starring it** ⭐ ⭐ ⭐ !

**Comment by ziyaointl** [comment]
This is awesome, thank you!
