### ISSUE TITLE
`auth provider returned error, user authorization failed` being spammed in Caddy log

### ISSUE THREAD

**Issue by poperigby** [greenpau/caddy-security#10]
**Describe the issue**
I'm trying to migrate my config over to Caddy Security, and I think I have most things working now, but I'm getting this message constantly spammed in Caddy's log:
```
{"level":"error","ts":1642791051.2186432,"logger":"http.handlers.authentication","msg":"auth provider returned error","provider":"authorizer","error":"user authorization failed"}
```
The interesting thing is, it doesn't seem to affect the functionality, because I'm able to login just fine.

**Configuration**
```
{ # Global configuration
    acme_dns cloudflare REDACTED
    email REDACTED
    order authorize before reverse_proxy
    order authenticate before authorize
    security {
        credentials email smtp.sendgrid.net {
            address smtp.sendgrid.net:587
            protocol smtp
            username {env.SMTP_USERNAME}
            password {env.SMTP_PASSWORD}
        }
        authentication portal myportal {
            crypto default token lifetime 3600
            # crypto key sign-verify {env.JWT_SECRET}
            backend local /etc/caddy/auth/local/users.json local
                    cookie domain haddock.cc
            ui {
                links { # Icons here -> https://icons8.com/line-awesome
                    "Cloud" https://cloud.haddock.cc icon "las la-cloud"
                    "Media" https://media.haddock.cc icon "las la-photo-video"
                    "Get TV Shows" https://tv.haddock.cc icon "las la-tv"
                    "Get Movies" https://movies.haddock.cc icon "las la-video"
                }
            }
            transform user {
                match origin local
                action add role authp/user
                ui link "Portal Settings" /settings icon "las la-cog"
            }
        }
        authorization policy mypolicy {
            set auth url https://auth.haddock.cc/
            allow roles authp/admin authp/user
        }
    }
    # }
    # crowdsec {
    #     api_url http://crowdsec:8180/
    #     api_key REDACTED
    #     ticker_interval 15s
    # }
}

auth.haddock.cc {
    authenticate * with myportal
}

cloud.haddock.cc {
    authorize with mypolicy
        reverse_proxy nextcloud:80 {
        header_down Strict-Transport-Security "max-age=15552000; includeSubDomains"
    }
    rewrite /.well-known/carddav /remote.php/dav
    rewrite /.well-known/caldav /remote.php/dav
}

media.haddock.cc {
    authorize with mypolicy
    reverse_proxy jellyfin:8096
}

indexers.haddock.cc { # Prowlarr
    authorize with mypolicy
    reverse_proxy prowlarr:9696
}

tv.haddock.cc { # Sonarr
    authorize with mypolicy
    reverse_proxy sonarr:8989
}

movies.haddock.cc { # Radarr
    authorize with mypolicy
    reverse_proxy radarr:7878
}

localhost:8112 { # QBittorrent
    reverse_proxy torrent:8080
}
```

**Version Information**
```
crowdsec v0.2.0
dns.providers.cloudflare v0.0.0-20210607183747-91cf700356a1
http.authentication.providers.authorizer v1.0.1
http.handlers.authenticator v1.0.1
http.handlers.crowdsec v0.2.0
layer4 v0.0.0-20201230212151-6587f40d4eb6
layer4.matchers.crowdsec v0.2.0
layer4.matchers.ip v0.0.0-20201230212151-6587f40d4eb6
security v1.0.1
```

**Expected behavior**
The Caddy log isn't filled up with the error.

**Comment by greenpau** [comment]
> {"level":"error","ts":1642791051.2186432,"logger":"http.handlers.authentication","msg":"auth provider returned error","provider":"authorizer","error":"user authorization failed"}

@lumbo7332 , are you able to access media.haddock.cc after you went to https://auth.haddock.cc/logout ?

**Comment by lumbo7332** [comment]
Yes.

**Comment by greenpau** [comment]
> Yes.

@lumbo7332 , are you saying the authorization is not working?

**Comment by lumbo7332** [comment]
No, the authorization appears to be working just fine.

**Comment by greenpau** [comment]
> are you able to access media.haddock.cc after you went to https://auth.haddock.cc/logout ?

After you visit  https://auth.haddock.cc/logout, the portal should reset you cookies rendering you "unauthenticated". If after that you browse to "media.haddock.cc", I expect it to redirect you back to https://auth.haddock.cc/ (i.e. not to let you access it).

**Comment by lumbo7332** [comment]
Oh wait. I must have done something wrong before. 
1. I went to https://auth.haddock.cc/logout
2. It showed me a login page.
3. I went to https://media.haddock.cc, but it didn't redirect me, and instead went to this url: https://media.haddock.cc/?redirect_url=https%3A%2F%2Fmedia.haddock.cc%2F

**Comment by greenpau** [comment]
> I went to https://media.haddock.cc, but it didn't redirect me, and instead went to this url: https://media.haddock.cc/?redirect_url=https%3A%2F%2Fmedia.haddock.cc%2F

@lumbo7332, That strange. Let me confirm. Looks like a bug in the redirect.

**Comment by lumbo7332** [comment]
Thanks :slightly_smiling_face:

**Comment by greenpau** [comment]
@lumbo7332 ,  confirmed bug with validator. Working on a fix.

**Comment by greenpau** [comment]
@lumbo7332  , released fix in https://github.com/greenpau/caddy-security/releases/tag/v1.0.2

Please retest and re-open if necessary.

Do not use `order`, use `routes`. See https://gist.github.com/greenpau/6abb58bf7b523210c39c8138c6a6417f

**Comment by lumbo7332** [comment]
That fixed the redirection, thank you. Why should I be using `route` over `order`?

**Comment by greenpau** [comment]
It gives you more control. With the “order” you might get a variable match, e.g. authorization might fail but reverse proxy still allows one to access a resource.

**Comment by lumbo7332** [comment]
Got it. Also, the redirection is fixed, but I'm still getting these errors, when going to media.haddock.cc:
```
{"level":"error","ts":1642820621.5075433,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}
{"level":"error","ts":1642820625.244474,"logger":"http.handlers.authentication","msg":"auth provider returned error","provider":"authorizer","error":"user authorization failed"}
```
`Caddyfile`
```
{ # Global configuration
    acme_dns cloudflare REDACTED
    email REDACTED
    security {
        credentials email smtp.sendgrid.net {
            address smtp.sendgrid.net:587
            protocol smtp
            username {env.SMTP_USERNAME}
            password {env.SMTP_PASSWORD}
        }
        authentication portal myportal {
            crypto default token lifetime 3600
            # crypto key sign-verify {env.JWT_SECRET}
            backend local /etc/caddy/auth/local/users.json local
                    cookie domain haddock.cc
            ui {
                links { # Icons here -> https://icons8.com/line-awesome
                    "Cloud" https://cloud.haddock.cc icon "las la-cloud"
                    "Media" https://media.haddock.cc icon "las la-photo-video"
                    "Get TV Shows" https://tv.haddock.cc icon "las la-tv"
                    "Get Movies" https://movies.haddock.cc icon "las la-video"
                }
            }
            transform user {
                match origin local
                action add role authp/user
                ui link "Portal Settings" /settings icon "las la-cog"
            }
        }
        authorization policy mypolicy {
            set auth url https://auth.haddock.cc/
            # crypto key verify {env.JWT_SECRET}
            allow roles authp/admin authp/user
        }
    }
}

auth.haddock.cc {
    route {
        authenticate * with myportal
    }
}

cloud.haddock.cc {
    route {
        authorize with mypolicy
        reverse_proxy nextcloud:80 {
            header_down Strict-Transport-Security "max-age=15552000; includeSubDomains"
        }
    }
    rewrite /.well-known/carddav /remote.php/dav
    rewrite /.well-known/caldav /remote.php/dav
}

media.haddock.cc {
    route {
        authorize with mypolicy
        reverse_proxy jellyfin:8096
    }
}

indexers.haddock.cc { # Prowlarr
    route {
        authorize with mypolicy
        reverse_proxy prowlarr:9696
    }
}

tv.haddock.cc { # Sonarr
    route {
        authorize with mypolicy
        reverse_proxy sonarr:8989
    }
}

movies.haddock.cc { # Radarr
    route {
        authorize with mypolicy
        reverse_proxy radarr:7878
    }
}

prowl.haddock.cc {
    route {
        authorize with mypolicy
        reverse_proxy prowlarr:9696
    }
}

localhost:8112 { # QBittorrent
    reverse_proxy torrent:8080
}
```

**Comment by greenpau** [comment]
@lumbo7332 please try changing all to “authorize * with mypolicy” and see if it make a difference. I wonder whether the “*” matcher will make a difference with reverse_proxy.

**Comment by lumbo7332** [comment]
Nope. That started spamming the original error message again.

**Comment by greenpau** [comment]
Will try getting to it tomorrow! Thank you for sponsoring the project! :-)

**Comment by lumbo7332** [comment]
No problem! I really appreciate you being so helpful!

**Comment by poperigby** [comment]
Do you mind re-opening the issue?

**Comment by greenpau** [comment]
@poperigby , sure.

1. please add “order authorize before reverse_proxy”
2. Remote default routes, i.e. “route {“
3. Replace “ authenticate * with myportal” with “ authenticate    
  with myportal”
4. Create gist with caddyfile, logs, and output of caddy list-module

**Comment by greenpau** [comment]
@poperigby , pleas enable debug too.

**Comment by poperigby** [comment]
> Remote default routes, i.e. “route {“

Do you mean **remove**, or am I misunderstanding?

**Comment by greenpau** [comment]
> Do you mean remove, or am I misunderstanding?

do not use them in this particular config. E.g.

foo.haddock.cc {
        authorize with mypolicy
        reverse_proxy bar
}

> Should I do this for everything, or just my auth URL?

For authenticate and authorize

**Comment by poperigby** [comment]
I'm guessing I should order `authenticate` as well? I'm getting this error:
```
run: adapting config using caddyfile: directive 'authenticate' is not ordered, so it cannot be used here
```
[Caddyfile](https://gist.github.com/poperigby/7238c03406f63e75c4c09fb9cd4a444b)

**Comment by greenpau** [comment]
> I'm guessing I should order authenticate as well? I'm getting this error:

@poperigby , yes. try:

```
order authenticate before reverse_proxy
```

Please create a "secret" gist with the logs and send me the link over email.

**Comment by greenpau** [comment]
@poperigby , I got the logs. I will release a new version of `caddy-trace` (current `trace` version would not work). You would need to enable it in this fashion.

```
media.haddock.cc {
    trace tag="TSHOOT"
    authorize with mypolicy
    reverse_proxy jellyfin:8096
}
```

Will ping you back when ready.

**Comment by greenpau** [comment]
@poperigby , actually, the current version works. Compile the binary with `caddy-trace` and add the following:

```
order authenticate first
order trace before reverse_proxy 
order authorize before reverse_proxy 


media.haddock.cc {
    trace tag="TSHOOT-media"
    authorize with mypolicy
    reverse_proxy jellyfin:8096
}

indexers.haddock.cc { # Prowlarr
    trace tag="TSHOOT-indexers"
    authorize with mypolicy
    reverse_proxy prowlarr:9696
}
```

Add the trace directive to all your "authorized" endpoint. Please send me "secret" gist over email.

**Comment by poperigby** [comment]
Sure thing.

**Comment by greenpau** [comment]
> Sure thing.

@poperigby , please uncomment the lines with `{env.JWT_SECRET}` in the config and re-upload trace log. I want to see whether having HS keys would make a difference.

**Comment by poperigby** [comment]
I haven't generated a JWT secret, and what looks to be the docs for generating one is a dead link: https://github.com/greenpau/caddy-authorize#token-verification

**Comment by greenpau** [comment]
> I haven't generated a JWT secret, and what looks to be the docs for generating one is a dead link: https://github.com/greenpau/caddy-authorize#token-verification

@poperigby , just put any string that would match between the two references. If you don't have shared keys, the keys will be auto-generated for you. I want to see whether shared keys work. If they do, then I will look into auto-generation code.

```
crypto key sign-verify 38f21186-af0a-4cb0-8752-9eb65925ddf1
crypto key verify 38f21186-af0a-4cb0-8752-9eb65925ddf1
```

**Comment by greenpau** [comment]
The docs are here: https://authp.github.io/docs/authorize/token-verification

**Comment by poperigby** [comment]
Okay I got it. Sent it to you.

**Comment by greenpau** [comment]
@poperigby , after the upgrade to [v1.0.6](https://github.com/greenpau/caddy-security/releases/tag/v1.0.6) you should see log messages identifying source ip address and, if available, user metadata.

```
2022/01/24 22:36:47.986 ERROR   http.handlers.authentication    auth provider returned error
{
  "provider": "authorizer",
  "error": "user authorization failed: src_ip=10.0.2.2, src_conn_ip=10.0.2.2, reason: user role is valid, but not allowed by access list"
}


2022/01/24 22:27:35.498 ERROR   http.handlers.authentication    auth provider returned error    
{
  "provider": "authorizer",
  "error": "user authorization failed: src_ip=10.0.2.2, src_conn_ip=10.0.2.2, jti=AHfMISbvciNTtnj5dbUP5BK1qD75qi4Pq83iC8QO, email=webadmin@localdomain.local, sub=webadmin, reason: keystore: parsed token has expired"
}
```
