### ISSUE TITLE
question: different up headers by role

### ISSUE THREAD

**Issue by Frando** [greenpau/caddy-security#105]
Hi,
thanks for this project, it's working great for us!
I'm using a configuration with an upstream OpenID provider. I have configured two authorization policies that match on the roles returned from the OpenID provider. This works well, and I can make different resources accessible through these policies.

```
    authorization policy oursite_member {                                                                                                                             
      set auth url https://portal.oursite.de/oauth2/oursite/
      [...]
      allow roles member
    }

    authorization policy oursite_admin {
      set auth url https://portal.oursite.de/oauth2/oursite/
      [...]
      allow roles admin
    }
```
Now, I'm using a few admin-only resources with proxy header auth. E.g.
```
grafana.oursite.de {
    authorize with oursite_admin
    reverse_proxy grafana:3000 {
      header_up X-Auth-User admin
    }
}
```
Now I'd like to make grafana accessible to non-admin members, but with restricted permissions (view only). For that it'd be most convenient to pass a *different* header value if a user only matches the oursite_member policy but not the ourisite_admin policy. Something like (imaginary syntax):
```
grafana.oursite.de {
    authorize with oursite_member
    reverse_proxy grafana:3000 {
      header_up X-Auth-User member
      if user_has_role admin {
        header_up X-Auth-User admin
      }
    }
}
```
Is this possible? What would be the correct syntax?

Thanks,
Franz

**Comment by greenpau** [comment]
> Is this possible? What would be the correct syntax?

@Frando , here is how you should go about it. 

When `authorize` plugin passes a request to the next plugin, e.g. `reverse_proxy`, it inject a number of items into caddy context.

Please see https://github.com/greenpau/caddy-security/issues/66#issuecomment-1075744577

```
"{http.auth.user.id}"
"{http.auth.user.claim_id}"
"{http.auth.user.sub}"
"{http.auth.user.email}"
"{http.auth.user.name}"
"{http.auth.user.roles}"
```

You can then access these variables. Please see https://github.com/greenpau/caddy-security/issues/66#issuecomment-1075777964

Now, please open an issue https://caddy.community/ and ask how to match on the `{http.auth.user.roles}`. 

Hope this helps!

**Comment by Frando** [comment]
Thanks @greenpau !
In the meantime I also found another way how to solve this, documenting here for others who might be interested:

I added an `action add` directive with a custom scope to the two user transforms for the different roles. As they are evaluated in-order, the second one overrides the first one if it applies. Thus, if the transforms are ordered from low-to-high privilege, the custom scope is set to the highest privilege the user has.
```
 transform user {
        match realm oursite
        match group member
        action add authlevel member as string
      }

      transform user {
        match realm oursite
        match group admin
        action add authlevel admin as string
      }
```

I then used this custom scope to inject a header with its value, which I then use e.g. in grafana to set a user account from the header value, which are assigned the respective access policies without having to go through the hurdles of configuring individual accounts for individual users (which we don't need here).

```
 authorization policy oursite_member {
      set auth url https://portal.oursite.de/oauth2/oursite/
      crypto key verify {env.JWT_SHARED_KEY}
      allow roles admin member
      validate bearer header
      inject header "X-Auth-Level" from authlevel
    }

    authorization policy oursite_admin {
      set auth url https://portal.oursite.de/oauth2/oursite/
      crypto key verify {env.JWT_SHARED_KEY}
      allow roles admin
      validate bearer header
      inject header "X-Auth-Level" from authlevel
    }
```

I might try your solution too, thanks for the hints! For now, this setup works great for us as well.

**Comment by greenpau** [comment]
@Frando , perfect! Please consider sponsoring and promoting this project 😄
