### ISSUE TITLE
question: Having a hard time with authentication through Argo Tunnel

### ISSUE THREAD

**Issue by TtheBC01** [greenpau/caddy-security#106]
Hi!

I'm trying to use the caddy security plugin to provide authentication for a browser-based IDE (Theia Framework) I'm setting up for remote development (full code available here: https://github.com/TtheBC01/browser-ide). 

When I access the application locally, the auth plugin works great, but when I throw an argo tunnel in front of it and try to access remotely, after I give the username, I get an unauthorized page (401).
![image](https://user-images.githubusercontent.com/6946868/168879079-a2eff53f-2ea7-47f7-9a10-0c336466658c.png)

This setup used to work great for me with the previous auth plugin, `caddy-auth-jwt`, so I'm just trying to figure out what I'm missing
in trying to upgrade my setup to `caddy-security`. Thank you for any help you might offer.

**Comment by greenpau** [comment]
@TtheBC01 , what is the config? Please output `/whoami` contents.

**Comment by TtheBC01** [comment]
ok, if i got to `/whoami` after authenticating locally I get

```
{
  "addr": "172.31.0.1",
  "authenticated": true,
  "email": "admin@outlook.com",
  "exp": 1652814189,
  "expires_at_utc": "Tue May 17 19:03:09 UTC 2022",
  "iat": 1652810589,
  "iss": "http://localhost:8888/login",
  "issued_at_utc": "Tue May 17 18:03:09 UTC 2022",
  "jti": "BaTbQAfI76SzRaTCh4wQvMD4Lv6zv8Zr86X8UxzN6fCf",
  "nbf": 1652810529,
  "not_before_utc": "Tue May 17 18:02:09 UTC 2022",
  "origin": "local",
  "roles": [
    "authp/admin"
  ],
  "sub": "admin"
}
```

**Comment by greenpau** [comment]
@TtheBC01 , config?

**Comment by TtheBC01** [comment]
This is the Caddyfile: https://github.com/TtheBC01/browser-ide/blob/main/Caddyfile

**Comment by TtheBC01** [comment]
Sorry, is config different than Caddyfile?

**Comment by greenpau** [comment]
@TtheBC01 , try adding `cookie insecure on`. I don't see your HTTPS config, so I am assuming it is related to the cookies.

**Comment by TtheBC01** [comment]
Hmmm, that was a good idea, but still same problem. I guess I may have to live with the fact that anonymous tunnels won't work and I'll have to have TLS configured for a specific domain?

**Comment by greenpau** [comment]
> Hmmm, that was a good idea, but still same problem

@TtheBC01 , how about we get on the Google Meet at 5:30 EST today and I will take a look at your setup? It is hard to troubleshoot something like this in an issue.

**Comment by TtheBC01** [comment]
Absolutely!

**Comment by greenpau** [comment]
> Absolutely!

Please send me an invite to greenpau|outlook.com

**Comment by TtheBC01** [comment]
Done

**Comment by TtheBC01** [comment]
Just wanted to come back to this thread and say that if you use Argo Tunnel authenticated against you Cloudflare account (instead of using an anonymous tunnel), then this issue does not arise. I was able get everything working properly by specifying a tunnel token with no changes to the Caddyfile.

**Comment by greenpau** [comment]
@TtheBC01 , good stuff! I am still adding the ability to strip domain from the token. Currently, working on UI changes. Then, I will jump to this one.

**Comment by greenpau** [comment]
@TtheBC01, I am looking to add testimonial sections to https://authcrunch.com. Could you please write one and send it to me at greenpau@outlook.com?

**Comment by TtheBC01** [comment]
done
