### ISSUE TITLE
feature: Remove domain from cookie

### ISSUE THREAD

**Issue by TtheBC01** [greenpau/caddy-security#107]
Continued from issue #106 

For reference, here is a trace:

```json
{
   "level":"debug",
   "time":"2022-05-17T22:06:58.948Z",
   "msg":"debugging response",
   "request_id":"2be10c67-59b0-470c-b74d-1eec2bb32f86",
   "direction":"outgoing",
   "tag":"XYZ",
   "status_code":303,
   "response_size":0,
   "buffer_size":0,
   "response_headers":{
      "Cache-Control":[
         "no-store"
      ],
      "Location":[
         "https://density-why-judge-epinions.trycloudflare.com/auth/sandbox/H1bTYMvZQHS4TBkL2Yy68XHOze2mazwY0ONElbBO8K62Y"
      ],
      "Pragma":[
         "no-cache"
      ],
      "Server":[
         "Caddy"
      ],
      "Set-Cookie":[
         "AUTHP_SANDBOX_ID=PKc832f47HN4cc0t4RrBLQyedZAuYucx6WyGPFA7kD; Domain=trycloudflare.com; Path=/;"
      ]
   }
}
```

**Comment by greenpau** [comment]
@TtheBC01 , as discussed, would add a Caddyfile directive to remove domain from the issued cookies.

**Comment by greenpau** [comment]
@TtheBC01 , I am about to release new version.

Please add the following directive. The `cookie strip domain` would instruct the plugin to omit the injection of Domain into a cookie. 

```
authentication portal <name> {
  cookie strip domain
}
```

Please test and let me know how it goes 😄

**Comment by TtheBC01** [comment]
Just tried it out with the latest version of the plugin. Adding `cookie strip domain` works great, anonymous tunnels supported now. Updated login forms look nice too!

**Comment by greenpau** [comment]
> Just tried it out with the latest version of the plugin. Adding cookie strip domain works great, anonymous tunnels supported now. Updated login forms look nice too!

@TtheBC01 , glad to hear that the guess was correct! 👍 Enjoy the weekend!
