### ISSUE TITLE
feature: Nextcloud OIDC support

### ISSUE THREAD

**Issue by poperigby** [greenpau/caddy-security#11]
This is a continuation of https://github.com/greenpau/caddy-auth-portal/issues/227#. I think it would be a useful feature to be able to login to Nextcloud with Caddy Security account, and for Caddy Security to automatically create new Nextcloud users based on Caddy Security users. This can be done with OIDC, correct?

**Comment by greenpau** [comment]
>  This can be done with OIDC, correct?

@lumbo7332 , yes, you need to setup the OIDC provider in the Nextcloud. Basically, it follows OAuth mode.

You would need to create "bypass" for anything that required for the OIDC provider.

**Comment by lumbo7332** [comment]
I need to setup the OIDC provider in Nextcloud? I thought it was the other way around. And for finding what to add bypasses for, should I use my browser's DevTools and see what is being blocked? Some elaboration on that part would be much appreciated.

**Comment by greenpau** [comment]
> I need to setup the OIDC provider in Nextcloud?

@lumbo7332 , yes, you set up Nextcloud instance to be OIDC provider, i.e. it stores usernames/passwords and provides login form.

**Comment by lumbo7332** [comment]
Oh okay. And what about setting up the bypasses? I'm still a bit confused on how to do that.

**Comment by lumbo7332** [comment]
By being rerouted to a certain endpoint?

**Comment by greenpau** [comment]
> By being rerouted to a certain endpoint?

@lumbo7332 , you are attempting to authenticate. The portal sends you to the nextcloud server. The nextcloud server has `authorize` in place, so you never get to nextcloud server (and never get authenticated).

So, say nextcloud has OIDC endpoint `/oidc/*`. You create a `bypass uri prefix /oidc/` and then the `authorize` will not block that traffic.

Next, you get to `/oidc/provider.html`.

The HTML page has a reference to load Javascript from `/js/oidc.js` ... That is not in your bypass for the `authorize` plugin. The attempt to load Javacript will fail and you get redirected to portal without being successfully authenticated.

Hope this helps.

**Comment by lumbo7332** [comment]
Okay I think I understand. And I should still be using the `nextcloud_oauth2_backend`? Is that a custom backend for working with Nextcloud's OAuth?

**Comment by greenpau** [comment]
@lumbo7332 , first, work on setting up Nextcloud OIDC provider. You want Nextcloud to serve: `.well-known/openid-configuration` file. 

it should output similar output: https://swagger.io/docs/specification/authentication/openid-connect-discovery/

instead of `https://example.com/authorize`, it would likely be `https://<NEXTCLOUD_SERVER>/authorize`

**Comment by lumbo7332** [comment]
Okay. I'm still a little bit confused why Caddy Security isn't the provider. I'm looking at the docs for the [Nextcloud OIDC app](https://github.com/pulsejet/nextcloud-oidc-login), and it seems to want the SSO app to be the provider. It also fundamentally doesn't make sense to me. Why would you want the thing you're trying to login to provide your credentials? Or am I looking at this the wrong way?

**Comment by greenpau** [comment]
The https://github.com/pulsejet/nextcloud-oidc-login is not what you need. It is "login to nextcloud through keycloak (OIDC provider".

You need "login to caddy throught nextcloud"

**Comment by lumbo7332** [comment]
That's what I'm confused about. I wanted to login to Nextcloud using my Caddy Security user.

**Comment by greenpau** [comment]
@lumbo7332 login or access?

**Comment by lumbo7332** [comment]
Login. So I can add a user to Caddy Security, and then they can login to Nextcloud without having to manually add another user on Nextcloud.

**Comment by greenpau** [comment]
“access” means the following.

For example, i could have “authorize” plugin protecting nextcloud server. I authenticate to caddy auth portal, the I click the “Nextcloud” link and get redirected to authorize-protected Nextcloud server.


The authorize plugin validates my credentials and passes me to Nextcloud server via reverse proxy.

Nextcloud does not perform any authentication/authorization and allows me browsing it.

in this case Nextcloud can determine the identity based on some “X-“ HTTP header.

**Comment by lumbo7332** [comment]
Would that also create new users based on Caddy Security users?

**Comment by greenpau** [comment]
> they can login to Nextcloud without having to manually add another user on Nextcloud.

this may sound like you want auth portal to be “OIDC provider”.

**Comment by greenpau** [comment]
> Would that also create new users based on Caddy Security users?

no, just assumes an identity.

**Comment by lumbo7332** [comment]
Can the auth portal be a OIDC provider? Because that's exactly what I want.

**Comment by greenpau** [comment]
@lumbo7332 , in short you are asking for a feature where Auth Portal becomes OIDC provider for NextCloud.

**Comment by lumbo7332** [comment]
Yes.

**Comment by greenpau** [comment]
> Yes

@lumbo7332 , will think how to accomplish this.

**Comment by lumbo7332** [comment]
Thank you!

**Comment by greenpau** [comment]
Someone else asked for it too. I never got to it. I think now is the time.

**Comment by poperigby** [comment]
@greenpau just to clarify, do you mean you'll be adding support for Caddy Security to be an OIDC provider?

**Comment by greenpau** [comment]
> do you mean you'll be adding support for Caddy Security to be an OIDC provider?

Yes. Just like Google, Facebook, Github, Gitlab, etc.

**Comment by poperigby** [comment]
Great! Thanks!

**Comment by greenpau** [comment]
> Great! Thanks! Should the issue be renamed to "OIDC provider support"?

@poperigby , I will be opening a separate issue for the feature.

**Comment by greenpau** [comment]
Added https://github.com/greenpau/caddy-security/issues/29
