### ISSUE TITLE
Caddy cannot come up when authentication provider is also hosted by caddy

### ISSUE THREAD

**Issue by jhogendorn** [greenpau/caddy-security#110]
I run fusionauth (https://fusionauth.io/) at https://auth.mydomain.org/, in a docker container. its reverse proxied by caddy.

If i configure caddy-security, caddy cannot come up any more because it fails to fetch metadata for oauth2.0 authorization server, because it gets 443 denied, because caddy is not up yet.

Aside from doing some overwrought double reverse proxy setup to split between systems, is there any way to elegantly work around this issue?

**Comment by greenpau** [comment]
> If i configure caddy-security, caddy cannot come up any more because it fails to fetch metadata for oauth2.0 authorization server, because it gets 443 denied, because caddy is not up yet.

@jhogendorn , please share you config.

Did you look into adding "delay" and "retry" settings?

https://authp.github.io/docs/authenticate/oauth/backend-oauth2-endpoint#oauth-20-endpoint-delayed-start

**Comment by greenpau** [comment]
@jhogendorn , you don’t need authentication portal if you have Fusion. After you login to Fusion as a user, what cookies do you see?

In short, Fusion issues a cookie. You task is to configure the “policy” to read the token issues by Fusion.

i am on EST and can be available after 5pm to do google meet. If interested, email me greenpau|outlook.com

**Comment by jhogendorn** [comment]
FWIW, I have gotten this working by using the auth portal. It just has some sharp edges where sometimes a user wont be redirected back to their application, and instead get stuck at the blank 'services' screen with the logout button.
