### ISSUE TITLE
feature: Proper focus/tab order for default login template

### ISSUE THREAD

**Issue by jesjimher** [greenpau/caddy-security#119]
> A clear and concise description of what you want the system to do.

Default login template doesn't place keyboard focus on the text field, so entering username requires clicking in the field first, and then writing the username (alternatively, you can also press tab twice in order to set focus to the field). Same happens in password screen, so another extra click is needed to be able to input password. It would be nice if text fields were already "focused", so users could start writing the moment the screen is shown, without extra clicks/tabs.

I know this could be achieved by using custom templates, but I think it's a general UI improvement that could benefit default templates.

Thanks a lot for your attention, and for creating such a great piece of software!

**Comment by greenpau** [comment]
@jesjimher , thank you for the issue! Great point!

**Comment by greenpau** [comment]
Working on it. It will be in the next release.

**Comment by greenpau** [comment]
@jesjimher , please test with the latest release and let me know how it goes.

**Comment by jesjimher** [comment]
Works like a charm! Thanks for the quick fix!

**Comment by greenpau** [comment]
@jesjimher , I am looking to add testimonial sections to https://authcrunch.com. Could you please write one and send it to me at greenpau@outlook.com?
