### ISSUE TITLE
breakfix: Access token set without expiry, still gets 401, and doesn't redirect to provided auth url

### ISSUE THREAD

**Issue by johnpyp** [greenpau/caddy-security#12]
**Describe the issue**

After logging in at https://auth.MYDOMAIN.com, the auth portal sets a cookie without a Max-Age or expires attribute set, meaning it only lives as long as the session. Example set-cookie header in the response of `/oauth2/github/authorization-code-callback?code=OAUTH_CODE...` after logging in with github:
```
set-cookie: access_token=eyJhbGciOiJI....; Domain=MYDOMAIN.com; Path=/; Secure; HttpOnly;
```

Also, the access token itself doesn't seem to work at all with my current configuration, and I get a 401 on the example domain of this config https://sonarr.MYDOMAIN.com, with error logs like:
```
{"level":"debug","ts":1642792571.8178122,"logger":"security","msg":"token validation error","session_id":"cO9Fu3cuNuNg5ufIugXgZphXU5MSzEFhfByBX0ojPb8","request_id":"26a2f6a9-51fb-4be8-92ac-85f40eefbfd5","error":"token validator: invalid token: keystore: failed to parse token"}
{"level":"error","ts":1642792571.8178322,"logger":"http.handlers.authentication","msg":"auth provider returned error","provider":"authorizer","error":"user authorization failed"}
```
and it just redirects to `https://sonarr.MYDOMAIN.com/?redirect_url=https%3A%2F%2Fsonarr.MYDOMAIN.com%2F`, rather than redirecting to `https://auth.MYDOMAIN.com` as I'd expect.

My very very similar config previously using caddy-authorize and caddy-auth-portal worked fine, I've basically just moved around the attributes to be inline with how the new config format looks, and I used the jumpcloud config as my example. 

**Configuration**

```
{
        debug
        order authorize before basicauth
        email {$CF_EMAIL}
        auto_https ignore_loaded_certs

        security {
                authentication portal mainportal {
                        crypto default token lifetime 2419200
                        crypto key sign-verify {$CADDY_AUTH_TOKEN_SECRET}
                        cookie domain {$DOMAIN}
                        backend local {$CADDY_AUTH_USERS_PATH} local
                        backend github {$CADDY_GITHUB_OAUTH_CLIENT_ID} {$CADDY_GITHUB_OAUTH_CLIENT_SECRET}
                        transform user {
                                exact match sub github.com/johnpyp
                                action add role authp/admin
                                action add role superadmin
                        }
                        transform user {
                                match email webadmin@localdomain.local

                                action add role authp/admin
                                action add role superadmin
                        }
                }

                authorization policy mainpolicy {
                        set auth url https://auth.{$DOMAIN}
                        allow roles admin superadmin authp/admin
                        crypto key verify {$CADDY_AUTH_TOKEN_SECRET}
                }
        }
}

(cf_tls) {
        tls {
                issuer zerossl {
                        resolvers 1.1.1.1
                        dns cloudflare {$CF_API_TOKEN}
                }
        }
}

auth.{$DOMAIN} {
        import cf_tls
        route {
                authenticate * with mainportal
        }
}

(protected_route) {
        {args.0}.{$DOMAIN} {
                import cf_tls
                authorize with mainpolicy
                route {
                        reverse_proxy {args.1}
                }
        }
}

import protected_route sonarr sonarr:8989
// ...
```

**Version Information**

Should be latest everything, just pulled a few minutes ago with this docker image:
```
FROM caddy:2-builder AS builder

RUN xcaddy build \
    --with github.com/greenpau/caddy-security \
    --with github.com/caddy-dns/cloudflare

FROM caddy:2

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

**Comment by johnpyp** [comment]
It seems that adding this makes the authorization work properly and I no longer receive 401s,
```
    order authorize before reverse_proxy
    order authenticate before authorize
```
from the example config given in this similar issue https://github.com/greenpau/caddy-security/issues/10

**Comment by greenpau** [comment]
@johnpyp, are you able to authenticate to the portal and browse to "/whoami" endpoint, i.e. `https://auth.{$DOMAIN}/whoami`? 

If yes, please paste the JSON you see there.

**Comment by johnpyp** [comment]
Actually, it seems that that order block has made it so I can access any of my "protected" services without auth...

**Comment by greenpau** [comment]
> Actually, it seems that that order block has made it so I can access any of my "protected" services without auth...

@johnpyp , what about if you just keep the following?

```
order authorize before reverse_proxy
```

**Comment by greenpau** [comment]
@johnpyp , please remove the ordering for now.

Change:

```

(protected_route) {
        {args.0}.{$DOMAIN} {
                import cf_tls
                authorize with mainpolicy
                route {
                        reverse_proxy {args.1}
                }
        }
}
```

To:

```

(protected_route) {
        {args.0}.{$DOMAIN} {
                import cf_tls
                route {
                        authorize with mainpolicy
                        reverse_proxy {args.1}
                }
        }
}
```

**Comment by johnpyp** [comment]
@greenpau Removing all the ordering and changing the authorize block to the route doesn't throw any ordering errors, but still exhibits the same behavior. (401, not setting max-age, improper redirect)

**Comment by greenpau** [comment]
> but still exhibits the same behavior. (401, not setting max-age, improper redirect)

@johnpyp , let me recreate it.

**Comment by greenpau** [comment]
@johnpyp , confirmed bug with validator. Working on a fix.

**Comment by greenpau** [comment]
@johnpyp , released fix in https://github.com/greenpau/caddy-security/releases/tag/v1.0.2

Please retest and re-open if necessary.

Do not use `order`, use `routes`. See https://gist.github.com/greenpau/6abb58bf7b523210c39c8138c6a6417f

**Comment by johnpyp** [comment]
@greenpau Thanks, it seems like the auth and redirect part of the bug have been fixed. The expiry/max-age bug seems to still be present though as far as I can tell, as in the max-age is unset and so the browser just makes it "Session".

**Comment by greenpau** [comment]
> The expiry/max-age bug seems to still be present though as far as I can tell, as in the max-age is unset and so the browser just makes it "Session".

@johnpyp , please explain this again. I am not sure I understood it.

**Comment by johnpyp** [comment]
What I mean is the `Set-Cookie` header for the `access_token` cookie, from the response of the `authorization-code-callback` route, doesn't include an `Expires` or `Max-Age` attribute. This makes it so that browsers think the cookie is a session-only cookie and such will wipe it upon restart of the browser, or if you restart the caddy server and navigate to the auth route, it will wipe it too (I'm not entirely sure why it only wipes upon restart of the server).

What I would expect is that the `lifetime` parameter sets the Max-Age/Expires attribute on the cookie. Looking at the code very loosely it seems that it should set it, so I'm not sure what's wrong: 
![image](https://user-images.githubusercontent.com/20625636/150611307-9056b838-0f52-46f6-b8af-949ae07b3203.png)

**Comment by greenpau** [comment]
> What I would expect is that the lifetime parameter configures what the plugin sets the Max-Age/Expires attribute to on the cookie. Glancing at some of the code, it seems that it should set it, so I'm not sure what's wrong:

@johnpyp , looking 👀 into it right now!

**Comment by greenpau** [comment]
@johnpyp , please try setting “cookie lifetime” and let me know if you see better results. https://authp.github.io/docs/authenticate/auth-cookie

**Comment by greenpau** [comment]
@greenpau , please note that “cookie lifetime <seconds>” is not the same as “crypto default token lifetime <seconds>”. 

you could have jwt token that expires every 15 minutes, but http cookie having max age 15 day. 

The unauthorized user redirect takes into the account the expired cookie when determining where to redirect. You can achieve flawless SSO (user never have to click anything)z

**Comment by johnpyp** [comment]
Ah I see, in that case what would cause the user to be logged out when the caddy server is restarted? Is there some login state that's only held in memory?

**Comment by greenpau** [comment]
> Ah I see, in that case what would cause the user to be logged out when the caddy server is restarted? Is there some login state that's only held in memory?

@johnpyp , yes ;-) and the expired (but valid) jwt token in non-expired cookie would provide a clue as to how the user originally authenticated.
