### ISSUE TITLE
question: KeyCloak logout problem

### ISSUE THREAD

**Issue by scorday** [greenpau/caddy-security#129]
Hello! I deployed Caddy + Caddy-Security + KeyCloak according to your documentation. Works really good except one thing: logout.

Steps to to produce:
1) Open https://auth/login and press Keycloak.
2) Fill the keycloak's login form and do login.
3) Check /whoami and then go to /logout.
4) Now portal redirects you to its root.
5) Now you are logouted from portal, but not from keycloak. To check it try to repeat steps 1-4 and there won't be step 2.

Is there any way to logout from keycloak when i open http://auth/logout?

**Comment by greenpau** [comment]
> Is there any way to logout from keycloak when i open http://auth/logout?

@scorday , there actually is a way 😄 I made a note to myself to add (and describe) it to documentation https://github.com/authp/authp.github.io/issues/30

The `enable logout` under your KeyCloak provider would cause it to go to KeyCloak to logout there.

I never actually tested it with KeyCloak. The relevant functions are here.

https://github.com/greenpau/go-authcrunch/blob/5473bfab6b931ba1612a32a5dd1d4590d3a5ac35/pkg/authn/handle_external_http_logout.go#L52-L61

https://github.com/greenpau/go-authcrunch/blob/ad9456bac8e30ec3a669a4a8c852fdb577ae3bad/pkg/idp/oauth/provider.go#L454-L460

It relies on the presence of `end_session_endpoint` in well-known config.

https://github.com/greenpau/go-authcrunch/blob/ad9456bac8e30ec3a669a4a8c852fdb577ae3bad/pkg/idp/oauth/provider.go#L366-L368

In theory it should work for you https://www.keycloak.org/docs/latest/server_admin/

> Backchannel Logout URL
> URL that will cause the client to log itself out when a logout request is sent to this realm (via end_session_endpoint). If omitted, no logout requests are sent to the client.

**Comment by greenpau** [comment]
@scorday , I saw you forking Angular stuff. I haven't touched it in a while. If you make it, work, please send PR my way 😄

**Comment by scorday** [comment]
@greenpau Tested it already 2 min ago! It works, thanks! 

Is there any way to specify post_logout uri? For example to go to login page right after logout.

**Comment by scorday** [comment]
@greenpau And more. Let's say i'm logged in in portal using user USER and /whoami working. 
From incognito i go to keycloak admin and kill all USER sessions, but i'm still logged in in portal and page refresh doesn't help :(

**Comment by greenpau** [comment]
> From incognito i go to keycloak admin and kill all USER sessions, but i'm still logged in in portal and page refresh doesn't help :(

@scorday, interesting point. It is a feature that is not there. The `/whoami` would need to accept a parameter that would instruct it to use Keycloak's granted access token to get user info. If it is not responding (e.g. token is no longer valid) - terminate user session.

**Comment by greenpau** [comment]
@scorday , have you considered using KeyCloak's ID token to perform the checks you are looking for? See `/whoami` args. https://github.com/authp/authp.github.io/issues/28#issue-1259032649
