### ISSUE TITLE
feature: auto-redirect to IDP when only one exists

### ISSUE THREAD

**Issue by clintharrison** [greenpau/caddy-security#132]
I'm using caddy-security with a single authn backend.

Instead of presenting a login page with a single button, it'd be great if `/login` redirected there immediately, since that's what the user will do anyway.

I suppose we could add a Caddyfile directive so this is opt-in behavior :)

**Comment by greenpau** [comment]
@clintharrison , have you looking into adding custom javascript to do the automatic redirect? https://authp.github.io/docs/authenticate/ui-features#javascript

**Comment by greenpau** [comment]
This feature does make sense. Will add it next time I do the refactoring of UI

**Comment by icsy7867** [comment]
Looking for this now as well.

**Comment by greenpau** [comment]
This feature is available and already implemented. Some keywords. You must configure “trust logout redirect uri” to safely use it.

**Comment by icsy7867** [comment]
Sorry for dropping in here again, I can make a new issue if that's better, but I am hoping this will be a quick answer.  I am a bit confused on using "trust logout redirect uri" to automatically initiate a login.  This reads as though it is used as a redirection when a logout is performed.

I tried adding this to my caddy file:
`trust logout redirect uri domain {http.request.host} path /auth/oauth2/generic`

Hoping that it will automate the login process.  Currently I see this login portal:
<img width="501" alt="image" src="https://github.com/user-attachments/assets/c1031478-01cd-47b6-b1ef-2e0df705c84c">

And I would like to skip this, and automatically navigate to:
https://myapp.company.com/auth/oauth2/generic

**Comment by clintharrison** [comment]
I'm also not quite connecting the dots on how configuring a trusted logout redirect URL is related to redirecting on the login screen.

@greenpau do you have any more pointers? I am still getting along just fine with redirecting in the custom template, _but_ I'm not sure if this feature was actually implemented 🤔

**Comment by jmittermair** [comment]
Also support this feature, and I looked through the docs and don't see a way to do this without attempting custom JavaScript, as @greenpau originally mentioned above.

But it would certainly be nicer and more ergonomic to have it as part of the Caddyfile, since clicking the button is just an additional step for users with only one IdP 99% of the time, (unless they need to access the `/whoami` or `/profile` endpoints).
