### ISSUE TITLE
question: How to use LDAP auth with Jumpcloud

### ISSUE THREAD

**Issue by arhue** [greenpau/caddy-security#140]
Hello, 

I am trying to use anonymous bind with Jumpcloud in Caddy. However I can't seem to get it working. My settings for ldap look like this:

```
  $config['auth_mechanism'] = "ldap";
  $config['auth_ldap_version'] = 3;
  $config['auth_ldap_server'] = "ldap.jumpcloud.com"; 
  $config['auth_ldap_port'] = 389;
  $config['auth_ldap_prefix'] = "uid=";
  $config['auth_ldap_suffix'] = ",ou=Users,o=xxx,dc=jumpcloud,dc=com";
  $config['auth_ldap_groupbase'] = "ou=Users,o=xxx,dc=jumpcloud,dc=com";
  $config['auth_ldap_groupmemberattr'] = "member";
  $config['auth_ldap_groups'] = ['TestGroup' => ['level' => 10],];
  $config['auth_ldap_userdn'] = true;
```

I did take a look at example Caddyfile here: https://github.com/authp/authp.github.io/blob/main/assets/conf/ldap/Caddyfile, but I am very confused. On Caddy side I am trying to reverse proxy to backend server after authentication. Can you help me please? I don't mind contributing to better documentation after I understand how it works.

**Comment by greenpau** [comment]
@arhue , anonymous bind is unsupported.

**Comment by arhue** [comment]
@greenpau Thanks. Closing this issue.
