### ISSUE TITLE
Matching user transform with wildcards

### ISSUE THREAD

**Issue by smurfb** [greenpau/caddy-security#142]
First, thanks for a great product!

I am trying to do a user transform, but it doesnt seem to be able to match with wildcards? 

Emails that I want to match have different subdomains, like

user@department.company.com or user@subdep.department2.company.com and I want to match all that ends with company.com regardless whats in front. Is that possible? 

Thanks!

**Comment by greenpau** [comment]
> I am trying to do a user transform, but it doesnt seem to be able to match with wildcards?

@smurfb , please provide your config. It should match any regex with 

`regex match <field> <value> ... <valueN>`

**Comment by smurfb** [comment]
I must have used the wrong command, it works now. Thanks a bunch!

**Comment by greenpau** [comment]
> I must have used the wrong command, it works now. Thanks a bunch!

@smurfb , awesome! Glad to worked.

P.S. "wrong command" => "wrong directive" (caddy thing)
