### ISSUE TITLE
question: Not redirected, callback URL?

### ISSUE THREAD

**Issue by darox** [greenpau/caddy-security#144]
> A clear and concise description of what you want to accomplish.

Hi, I'm totally new to Caddy after coming from Oauth2proxy. Currently I'm only experimenting locally with Github Oauth2 authz/authn. 

My config file is derived from https://github.com/authp/authp.github.io/blob/main/assets/conf/oauth/github/Caddyfile

```
{
        http_port 80
        debug
        order authenticate before respond
        order authorize before basicauth

        security {
                oauth identity provider github id secret

                authentication portal myportal {
                        crypto default token lifetime 3600
                        crypto key sign-verify {env.JWT_SHARED_KEY}
                        cookie domain site.example
                        enable identity provider github
                        ui {
                                links {
                                        "My Identity" "/whoami" icon "las la-user"
                                }
                        }

                        transform user {
                                match realm github
                                action add role authp/user
                                ui link "File Server" http://assets.site.example:8080/ icon "las la-star"
                        }

                        transform user {
                                match realm github
                                match sub github.com/darox
                                action add role authp/admin
                        }
                }

                authorization policy mypolicy {
                        set auth url http://auth.site.example:8080/oauth2/github
                        crypto key verify {env.JWT_SHARED_KEY}
                        allow roles authp/admin authp/user
                        validate bearer header
                        inject headers with claims
                }
        }
}

http://auth.site.example {
        authenticate with myportal
}

http://assets.site.example {
        authorize with mypolicy
        root * /usr/share/caddy
        encode gzip
        try_files {path} /index.html
        file_server
}
```

Behavior: 
1. I can access http://assets.site.example:8080 and I'm redirected to Github and login works
2. I can access http://auth.site.example:8080 and click on Github login and I'm redirected back with URL: http://auth.site.example:8080/oauth2/github/authorization-code-callback?code=xxx

Expectation: 
I would expect, that I'm successfully redirected to http://assets.site.example:8080

However, I'm not certain whether the callback URL is correct with?
`http://auth.site.example:8080/oauth2/github`

Thank you

**Comment by greenpau** [comment]
@darox , it should be this `https://auth.site.example:8080/oauth2/github/authorization-code-callback`

I notice you don’t use https. You should then use `cookie insecure on` (Please search issues based on “cookie” tag. One of the should have an explanation why it is needed).

**Comment by darox** [comment]
@greenpau Wow thank you! Works as expected. The point with the cookie insecure is understandable.

**Comment by greenpau** [comment]
@darox , glad it worked! Please help spread the word about this project ⭐

**Comment by darox** [comment]
@greenpau Sure. I will write a blog post soon. I have another question. 
In oauth2proxy there's the possibility to specify allowed groups in order to filter on them. Groups is a claim in this case. Is this also possible with Caddy Security?

**Comment by greenpau** [comment]
> Is this also possible with Caddy Security?

@darox , yes. Through user transforms. See https://authp.github.io/docs/authenticate/user-transforms and https://authp.github.io/docs/authorize/acl-rbac

The `groups` claims is always converted to `roles` claim in the backend of the plugin.

P.S. it is best opening a separate issue for questions.
