### ISSUE TITLE
feature: LDAP connection persistence

### ISSUE THREAD

**Issue by iamjrock** [greenpau/caddy-security#148]
> A clear and concise description of what you want the system to do.

In the LDAP IdP docs the following is mentioned:

"The plugin does not keep connections open to LDAP servers. The plugin tears a connection down each time it finishes authenticating a request associated with the connection."

This would probably put a lot of load on an ldap server for high volume auth traffic.  Some ldap services might even throttle caddy-security.

Does it make sense to enhance this so that ldap connections are persisted?

> What are the Caddyfile directives that need to be added.

n/a

**Comment by iamjrock** [comment]
Oh wait, I just realised why the connection is not kept persistent.  Its because of this, right?

> Once the plugin determines the user's roles, e.g. admin, editor, viewer, the plugin actually checks whether the user's password is valid.
> 
> It does so by doing LDAP re-binding with the user's DN and the password provided in the request. In this example, the user's DN is CN=Smith\\, John,OU=Users,DC=CONTOSO,DC=COM.
> 
> If the re-binding is successful, the plugin issues a JWT token.

**Comment by greenpau** [comment]
> Oh wait, I just realised why the connection is not kept persistent. Its because of this, right?

Yes. Basically, you want to use user-provided credentials to bind to the LDAP server.

**Comment by iamjrock** [comment]
Yep, understood.  Let's close this issue then.
