### ISSUE TITLE
question: Change logo on auth page 

### ISSUE THREAD

**Issue by CaKlau** [greenpau/caddy-security#153]
Hi everyone,

thanks a lot for your work, caddy-security works like a charm. 🙂

However I would like to customize my Auth portal `auth.mydomain.com`. At the moment it looks like that, I want to replace that logo and the Favicon.

![screen](https://user-images.githubusercontent.com/90129784/188270281-9f3dd43c-803a-4907-92f4-4669bec557a4.png)

The HTML source code reveals 
`
\<div>
  ...
  <img class="logo-img" src="/assets/images/logo.svg" alt="Authentication Portal" />
 ...
 \<div>
`

Where exactly can I find the ` /assets/images/` folder? Alternatively: how can I cange the logo/favicon directly over my Caddyfile?

Thanks in advance!

**Comment by greenpau** [comment]
@CaKlau , is your logo available externally or you want auth portal hosting the logo?

**Comment by CaKlau** [comment]
Hi @greenpau  

I am running caddy in a Docker container. Therefore I would like to mount the logo into the container and replace the existing logo.svg. Is that possible?

**Comment by greenpau** [comment]
> I am running caddy in a Docker container. Therefore I would like to mount the logo into the container and replace the existing logo.svg. Is that possible?

In that case, add the following to `authentication portal` config:

```
authentication portal <portal_name>{
  ui {
    logo url /assets/custom/logo.svg
    static_asset "assets/custom/logo.svg" "image/svg+xml" path/to/local/drive/logo.svg
```

If your image is png, then change `image/svg+xml` to `image/png`.

**Comment by CaKlau** [comment]
Great! That works. @greenpau  🙂
Is there a directive for the favicon as well? I tried `icon` and `favicon`, both did not work.

```
logo url /assets/images/myimage.png

icon url /assets/images/myimage.png

static_asset "assets/images/myimage.png" "image/png" /etc/caddy/assets/myimage.png
```

Once this is solved we can close the issue.

**Comment by greenpau** [comment]
@CaKlau , please open a separate issue for the favicon and make it a feature request.
