### ISSUE TITLE
question: add passkey support

### ISSUE THREAD

**Issue by gedw99** [greenpau/caddy-security#154]
> A clear and concise description of what you want to accomplish.

Passkeys are coming . Microsoft, google and Apple are all working on it and it’s now in iOS and Mac 

it would be cool if this can be supported. WebAuthn is already and so adding passkeys is likely to be the next step as passkeys are part of WebAuthn.

i found this example in golang . 
https://github.com/orgs/teamhanko/repositories

it might be a good resource and so posting it here if anyone else is interested

**Comment by greenpau** [comment]
@gedw99 , this is a long shot for now. I don’t have much time to invest in the research.

**Comment by gedw99** [comment]
no worries.

I got it working as a hacky prototype. I hope to publish this so it can be a plugin for caddy security stuff your doing.

**Comment by greenpau** [comment]
The passkey should now work out of the box. 

https://www.youtube.com/watch?v=6BWPu7127Bw

**Comment by greenpau** [comment]
> An End User would find that daunting to use IMHO.. Know what I mean ?

@gedw99 , not really. I onboarded passkeys from my iphone, ipad, windows hello and doing just fine. The key is onboarding app token first.

**Comment by greenpau** [comment]
> There is no way a user could do it imho .

@gedw99 , it is not geared towards ecommerce shopping cart solution.
