### ISSUE TITLE
question: pass original bearer token in header

### ISSUE THREAD

**Issue by coronabytes** [greenpau/caddy-security#156]
Hi,

Im evaluating if we can substitute our current setup of caddy + oidc-proxy with caddy+caddy-security.
And i got it "working" with the following setup:

```
{
    security {
		oauth identity provider keycloak {
			driver generic
			realm core
			client_id ***
			client_secret ***
			scopes openid email profile
			metadata_url https://***/realms/core/.well-known/openid-configuration
		}

		authentication portal myportal {
			crypto key sign-verify ***
			enable identity provider keycloak
                        cookie samesite strict
                        transform user {
		            match realm core
			    action add role authp/user
			}
		}

		authorization policy frontend_policy {                    
			set auth url https://authz.domain.com/oauth2/core
			crypto key verify ***
			allow roles authp/user
		}

                authorization policy backend_policy {
			disable auth redirect query
                        disable auth redirect
			crypto key verify ***
			allow roles authp/user
		}
}

*.domain.com {
     
    @app host app.domain.com
    handle @app {
        route {
	   authorize with frontend_policy
           #respond "Frontend"
           reverse_proxy 10.0.0.4:5000
	}
 
        route /api/* {
	  authorize with backend_policy
	  #respond "Backend"
          reverse_proxy 10.0.0.4:5000
	}        
    }

    @authz host authz.domain.com
    handle @authz {
        authenticate with myportal
    }
}
```

~~Now, is it possible to circumvent the ui authz.domain.com when there is only a single idp?~~
Found the set auth url .../oauth2/core trick in the other issue

and can i get the access token from keycloak (not caddy security access_token cookie!) passed as an authorization header for backend usage? (Authorization: Bearer <keycloal_access_token>)
I want to keep cloak as a direct authority for my backends and not caddy-security.

If it's not possible to configure yet, is this something that would even make sense to implement within the scope of this project?

**Comment by greenpau** [comment]
>  Found the set auth url .../oauth2/core trick in the other issue

@coronabytes , this is one option. Option 2: add custom JS to redirect to `/oauth2/core`. See https://authp.github.io/docs/authenticate/ui-features#javascript

> and can i get the access token from keycloak (not caddy security access_token cookie!) passed as an authorization header for backend usage? (Authorization: Bearer <keycloal_access_token>)

The closest to this is documented here. https://github.com/authp/authp.github.io/issues/28
It works with AWS Cognito. Cognito returns `access_token` and `id_token`. The plugin takes the value of `id_token` and injects it into environment variable. The cookie is then available to api/backend.

> If it's not possible to configure yet, is this something that would even make sense to implement within the scope of this project?

> and can i get the access token from keycloak (not caddy security access_token cookie!) passed as an authorization header for backend usage? (Authorization: Bearer <keycloal_access_token>)

^ I think it is doable. We would still need to pass the cookie. However, you will be able to take the cookie value and inject it as Bearer token in Authorization header.

**Comment by greenpau** [comment]
similar to `inject header <header_name> from <field_name>` (see https://authp.github.io/docs/authorize/headers#custom-headers)

I could add:

```
inject authorization bearer header from cookie <COOKIE_NAME>
```

**Comment by coronabytes** [comment]
well, i can tell you what oidc-proxy does.
it either stores the keycloak-access-token inside its own cookie and passes it down in the authorization header (and makes ridiculously large cookies)
or store a random id in cookie and hold the access/id/refresh token in a redis instance. (much smarter choice).

and when the access token is close to expiring it will try to refresh it.

now caddy-security has no concept of refreshing "original" access tokens at all, because it just extracts infos once and then uses its own access_token downstream correct?

**Comment by greenpau** [comment]
> now caddy-security has no concept of refreshing "original" access tokens at all, because it just extracts infos once and then uses its own access_token downstream correct?

Once authenticated, it does not care about access_token. If id_token is present, it could be used with a particular backend.

The token used for authorization is the token issued by the portal.

**Comment by coronabytes** [comment]
ok thanks,
I tried it with the id_token, however its on the authz subdomain, and no control over cookie domain so its accessible on the app subdomain? (maybe toss authz.domain.com and use app.domain.com/authportal ?)

and even then no refresh after 1 hour.

so I guess I'll stick with oidc-proxy for now.

caddy-security works fine however, when using "inject headers with claims" and downstream servers just rely on them and not jwt middleware.
