### ISSUE TITLE
breakfix: CHANGE_ME

### ISSUE THREAD

**Issue by whatgoesbump** [greenpau/caddy-security#160]
**Describe the issue**

I am trying to enable organizr. Nothing I do seems to get the security module working. I've compiled it 100 times, I've tried different versions of go, different install locations. I followed the guide, it just seems to ignore the security package, even though it shows as installed. Cloudflare still works, but it will not recognize `authorize` as a directive. Is the config wrong? 

**Configuration**

Paste full `Caddyfile` below:

```
# The Caddyfile is an easy way to configure your Caddy web server.
#
# Unless the file starts with a global options block, the first
# uncommented line is always the address of your site.
#
# To use your own domain name (with automatic HTTPS), first make
# sure your domain's A/AAAA DNS records are properly pointed to
# this machine's public IP, then replace ":80" below with your
# domain name.

(cloudflare) {
  tls {
    dns cloudflare X36XzkCjmhFUyAKfafMooYZ6Zm8x1k1JwgoXh67
  }
}
 

:80 {
    # Set this path to your site's directory.
    root * /usr/share/caddy

    # Enable the static file server.
    file_server

    # Another common task is to set up a reverse proxy:
    # reverse_proxy localhost:8080

    # Or serve a PHP site through php-fpm:
    # php_fastcgi localhost:9000

}

#test
#security { 
#    authorization policy admin {
#       #name : admin
#        set auth url https://website.com/auth
#        crypto key token name organizr_token_uuid
#        crypto key verify organizrHash
#        set token sources cookie
#        validate bearer header
#	}
#}

#security { 
#    authorization policy admin {
#    	#name : admin
#        set auth url https://website.com/auth
#        crypto key token name organizr_token_uuid
#        crypto key verify organizrHash
#        set token sources cookie
#        validate bearer header
#
#        # Log any admin
#        acl rule {
#            match iss Organizr
#            match role Admin
#            allow stop log info
#        }
#
#        # Log any denied 
#        acl rule {
#            match iss any
#            deny log warn
#        }
#    }
#
#    authorization policy user {
#        set auth url https://website.com/auth
#        crypto key token name organizr_token_uuid
#        crypto key verify organizrHash
#        set token sources cookie
#        validate bearer header
#
#        # Log any admin/user
#        acl rule {
#            match iss Organizr
#            match role Admin User
#            allow stop log info
#        }
#
#        # Log any denied 
#        acl rule {
#            match iss any
#            deny log warn
#        }
#    }
#}

website.com {
    root * /var/www/websites/organizr        
    php_fastcgi unix//run/php/php8.1-fpm.sock  
    rewrite /api/v2/* /api/v2/index.php?{query}
    file_server
}

#plex.website.com {
#    route /plex* {
#        authorize with admin
#        reverse_proxy http://127.0.0.1:32400/web
#        import cloudflare
#    } 
#}

#comics.website.com {
#    route /plex* {                    
#        authorize with admin     
#        reverse_proxy http://127.0.0.1:8616
#        import cloudflare
#    } 
#} 

#tautulli.website.com {
#    route /tautulli* {
#        #authorize with admin
#        reverse_proxy localhost:8181
#        import cloudflare
#    } 
#}

#nzb.website.com {       
#    route /nzbget* {                              
#        authorize with admin                    
#        reverse_proxy http://127.0.0.1:6789     
#        import cloudflare
#    } 
#}

#qbit.website.com {       
#    route /qbittorrent* {                              
#        authorize with admin                    
#        reverse_proxy http://10.0.0.11:8080     
#        import cloudflare
#    } 
#} 

#sonarr.website.com {       
#    route /sonarr* {                              
#        authorize with admin                    
#        reverse_proxy http://127.0.0.1:8989     
#        import cloudflare
#    } 
#} 

#radarr.website.com {       
#    route /radarr* {                              
#        authorize with admin                    
#        reverse_proxy http://127.0.0.1:7878     
#        import cloudflare
#    } 
#} 

#lidarr.website.com {       
#    route /lidarr* {                              
#        authorize with admin                    
#        reverse_proxy http://127.0.0.1:8686     
#        import cloudflare
#    } 
#} 

#readarr.website.com {       
#    route /readarr* {                              
#        authorize with admin                    
#        reverse_proxy http://127.0.0.1:8787     
#        import cloudflare
#    } 
#} 

#prowlarr.website.com {       
#    route /prowlarr* {                              
#        authorize with admin                    
#        reverse_proxy http://127.0.0.1:9696     
#        import cloudflare
#    } 
#} 

#mylar.website.com {       
#    route /mylar* {                              
#        authorize with admin                    
#        reverse_proxy http://127.0.0.1:8090     
#        import cloudflare
#    } 
#} 

#requests.website.com {       
#    route /overseerr* {                              
#        authorize with admin                    
#        reverse_proxy http://127.0.0.1:5055     
#        import cloudflare
#    } 
#} 

#cockpit.website.com {       
#    route /cockpit* {                              
#        authorize with admin                    
#        reverse_proxy http://127.0.0.1:9090     
#        import cloudflare
#    } 
#} 

#syncthing.website.com {
#    route /syncthing* {      
#        authorize with admin                    
#        reverse_proxy http://10.0.0.9:8384     
#        import cloudflare
#    } 
#}

#zm.website.com {       
#    route /zm* {                              
#        authorize with admin                    
#        reverse_proxy http://10.0.0.8/zm     
#        import cloudflare
#    } 
#} 

requests.website.com {
    #route /overseerr*
    #redir / /requests
    reverse_proxy http://127.0.0.1:5055
    import cloudflare
}

comics.website.com {
    reverse_proxy http://127.0.0.1:8616
    import cloudflare
}

# Refer to the Caddy docs for more information:
# https://caddyserver.com/docs/caddyfile
```

**Version Information**

Provide output of `caddy list-modules -versions | grep git` below:

```
dns.providers.cloudflare v0.0.0-20210607183747-91cf700356a1
http.authentication.providers.authorizer v1.1.15
http.handlers.authenticator v1.1.15
security v1.1.15

  Non-standard modules: 4
```

**Expected behavior**

To enable security authorization as described in Caddyfile

**Additional context**

The authorization section was copied directly from https://docs.organizr.app/features/server-authentication/caddy-server-authentication

**Comment by greenpau** [comment]
@whatgoesbump , what happens when you add “authorize” directive?

website.com {
    authorize with user
    root * /var/www/websites/organizr        
    php_fastcgi unix//run/php/php8.1-fpm.sock  
    rewrite /api/v2/* /api/v2/index.php?{query}
    file_server
}

**Comment by whatgoesbump** [comment]
> 

Sorry, this is the first post like this, I thought I included that.

I always get ` run: adapting config using caddyfile: /etc/caddy/Caddyfile:78: unrecognized directive: authorization`

when I run this other config I found 

`{
    order authenticate before respond
    order authorize before basicauth

    security {
        authorization policy organizrpolicy {
            set auth url "https://server.mydomain.com/auth"'
            crypto key verify <ORGANIZR_HASH_TOKEN>
            crypto key token name organizr_token_<ORGANIZR_UUID>
            set token sources cookie header query
            validate bearer header

             acl rule {
                 comment allow admins only
                  match iss Organizr
                  match role Admin
                  allow stop log info
            }
             acl rule {
                  comment default deny
                  match iss any
                  deny log warn
            }
        }
    }
}


*.mydomain.com {
    tls {
        dns cloudflare <CLOUDFLARE_KEY>
    }

    @server host server.mydomain.com
	handle @server {
        reverse_proxy organizr:80
    }

    @tv host tv.mydomain.com
	handle @tv {
        authorize with organizrpolicy
        reverse_proxy sonarr:8989
    }
}'

I get 
`run: adapting config using caddyfile: server block without any key is global configuration, and if used, it must be first` 
which sounds more promising but I don't really know what that means

**Comment by whatgoesbump** [comment]
Ok, update I think it's "technically working, but I'm getting `run: loading initial config: loading new config: starting caddy administration endpoint: listen tcp 127.0.0.1:2019: bind: address already in use`

**Comment by greenpau** [comment]
@whatgoesbump , try removing “order authenticate before respond” and adding “admin off” in its place.

**Comment by whatgoesbump** [comment]
> @whatgoesbump , try removing “order authenticate before respond” and adding “admin off” in its place.

Ok, what does that do? because it seems to be working as is...?

**Comment by greenpau** [comment]
@whatgoesbump , did you review this doc? https://docs.organizr.app/features/server-authentication/caddy-server-authentication

**Comment by whatgoesbump** [comment]
> @whatgoesbump , did you review this doc? https://docs.organizr.app/features/server-authentication/caddy-server-authentication

Yes that was the first thing I did. That code doesn't work at all. Had to go with the mods I found. But now the problem is that while the site works for me, it doesn't load iframes in mobile or on any browser aside from Firefox... So the site doesn't really work.

**Comment by greenpau** [comment]
@whatgoesbump , the iframes issue is not related to this plugin. You need to ask these questions at caddy.community

**Comment by whatgoesbump** [comment]
@greenpau Yeah I've kinda given up on them
