### ISSUE TITLE
question: text instructions for install

### ISSUE THREAD

**Issue by unusualevent** [greenpau/caddy-security#166]
Are there text instructions for installing this? not a video?

Can those instructions be linked to in the readme, and the documentation?

**Comment by bbrendon** [comment]
@unusualevent  I'm still trying to figure out how to install it. Where is the video?

**Comment by bbrendon** [comment]
NM. Figured out how to install it...

Dockerfile:
```
FROM caddy:2-builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/greenpau/caddy-security
    #--with github.com/caddyserver/nginx-adapter \
    #--with github.com/hairyhenderson/caddy-teapot-module@v0.0.3-0

FROM caddy:2

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

**Comment by unusualevent** [comment]
@greenpau did you add this to the docs?

**Comment by greenpau** [comment]
> did you add this to the docs?

@unusualevent , did not get to it. PRs are welcome in https://github.com/authp/authp.github.io/tree/main/docs
