### ISSUE TITLE
question: Keycloak upgrade from 14 to 20

### ISSUE THREAD

**Issue by axi92** [greenpau/caddy-security#177]
We upgraded from keycloak 14 to 19 and I have some difficulties to set the settings again according to the [docs](https://authp.github.io/docs/authenticate/oauth/backend-oauth2-0011-keycloak#realm) because the UI changed a little bit and some things are named different.

Caddy gives me that message:
`2022/10/28 07:58:35.075 WARN    security        Authentication failed   {"session_id": "isMv0V4WAjUuOH52OtCEhVvBttw7cbSLDeLd", "request_id": "683ec5d1-b9f0-4361-acd4-fa6b6fc2f773", "error": "failed fetching OAuth 2.0 access token: failed obtaining OAuth 2.0 access token, error: invalid_request, description: \"can not get encryption KEK\""}`

While keycloak logs this:
```
2022-10-28 07:58:35,060 WARN  [org.keycloak.keys.loader.ClientPublicKeyLoader] (executor-thread-79) Unable to retrieve publicKey of client 'caddy-security-portal' for the specified purpose other than verifying signature
2022-10-28 07:58:35,060 WARN  [org.keycloak.keys.infinispan.InfinispanPublicKeyStorageProvider] (executor-thread-79) PublicKey wasn't found in the storage. Requested kid: 'null' . Available kids: '[]'
```

And on the Web UI I get unauthorized.

Client settings:
![image](https://user-images.githubusercontent.com/1394837/198548956-c50f9ee0-9c3f-4d1e-998f-04871bf8cd8e.png)

Is it the right one that I selected Client ID and secret as the client authenticator?
![image](https://user-images.githubusercontent.com/1394837/198545175-e51b7948-f8e7-4f2a-b533-aab0bb04f1ba.png)

Those are the advanced settings:
![image](https://user-images.githubusercontent.com/1394837/198547597-3f31b063-5108-4a75-b288-20be1ade094f.png)

I have already set up an empty keycloak instance if you need to login and see the settings for yourself? Credentials are the same as in the last email from some months ago.

**Comment by axi92** [comment]
I opened a ticket at keycloak, for me it looks like keycloak cant find the public keys that caddy-security is requesting. Although its there https://keycloak/realms/master/protocol/openid-connect/certs

**Comment by axi92** [comment]
This was the right configuration:
![image](https://user-images.githubusercontent.com/1394837/200008065-055701df-9629-486f-93b6-8a6d6a63294d.png)

**Comment by greenpau** [comment]
@axi92 , glad it worked! Please consider documenting step by step on how you did it in here https://github.com/authp/authp.github.io/tree/main/docs/authenticate/oauth 

The file name should be `81-backend-oauth2-0011-keycloak-v2.md`

**Comment by omario36** [comment]
Hi @axi92 can you share with us an extraction of your client ? I have the same config as you have mentioned before but I have an error 
`{"level":"debug","ts":1670518067.2857337,"logger":"security","msg":"failed fetching OAuth 2.0 access token from the authorization server","session_id":"Sq7UpJCVjFNCWODbA6E8evVj8FmMWxneDhraIg","request_id":"43e0aefb-0edd-457b-8273-74368faa52a9","error":"authorization server response has no \"id_token\" field"}`

If you can describe what you have in  Client scopes tab ...
![image](https://user-images.githubusercontent.com/10621369/206514008-720f9c56-4644-46e3-9605-059f1e0d0fdd.png)

Thanks a lot
