### ISSUE TITLE
question: Default deny for user transforms

### ISSUE THREAD

**Issue by sandstormkeshav** [greenpau/caddy-security#182]
> A clear and concise description of what you want to accomplish.

I would like to prevent issuance of a token if users are not whitelisted when using the google oauth provider. 
```
transform user {
                                match realm google
                                match email myemail@email.com
                                action add role authp/admin
                        }
                        transform user {
# not sure what match condition to include here
                                block
                        }
```
Essentially is there a way to do a catch all where if the email is not specified in the first transform it'll be blocked by the catch all rule

**Comment by greenpau** [comment]
@sandstormkeshav , try this:

```
                        transform user {
                               no match email myemail@email.com
                                block
                        }
```

**Comment by sandstormkeshav** [comment]
@greenpau That works, thank you! The only con I can think of would be that I need to update the emails in both blocks when I make any changes but that's alright!

**Comment by sandstormkeshav** [comment]
This is a very old issue but I was wondering how this could be done if there was multiple users. Creating multiple blocks won't work because they are evaluated sequentially. Thank you!
