### ISSUE TITLE
question: Serving Authentication portal from non root uri

### ISSUE THREAD

**Issue by ahmedwonolo** [greenpau/caddy-security#187]
Is it possible to serve authentication portal from lets say `/oauth2` uri instead of `/`?
I'm using google IDP if that makes a difference.
I have `set auth url /oauth2/google` set under `authorization policy`, so I expect things like generic logo to be served from `/oauth2/assets/images/logo.svg` while it it fetch from `/assets/images/logo.svg`.

**Comment by ahmedwonolo** [comment]
![image](https://user-images.githubusercontent.com/102168038/202029532-db397bf7-f744-4dd4-ad65-3226412398a9.png)

**Comment by ahmedwonolo** [comment]
I above screenshot, for some reason auth code flow doesn't randomly and that's how I got to this page.

**Comment by greenpau** [comment]
@ahmedwonolo , please share your config.

**Comment by greenpau** [comment]
@ahmedwonolo , please use “/auth*” instead of “/oauth2*”

route /auth* {
    authenticate with authz_proxy_portal
  }

**Comment by ahmedsajid** [comment]
I'm basically protecting a part of an app endpoint protected with oauth2. I don't want to intercept `/auth*`.

Is it possible to use `/oauth2*` instead? Configuration open that allows it?

**Comment by ahmedsajid** [comment]
I used [this](https://github.com/authp/authp.github.io/blob/86726777e147b298cb653d1303e243e700f37573/assets/conf/oauth/authproxy/Caddyfile#L28)  example which you provided in earlier issue.
I just dropped `authzproxy` part.

**Comment by ahmedwonolo** [comment]
looks like using [this](https://github.com/authp/authp.github.io/blob/main/assets/conf/oauth/authproxy/Caddyfile#L28) example as is and NOT ignore `authzproxy` part things work fine.

**Comment by ahmedwonolo** [comment]
Thank you very much for all your help!!!!

**Comment by greenpau** [comment]
@ahmedwonolo , I am looking to add testimonial sections to https://authcrunch.com. Could you please write one and send it to me at greenpau@outlook.com?
