### ISSUE TITLE
question: warn OAuth 2.0 authorization state not found

### ISSUE THREAD

**Issue by ahmedwonolo** [greenpau/caddy-security#188]
When running more than 1 instance causes `OAuth 2.0 authorization state not found` error.
Am I missing something here?
Config here https://github.com/greenpau/caddy-security/issues/187#issuecomment-1316227053

**Comment by greenpau** [comment]
@ahmedwonolo , you need to implement something that would keep a client connected to the same instance, e.g. cookie persistence.

Auth portal does not share state between its instances.
