### ISSUE TITLE
question: Keycloak JWT_TOKEN

### ISSUE THREAD

**Issue by support-tt** [greenpau/caddy-security#189]
> I want to use caddy with keycloak to protect some sites with the keycloak login 

Im very new to caddy switched from traefik today. 
I want to protect some sites with my keycloak. I used the template from the github and the caddy portal site works.

When I klick on login the redirect to keycloak also works. After I login I get "Unauthorized" from caddy portal.
On the keycloak admin site under logs I see login successful.

In the caddy logs there is a error message:
`
{"level":"debug","ts":1669059961.1780937,"logger":"security","msg":"failed fetching OAuth 2.0 access token from the authorization server","session_id":"XXX","request_id":"XXX","error":"failed obtaining OAuth 2.0 access token, error: unknown_error"}
{"level":"warn","ts":1669059961.178116,"logger":"security","msg":"Authentication failed","session_id":"XXX","request_id":"XXX","error":"failed fetching OAuth 2.0 access token: failed obtaining OAuth 2.0 access token, error: unknown_error"}
`
I use Keycloak 19 and the newest version of caddy.
Because im not familiar with JWK I think there is a issue:
What do I need to insert for the parameters?:
  crypto key sign-verify 
and
  crypto key verify

I tried a lot but doenst find a solution. 

Greetings David

**Comment by greenpau** [comment]
@support-tt , please see the following links:

- https://authp.github.io/docs/authenticate/oauth/backend-oauth2-0011-keycloak
- https://github.com/greenpau/caddy-security/issues?q=is%3Aissue+label%3Aoauth-keycloak+is%3Aclosed
- https://github.com/authp/authp.github.io/tree/main/assets/conf/oauth/keycloak

**Comment by support-tt** [comment]
sorry saw the post where Shared key has nothing to do with keycloak.

So my problem comes from elsewhere

**Comment by support-tt** [comment]
@greenpau 
I checked all functions now again and enabled "Authorization" in Keycloak. 
Afterwards Keycloak regenerated the jwk key. Now I get the error:
`
Error: loading initial config: loading new config: loading security app module: provision security: server initialization failed: failed configuring identity provider: failed to fetch jwt keys for OAuth 2.0 authorization server: invalid jwks key: jwks unsupported key algorithm RSA-OAEP-256 for XXX
`
The problem is I can only choose between 
![image](https://user-images.githubusercontent.com/61587422/203153728-1581ca06-b1cd-467a-aadc-479cacc273e9.png)

and all 3 algorithm produce the same error that they are not supported..

**Comment by greenpau** [comment]
@support-tt , if you need my help, then i need you to set me up with a test instance and sponsor $1K.

**Comment by support-tt** [comment]
Y I will search a little more. At the moment this is only a internal test setup so I will not get the money but I totally understand that you cant fix this for free via github issue but thanks for your help.

**Comment by greenpau** [comment]
> Y I will search a little more. At the moment this is only a internal test setup so I will not get the money but I totally understand that you cant fix this for free via github issue but thanks for your help.

@support-tt , i have little time nowadays and I want to make sure that the person asking for help is "invested", so the 1K serves as a gatekeeper of sorts.

**Comment by greenpau** [comment]
@support-tt , one thing you should try is checking keycloak docs and seeing if it is possible to enable “supported” protocols.
