### ISSUE TITLE
question: map login for NTLM backend 

### ISSUE THREAD

**Issue by graphik55** [greenpau/caddy-security#194]
I have a backend application which is only possible to do NTLM Auth. This makes user manage difficult, for example you have to access the windows server to change passwords.

My current idea is to use Caddy as a reverse proxy with the security feature to provide a better authentication like OIDC and map the successful authenticated user to a NTLM login which will be done automatically by caddy as middleware.

Is such a mapping and automatic login possible using the security feature?

I know it is really special but I am curious.

**Comment by greenpau** [comment]
> Is such a mapping and automatic login possible using the security feature?

@graphik55 , once you are authenticated with auth portal, the portal sets Caddy’s internal user id. You potentially map it to middleware.

you can set user id to username or email https://authp.github.io/docs/authorize/identity

**Comment by graphik55** [comment]
@greenpau thank you for this information.

I guess this could be all I needed :)

**Comment by greenpau** [comment]
@graphik55 , I am looking to add testimonial sections to https://authcrunch.com. Could you please write one and send it to me at greenpau@outlook.com?
