### ISSUE TITLE
How to install this plugin?

### ISSUE THREAD

**Issue by svenskanda** [greenpau/caddy-security#201]
> A clear and concise description of what you want to accomplish.

Really - On the website and here at Github you will not find anywhere how to install the plugin or integrate it accordingly. Any basis for using the plugin at all is not given. Why? How do I integrate this plugin into Caddy?

**Comment by greenpau** [comment]
@svenskanda , like any other plugins, you can use Caddy Download page. There select the plugins you would like to use and click download.

Then, review docs and configuration examples mentioned below

* Documentation: [authp.github.io](https://authp.github.io/)

* Configuration Examples: [here](https://github.com/authp/authp.github.io/tree/main/assets/conf)

there are also some videos on youtube

**Comment by svenskanda** [comment]
Thanks for your feedback. I think if caddy status for plugins like Apache, then I come back to your plugin. But I will not download the build of caddy with your plugin and then every time, I must build a new caddy. I need the comfort of shell with apt etc... or do you know how I can download caddy with your plugin for Debian like caddy's normal solution?

**Comment by svenskanda** [comment]
https://caddyserver.com/docs/install

**Comment by greenpau** [comment]
@svenskanda , get comfortable with caddy first. Building caddy with xcaddy is a way to go.

**Comment by greenpau** [comment]
@svenskanda , if you are using non-standard plugins, like this one, then you have to build it.

**Comment by svenskanda** [comment]
What is with the caddy cli function: caddy add-package github/...../caddy-security?

**Comment by greenpau** [comment]
> What is with the caddy cli function: caddy add-package github/...../caddy-security?

never used it myself. Try it out.

**Comment by greenpau** [comment]
Behind the scenes it uses xcaddy to build the updated binary.
