### ISSUE TITLE
question: Basic Caddyfile to get started

### ISSUE THREAD

**Issue by philipkukoba** [greenpau/caddy-security#202]
I would like to configure the Caddyfile to expose the caddy-security auth portal. I would like to use caddy-security to enable MFA for all my websites running on my server. Can this be done in the auth portal GUI? 

What's the minimal Caddyfile that I need to get started?

My current Caddyfile only does reverse proxies for my servers: 

```
subdomain1.domain.org {
   reverse_proxy container1:1234
}

subdomain2.domain.org {
   reverse_proxy container2:1234
}
```

My docker-compose:

![image](https://user-images.githubusercontent.com/99122730/213263060-6902ba01-d6d8-40eb-bc82-88c846b172ff.png)

**Comment by Hoempi** [comment]
Yes, that is certainly doable. Actually I have MFA setup for my portal, but not yet set as mandatory as right now I am still the only user.

But it is possible to require it, see https://authp.github.io/docs/authenticate/mfa
