### ISSUE TITLE
Is it possible to have transparent basic auth?

### ISSUE THREAD

**Issue by MartinWallgren** [greenpau/caddy-security#204]
I have configured an ldap store and it works well with the login form in the portal and I can login with basic auth using the basic endpoint.

My question is: is it possible to configure caddy-security to accept basic auth headers from the initial/main request, so the user don't have to do the initial login request first?

Basically, if there is no valid token, see if there is any basic auth header and use that to generate a token and then continue the request.

**Comment by greenpau** [comment]
@MartinWallgren , please see if this helps https://authp.github.io/docs/authenticate/misc#basic-authentication

Set the auth URL to basic auth in your authorization policy.

**Comment by MartinWallgren** [comment]
Thank you, that didn't even cross my mind.
But won't this break the login if no basic auth header exists in the request?
If there is no basic auth header, I want to land on the login portal to be able to provide other forms of auth.
I want to add additional login provides (azure). Supporting basic this way is mainly for legacy reasons. I don't want to break existing api clients, while at the same time provide single sign on via azure for web browser users.

I'll experiment with your idea tomorrow. Can I have different auth urls for different routes?

**Comment by MartinWallgren** [comment]
Sorry for the late response. I got distracted by unplanned work but I was finally able to test your suggestion.

I created a separate policy with auth url as below.

`set auth url https://not.my.domain.com/auth/basic/login/ldap`

And I created a separate route for /api/* using this policy.
As long as I use the browser (chrome, firefox) everything works great. When I go to the main page I'm redirected to the auth portal (with multiple auth variants to click).
If I go directly to `/api/some/resource` I get the basic auth dialog from the browser, and when I enter my credentials I'm redirected to the api resource.

However, when I try to do the same with curl I'm redirected to the auth portal instead of the api resource I tried to request.

```sh
❯ curl -L -umartin https://not.my.domain.com/api/v2/atoms
Enter host password for user 'martin':
<!DOCTYPE html>
<html lang="en" class="h-full bg-blue-100">
  <head>
    <title>Authentication Portal - Sign In</title>
    <!-- Required meta tags -->
```

Any idea why this happens?

**Comment by greenpau** [comment]
@MartinWallgren , please pass application/json header in your request.

**Comment by MartinWallgren** [comment]
I couldn't get this to work (tried various ways), but I wont pursue it further.
We (and our clients) will accept a change in how to authenticate towards our api (basically following the suggestion from the basic auth documentation from this project).

Thank you for the great input. I'm ok with closing this.
