### ISSUE TITLE
feature: add shortcut and docs for oauth keycloak integration

### ISSUE THREAD

**Issue by greenpau** [greenpau/caddy-security#21]
> A clear and concise description of what you want the system to do.

> A clear and concise description of what you want the system to do.

1. Create a shortcut for `keyclock` (similar to https://authp.github.io/docs/authenticate/misc#shortcuts)
2. Document the integration in under https://github.com/authp/authp.github.io/tree/main/docs/authenticate/oauth

```
        generic_oauth2_backend {
          method oauth2
          realm generic
          provider generic
          client_id <id>
          client_secret <secret>
          scopes openid email profile
          base_auth_url https://<keycloak-url>
          metadata_url https://<keycloak-metadata-url>
        }
```

to:

```
keycloak <keycloak-url>
```

See https://github.com/greenpau/caddy-auth-portal/issues/215

**Comment by axi92** [comment]
Is keycloak working right now with this? I was not able to find anything. We use keycloak with our own apps to authenticate and authorize.

**Comment by greenpau** [comment]
@axi92 , it works. i just don’t have access to keycloak console to take screenshots.

**Comment by axi92** [comment]
I could provide you a fresh instance? Would that help? I can just spin one up on my vps and give you the credentials, when you are done I delete it =)

**Comment by greenpau** [comment]
> I could provide you a fresh instance? Would that help? I can just spin one up on my vps and give you the credentials, when you are done I delete it =)

@axi92 , yes. That works 😄 Please email me at greenpau at outlook.com

**Comment by axi92** [comment]
@greenpau you got mail =)

**Comment by greenpau** [comment]
@axi92 , thank you for your help! It is now done. https://authp.github.io/docs/authenticate/oauth/backend-oauth2-0011-keycloak

**Comment by greenpau** [comment]
My config:

```
        oauth identity provider keycloak {
            driver generic
            realm keycloak
            client_id {env.KEYCLOAK_CLIENT_ID}
            client_secret {env.KEYCLOAK_CLIENT_SECRET}
            scopes openid email profile
            metadata_url https://keycloak.axi92.at/auth/realms/master/.well-known/openid-configuration
        }
```

**Comment by axi92** [comment]
I try to follow your documentation.

We have right now an older version of keycloak (14.0.0) so the behavior may be different.

1. If I disable all providers except the rsa-generated. When I disable the mac-* i get logged out and when I login again there is a new mac fallback provider with priority -100. Maybe the version that we use in production is having this feature and it was removed in an update. We need to schedule an admin day to upgrade keycloak.

2. https://github.com/authp/authp.github.io/blob/main/assets/conf/oauth/keycloak/Caddyfile#L39 in here there is an JWT_SHARED_KEY where can I find this in my keycloak instance?

**Comment by greenpau** [comment]
@axi92 that environment variable should be set to what you want. It has nothing to do with keycloak. Rather it is the shared key for encryption of the tokens issued by auth portal.

https://github.com/authp/authp.github.io/blob/main/assets/conf/oauth/cognito/caddy.env

**Comment by greenpau** [comment]
> If I disable all providers except the rsa-generated. When I disable the mac-* i get logged out and when I login again there is a new mac fallback provider with priority -100

you actually don’t have to delete all of them. It was just easier for me to get it working with RSA. The realm configuration was the hardest to figure out.

now, please make sure that you review my screenshot with your setup, especially advanced opeid config.
