### ISSUE TITLE
question: Setting a singular, automatic SSO login for Azure

### ISSUE THREAD

**Issue by maemigh** [greenpau/caddy-security#211]
Is there a simple/recommended way to make the Azure login automatic? Currently the login page shows up and then one must click on the Azure button to be redirected to the Azure login page.

I'd like to my setup to only allow Azure logins, so I would like to skip that step of needing to click the button.

**Comment by phidevz** [comment]
Hello @maemigh ! I do not know if that solves your problem, but have you had a look at https://authp.github.io/docs/apps/sso_saml ? This page explains how SSO works with SAML, and Azure also supports SAML. So maybe that may help? Let me know!

**Comment by greenpau** [comment]
@maemigh , the are couple of ways to do it.
1. Set your auth url to the azure endpoint (within portal)
2. Use javascript injection to redirect to azure endpoint https://authp.github.io/docs/authenticate/ui-features#javascript

**Comment by maemigh** [comment]
Thanks. Got this working with option 1.
