### ISSUE TITLE
caddy-secruity build fails through caddyserver.com's custom build service

### ISSUE THREAD

**Issue by linust** [greenpau/caddy-security#216]
**Describe the issue**

Custom Build through caddy build service fails if adding caddy-security (latest version). 

**Configuration**

(https://caddyserver.com/download?package=github.com%2Fgreenpau%2Fcaddy-auth-jwt&package=github.com%2Fgreenpau%2Fcaddy-auth-portal&package=github.com%2Fgreenpau%2Fcaddy-authorize&package=github.com%2Fgreenpau%2Fcaddy-security)

**Version Information**

latest

**Expected behavior**

Caddy complies with caddy-security module and download is initiatied.

**Additional context**

Granted the build service is not part of caddy-security but:
Since the same build service works for other non standard packages and consistently fails if adding caddy-security it seems to be caddy-security specific.

**Comment by linust** [comment]
FWIW the last time i build caddy-security in 2022-08-19 it worked.

**Comment by kiwiz** [comment]
FWIW, the download seems to be working now.
