### ISSUE TITLE
question: Deny default 

### ISSUE THREAD

**Issue by CruzMarcio** [greenpau/caddy-security#223]
I want to set two groups of users and deny by default all the rest. Currently I am doing it like this, is there a better way of not having to list the emails twice?

```
                        transform user {
                                match email email1@test.com email2@test.com email3@test.com
                                action add role authp/user
                        }
                        transform user {
                                match email email4@test.com
                                action add role authp/admin
                        }
                        transform user {
                                no match email email1@test.com email2@test.com email3@test.com email4@test.com
                                block
                        }
```

**Comment by greenpau** [comment]
> Currently I am doing it like this, is there a better way of not having to list the emails twice?

@CruzMarcio , are the users from the same domain?

**Comment by CruzMarcio** [comment]
> > Currently I am doing it like this, is there a better way of not having to list the emails twice?
> 
> @CruzMarcio , are the users from the same domain?

No, different domains. I should have made a better example, but they are all different domains.

**Comment by greenpau** [comment]
@CruzMarcio , what is the purpose of “no match email” and block? Are you trying to explicitly block certain users? or it is your way of saying don’t allow anyone else?

if it is the later, then match on the previously granted role, i.e. no match role authp/admin authp/user. Then, block.

**Comment by CruzMarcio** [comment]
> @CruzMarcio , what is the purpose of “no match email” and block? Are you trying to explicitly block certain users? or it is your way of saying don’t allow anyone else?
> 
> if it is the later, then match on the previously granted role, i.e. no match role authp/admin authp/user. Then, block.

Do the transforms work in order? What I noticed is that if I do it like your suggestion, I still can acess the whoami endpoint and I see the the user has the authp/guest role. I also tried doing match role authp/guest and block but it didn't work.

**Comment by greenpau** [comment]
@CruzMarcio , wait :-) match role authp/guest and block :-)

**Comment by greenpau** [comment]
> Do the transforms work in order?

i think yes. The issue might be the difference between match any and match all. You will need to experiment and read the docs https://authp.github.io/docs/authorize/acl-rbac#granting-access-with-access-lists
