### ISSUE TITLE
question: Login and Password on the same Sign-In page

### ISSUE THREAD

**Issue by cfe84** [greenpau/caddy-security#231]
> A clear and concise description of what you want to accomplish.

Hello there, awesome plugin!

Is there a way to bring both login and password fields on the local Sign-In page? I don't like having both on separate pages as I can't get a quick password-manager fill. I've been looking at the templates but I don't see how to do that

![image](https://user-images.githubusercontent.com/6646258/234634631-29942014-5d5f-45b7-9667-6ea93bf6683f.png)

**Comment by ooiuri** [comment]
Hello everyone, i'm looking forward to discover a solution to this question too!

@greenpau is there a way to post on the sandbox endpoint the username and password and get the authentication without needing the sandbox_id?
(i'm using local auth)

**Comment by greenpau** [comment]
@ooiuri , not at the moment. This is related to authentication sandbox process. There is no way to merge the two.
