### ISSUE TITLE
feature: Accept secrets passed via files (for docker compose)

### ISSUE THREAD

**Issue by lukeyeager** [greenpau/caddy-security#253]
Others also asked for this a few months ago: https://caddy.community/t/how-can-i-use-docker-secrets-with-caddy-containers/15279

Currently, secrets must be provided via environment variables. I want to use docker-compose to manage my caddy service, and I want to use their recommended approach to secrets - files instead of environment variables:

>Docker Compose provides a way for you to use secrets without having to use environment variables to store information. If you’re injecting passwords and API keys as environment variables, you risk unintentional information exposure. Environment variables are often available to all processes, and it can be difficult to track access. They can also be printed in logs when debugging errors without your knowledge. Using secrets mitigates these risks.
> https://docs.docker.com/compose/use-secrets/

Many services such as [Grafana](https://grafana.com/docs/grafana/v10.0/setup-grafana/configure-grafana/#file-provider), [splunk-docker](https://github.com/splunk/splunk-ansible/commit/5f196b934db8c29def81193cbf900e046e276f0d), [Alertmanager](https://prometheus.io/docs/alerting/0.25/configuration/#http_config), and more do support passing secrets through files. These are easy to integrate with docker compose.

> What are the Caddyfile directives that need to be added.

This would be a lot of new directives. For one example, you could add `client_secret_file` as a sibling to `client_secret` [here](https://github.com/greenpau/caddy-security/blob/v1.1.19/caddyfile_identity_provider.go#L38). For a full list,  you could just run `git grep --fixed-strings env.` in https://github.com/authp/authp.github.io to find all configuration locations which you usually recommend not to check in to git directly.

**Comment by greenpau** [comment]
@lukeyeager , did you check whether caddy has some way to read a file and pass it to a config? That would be a preferred way to deal with it.

**Comment by lukeyeager** [comment]
Thanks for pointing me in the right direction. I think `caddy start --envfile` does everything I need!
https://caddyserver.com/docs/command-line#caddy-run
