### ISSUE TITLE
question: What is the purpose of the SSH & GPG keys, and the Connected Accounts areas in settings

### ISSUE THREAD

**Issue by jinnko** [greenpau/caddy-security#260]
Having published both SSH and GPG keys to my localdb I can't see how these can be used.  There's no mention in the docs and I couldn't find much in the code.

Can you give some examples of how these can be used please?

I also can't see how an account can be connected into the Connected Accounts area.

**Comment by greenpau** [comment]
@jinnko, I use them in my projects. For example, compile a list of public SSH keys for server access. GPG keys are used for the encryption of files sent between users. These capabilities are not a part of the portal, but they are there for that reason.

**Comment by jinnko** [comment]
@greenpau - one more question: is there an endpoint that exposes these keys publicly or privately, particularly the SSH keys?  (I'm already using [GnuPG WKD](https://wiki.gnupg.org/WKD) for GPG)?

**Comment by greenpau** [comment]
@jinnko ,  there is no endpoint at the moment. It probably deserves one.

The reason it is not there is that I can read from db file itself.

my plans include adding different database types backed by cloud based KV services, e.g. dynamodb, etcd, etc

**Comment by greenpau** [comment]
I already started the process, but my work life made it difficult to contribute

https://github.com/greenpau/go-authcrunch-ids-dynamodb

**Comment by jinnko** [comment]
> I already started the process, but my work life made it difficult to contribute
> 
> https://github.com/greenpau/go-authcrunch-ids-dynamodb

Cool - I know the feeling.

I'll try to make some time myself to raise a PR against the docs to include the info shared in this issue.

> there is no endpoint at the moment. It probably deserves one.

Have you considered an implementation to expose SSH keys similar to Github/Gitlab?  For example SSH keys are exposed publicly at github.com/username.keys and similarly on gitlab.com/username.keys.  If you follow the pattern you could expose the user keys on the authentication host.

For GPG the WKD standard has been good enough for me so I don't have another suggestion there.

Just some ideas.

Thanks for answering my questions and thanks for putting together this awesome project!
