### ISSUE TITLE
question: Conditional redirect to OIDC provider login page based on IP together with OIDC-enabled web app

### ISSUE THREAD

**Issue by nicolazilio** [greenpau/caddy-security#284]
Hi,

I would to use Caddy and Caddy-Security for the following use case:

1. I have a Django app that already uses OIDC internally for authentication, let's say at www.myapp.com, its OIDC callback redirect URL is www.myapp.com/oidc/callback/
2. I already used Caddy as the webserver for the app, and block any external IP from accessing it

```
www.myapp.com {

    # Block external access
    @external {
     not remote_ip [LIST OF IPs]
    }
    respond @external 403

    # Static files
    handle_path /static/* {
        file_server {
            root /home/myapp/staticfiles
        }
    }

    # Reverse proxy
    reverse_proxy 127.0.0.1:9090 
}
```
3. What I would like to do is to allow external IP addresses to access the app but, before they can do so, they would need to authenticate themselves with the same OIDC that the app uses. If the authentication is successful, they would be automatically redirected to the app. Internal IP addresses would not need this extra layer of protection.

![image](https://github.com/greenpau/caddy-security/assets/2800360/ac268142-98f9-451d-a06b-62cdd52bf1a6)

I know there is a generic OIDC configuration at https://github.com/authp/authp.github.io/blob/main/assets/conf/oauth/generic/Caddyfile but I must admit I don't even know where to start. Would you have some pointers? 

Some additional questions:
1. would I need to set up and additional callback URL for Caddy with my OIDC provider?
2. How can I make the redirection to my OIDC provider conditional on an IP address?
3. What is exactly the `base_auth_url`?

Thank you very much in advance.

**Comment by rootbeerdan** [comment]
You should never "allow" something just because it comes from a certain IP address or subnet, IP addresses are never to be trusted because of how easily they can be spoofed.

**Comment by nicolazilio** [comment]
Ok, but that is only one part of the problem, which would be nonetheless interesting to know whether it is at all possible, at least theoretically. I would be fine if all traffic would have to be authenticated/authorized by the OIDC provider before it can access the web app. The main question remains as to whether I would need to have two callback URLs, one for Caddy and one for Django. And if so, how can the OIDC provider know when to use one and the other? And how would Caddy need to be configured for that?

**Comment by greenpau** [comment]
@nicolazilio , Django would not work with OIDC in this scenario. Once you have authenticated, the JWT token you are carrying is the caddy-security token.

**Comment by nicolazilio** [comment]
@greenpau, yes, that makes sense, but of course one could just (re)authenticate with the Django app once it got past Caddy. My ultimate aim is not to have the app exposed directly to the world.
