### ISSUE TITLE
question: use authp as upstream oauth server / authorization endpoint?

### ISSUE THREAD

**Issue by unusualevent** [greenpau/caddy-security#287]
> Can you use authp as the upstream IdP / authorization endpoint for other services that support oauth/saml?

e.g., If I use [local authorization](https://authp.github.io/docs/authenticate/local/local), can I configure another server to use this as the SSO?

I say that because the plugin, registration, and setup is so amazing compared to every other IdP server.

**Comment by greenpau** [comment]
@unusualevent , not at the moment. There was an issue related to the same, i.e. making the portal an IDP server. I will make it happen at some point.
