### ISSUE TITLE
question: How to set the portal URL?

### ISSUE THREAD

**Issue by xtractalpha** [greenpau/caddy-security#288]
I couldn't locate the information – can the URL of the portal be changed? If so, how is this done?

Thank you!

Here is what I am aiming to establish:

**Goal:**
For Login:
login.xxx.com

And for the Portal:
portal.xxx.com

Current situation:
Portal:
login.xxx.com/portal

**Comment by greenpau** [comment]
@xtractalpha , I think this could be done by rewriting path, e.g. match `login.xxx.com/portal` and redirect to `portal.xxx.com`.
In the `portal.xxx.com`, validate authenticated and then append `/portal` to path. 

The above is Caddy's magic. There is nothing you need to do with the plugin configuration.
