### ISSUE TITLE
question: ACL in Caddy

### ISSUE THREAD

**Issue by jayadevx** [greenpau/caddy-security#301]
Hello there,

1/ Is there a way to create ACL in Caddy?
like 
allow {condition} /images
deny {condition} /private

2/ Can we do this via API dymamically?

Best,
Jay

**Comment by greenpau** [comment]
> 1/ Is there a way to create ACL in Caddy?

@jayadevx , generally speaking it is done using a combination of request matchers and handle directive.

* https://caddyserver.com/docs/caddyfile/matchers
* https://caddyserver.com/docs/caddyfile/directives/handle

> 2/ Can we do this via API dymamically?

No.

**Comment by greenpau** [comment]
@jayadevx , here it is https://github.com/greenpau/caddy-security/issues/181#issuecomment-1516544684

**Comment by greenpau** [comment]
@jayadevx , in your case it might be

```
test.example.com {
	@images {
	        path /images
	}
	handle @images{
                authorize with imagepolicy
	        reverse_proxy destination:80
	}
	handle {
	        authorize with adminpolicy
	        reverse_proxy destination:80
	}
}
```

**Comment by jayadevx** [comment]
Thank you @greenpau

**Comment by greenpau** [comment]
@jayadevx, I am looking to add testimonial sections to https://authcrunch.com. Could you please write one and send it to me at greenpau@outlook.com?

**Comment by jayadevx** [comment]
I donno if I have used authcrunch.com. is it same as caddy?

**Comment by greenpau** [comment]
> I donno if I have used authcrunch.com. is it same as caddy?

@jayadevx , it is what powers `caddy-security`.

**Comment by jayadevx** [comment]
Ok! Can you give some sample testimonial?

**Comment by greenpau** [comment]
> Ok! Can you give some sample testimonial?

@jayadevx , gemini.google.com, prompt. Then, edit to match the reality of your usage.

```
write me a testimonial for the following:

I use Caddy Security app for Caddy web server for my internal web servers. It does good job at integrating my LDAP users and internal web apps.
```
