### ISSUE TITLE
How to set a custom session timeout value?

### ISSUE THREAD

**Issue by bfg100k** [greenpau/caddy-security#317]
I'm implementing this module in a home environment and managed to get it up and running. However, I'm finding that the session times out rather quickly (less than 30mins for sure). Is there a setting I can specify to extend it? Ideally I would like days instead.

**Comment by mgmorcos** [comment]
👍

**Comment by greenpau** [comment]
@bfg100k , you are probably looking for “lifetime” settings. Please see https://github.com/authcrunch/authcrunch.github.io/blob/c6d02968980595021863c223369f9f6cb31992b6/assets/solutions/A00003/Caddyfile#L36

That’s 3600 seconds or 1 hour. Use 7200 for 2 hours.
