### ISSUE TITLE
breakfix: Azure OAuth2 config not working

### ISSUE THREAD

**Issue by MrSuttonmann** [greenpau/caddy-security#318]
**Describe the issue**

I’ve followed the documentation for setting up an Azure OAuth2 IdP.
When I run my pipeline to validate the Caddyfile, I get the following error:

`Error: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 1: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 1: loading handler modules: position 1: loading module 'authentication': provision http.handlers.authentication: loading authentication providers: module name 'authorizer': provision http.authentication.providers.authorizer: loading security app module: provision security: server initialization failed: failed configuring identity provider: failed to fetch metadata for OAuth 2.0 authorization server: metadata authorization_endpoint field not found for provider azure`

**Configuration**

Paste full `Caddyfile` below:

```

{

	order authenticate before respond
	order authorize before reverse_proxy

	security {
		oauth identity provider azure {
			realm azure
			driver azure
			client_id {env.ENTRA_CLIENT_ID}
			tenant_id {env.ENTRA_TENANT_ID}
			client_secret {env.ENTRA_CLIENT_SECRET}
			scopes openid email profile
		}
		
		
		authentication portal authportal {
			crypto default token lifetime 3600
			crypto key sign-verify {env.JWT_SHARED_KEY}
			cookie domain littleberrylodge.co.uk
			enable identity provider azure
			ui {
				links {
					"My Identity" "/whoami" icon "las la-user"
				}	
			}	
			
			transform user {
				match realm azure
				action add role authp/user
				ui link "PiHole" https://dns.littleberrylodge.co.uk icon "las la-star"
			}
			
			transform user {
			 	match realm azure
			 	match email ted@littleberrylodge.co.uk
			 	action add role authp/admin
			}		
		}
		
    		authorization policy azure {
			set auth url https://auth.littleberrylodge.co.uk/auth/oauth2/azure/authorization-code-callback
			crypto key verify {env.JWT_SHARED_KEY}
			allow roles authp/admin authp/user
			validate bearer header
			inject headers with claims
		}			
	}
}

*.littleberrylodge.co.uk {

	tls domains@littleberrylodge.co.uk {
		dns cloudflare {env.CLOUDFLARE_API_KEY}
	}	

	@plex host plex.littleberrylodge.co.uk
	handle @plex {
		reverse_proxy 10.0.0.3:32400
	}

	@dns host dns.littleberrylodge.co.uk
	handle @dns {
		encode zstd gzip
		authorize with azure
		redir / /admin{uri}
		reverse_proxy http://pihole
	}

	@git host git.littleberrylodge.co.uk
	handle @git {
		reverse_proxy http://gitea:3000
	}

	@photos host photos.littleberrylodge.co.uk
	handle @photos {
		encode zstd gzip
		reverse_proxy http://photoview
	}
	
	@auth host auth.littleberrylodge.co.uk 
	handle @auth {
		authenticate with myportal
	}
			

	handle {
		abort
	}
}

```

**Version Information**

Provide output of `caddy list-modules -versions | grep git` below:

```

Error: unknown shorthand flag: 'v' in -versions

```

**Expected behavior**

I expect the configuration to work!

**Additional context**

**Comment by abirvepete** [comment]
what is meaning of blank nvironment variables？ I try The Microsoft oauth2.0 recently， i Compare The part Which is Microsoft of the documentation. the blank nvironment variables is meaing that we not set the metadata  authorization_endpoint ?

**Comment by greenpau** [comment]
> what is meaning of blank nvironment variables？

@abirvepete , it is likely the environment variables were not set.
