### ISSUE TITLE
question: Passkey support

### ISSUE THREAD

**Issue by cromelex** [greenpau/caddy-security#324]
Hi,

I have tried to enroll a [passkey ](
https://fidoalliance.org/passkeys/#resources) as the "2fa" token, instead of a physical key.
For reference, I have manged to enroll a Yubikey USB, a Yubikey NFC, and also via Windows Hello.

I have tried a Bitwarden Passkey and get the following errors, one on Chrome another on the Firefox.

```
TypeError
DataView: expected ArrayBuffer, got Uint8Array
```

```
TypeError
First argument to DataView constructor must be an ArrayBuffer
```

On mobile, on my partner's Chrome on Android, I get a similar error while trying to enroll a Google Passkey (generated via their password manager - in browser).

Considering it is, to my understanding, a type of U2F implementation, of which the hardware keys are supported, I wonder if this is a quick fix. Would certainly be a nice to have.

Thanks,

**Comment by greenpau** [comment]
Google docs https://kstatic.googleusercontent.com/files/6a8a4d6536362a2107727b20072f2ab4e853291ce5eb90cc85b6b3b814740639f5d89e964598a63ed62cca4899006d2361cd8caed726b6e4997135a08dba200f

**Comment by greenpau** [comment]
@cromelex , when you say Passkeys are not working. How did you test it?

I was able to enroll passkeys with Windows Hello.

![image](https://github.com/greenpau/caddy-security/assets/3826416/aa6fcb15-c2ed-44a7-9530-021e18178bed)

![image](https://github.com/greenpau/caddy-security/assets/3826416/90f62deb-2fd8-4b0b-84c0-7b8d39b78c06)

![image](https://github.com/greenpau/caddy-security/assets/3826416/21868012-6105-432f-b6ef-93baccd8d27a)

![image](https://github.com/greenpau/caddy-security/assets/3826416/fbf60278-d53f-45fa-8753-427e2b692ef1)

![image](https://github.com/greenpau/caddy-security/assets/3826416/7d63e92c-0b4f-433a-bec5-f1fb9d8f86f6)

![image](https://github.com/greenpau/caddy-security/assets/3826416/7f511da4-7427-4bd4-8d43-9936e85cecbb)

Testing:

![image](https://github.com/greenpau/caddy-security/assets/3826416/57cea4ce-a010-4622-b95d-249c665df6bc)

![image](https://github.com/greenpau/caddy-security/assets/3826416/296acf6a-b7cf-4289-8e89-163bf64bbba8)

![image](https://github.com/greenpau/caddy-security/assets/3826416/fd27e046-073b-461c-8cb0-af2d1d94fa50)

**Comment by greenpau** [comment]
@cromelex , what is the procedure to setup Bitwarden? I am not familiar with it.

**Comment by cromelex** [comment]
@greenpau Windows passkeys do work, that's what I mentioned above: For reference, I have manged to enroll a Yubikey USB, a Yubikey NFC, and also via **Windows Hello.**

Bitwarden is a password management tool with a free tier that supports passkeys ( https://bitwarden.com/ ).
You'd have to set to an account to test, I assume.

Alternatively, if you have a Google account, they do have support for it as well?

Neither the bitwarden not the Google passkeys worked for me when enrolling (got the error message).

**Comment by greenpau** [comment]
@cromelex , thank you for the explanation! I am now working on the new Profile UI and will try Bitwarden when rewriting that U2F related code.

**Comment by greenpau** [comment]
I might have found the issue. I am testing to see if what I see applies to Bitwarden,

**Comment by greenpau** [comment]
@cromelex, I release Profile UI 1.0. It contains new API and I think you should be able to onboard your key. At least try it.

Please see:
* https://github.com/greenpau/caddy-security/issues/327
* https://youtu.be/f-P2y5jrq-w

**Comment by cromelex** [comment]
Thank you for this. Not sure when it'll be, but I'll give it a try once I get a bit of spare time.

**Comment by greenpau** [comment]
@cromelex , I recorded the video about onboarding hardware tokens here: https://www.youtube.com/watch?v=272UQYWGhKo

It is the same thing for passkeys. I verified with Windows Hello and Apple Passkeys.

**Comment by greenpau** [comment]
Here is Windows Hello example: https://youtu.be/6BWPu7127Bw
