### ISSUE TITLE
feature: LDAP assumes memberof is available which is deprecated in OpenLDAP

### ISSUE THREAD

**Issue by ForceFaction** [greenpau/caddy-security#332]
> A clear and concise description of what you want the system to do.

The system should not assume memberof for LDAP.  Every group contains a list of memberUids which should be searched instead for the users uid.

> What are the Caddyfile directives that need to be added.

The Caddyfile needs a flag that disables memberof.  Then the groups a user belongs to can be found with a search_group_filter like this `(&(memberUid=%s)(objectClass=posixGroup))` where %s is the uid of the user.

**Comment by birlorg** [comment]
@ForceFaction 

If you add posix_groups option to the ldap:// URL setting, it will do a separate search for group membership with an attribute option of `search_group_filter`

```
servers {
        ldap://ldap.example.com posix_groups
      }
```

Then in the `attributes` section:

```
 search_base_dn "DC=example,DC=com"
 search_filter "(&(|(uid=%s)(email=%s))(objectClass=person))"
 search_group_filter "(member=%s)"
  ```

Obviously the search strings will need to be changed to work with your openldap setting, but the %s in search_group_filter will be the full dn of the user. See the docs: https://docs.authcrunch.com/docs/authenticate/ldap/ldap
