### ISSUE TITLE
breakfix: GitHub oauth2 flow always redirects back to /login even after successful login

### ISSUE THREAD

**Issue by infogulch** [greenpau/caddy-security#333]
I'm trying to use the github oauth flow based on [this page](https://docs.authcrunch.com/docs/authenticate/oauth/backend-oauth2-0007-github) and the linked Caddyfile, and it seems to be successfully authorizing based on the "Successful login" INFO message in the logs, but the end of the flow always ends up back at `/login`. Manually requesting `/whoami` or `/profile` after login also shows the "Successful login" log message but still redirects back to `/login` anyway.

Here's a summary of the request flow based on inspecting my browser network requests and logs:

* GET `https://auth.localhost:8443/login` -> 200 OK
* (click github login button)
* GET `https://auth.localhost:8443/oauth2/github` -> 302, with location header: `https://github.com/login/oauth/authorize?client_id=(snip)&redirect_uri=https%3A%2F%2Fauth.localhost%3A8443%2Foauth2%2Fgithub%2Fauthorization-code-callback&scope=read%3Auser&state=(snip)`
* GET `https://github.com/login/oauth/authorize?client_id=(snip)&redirect_uri=https://auth.localhost:8443/oauth2/github/authorization-code-callback&scope=read:user&state=(snip)` -> 200 OK
* (click authorize button on github.com)
* POST `https://github.com/login/oauth/authorize` -> returns 200 OK with content (which I assume uses js to redirect to the app):
  ```
  ...
  <h3 data-view-component="true" class="blankslate-heading">You are being redirected to the authorized application.</h3>
  <p data-view-component="true">If your browser does not redirect you back, please visit <a id="js-manual-authorize-redirect" href="https://auth.localhost:8443/oauth2/github/authorization-code-callback?code=(snip)&amp;state=(snip)">this setup page</a> to continue.
  ```
* GET `https://auth.localhost:8443/oauth2/github/authorization-code-callback?code=(snip)&state=(snip)` -> 303 with location: `https://auth.localhost:8443/portal`
* I assume this is where the log line occurs:
  * `2024/04/11 06:17:08.086 INFO    security        Successful login        {"session_id": "(snip)", "request_id": "(snip)", "auth_method": "oauth2", "auth_realm": "github", "user": {"metadata":{"id":133882},"name":"Joe Taber","origin":"https://api.github.com/user","picture":"https://avatars.githubusercontent.com/u/133882?v=4","sub":"github.com/infogulch"}}`
* GET `https://auth.localhost:8443/portal` -> 302 with location `https://auth.localhost:8443/login`

The last request response is unexpected; I'd expect it to render `/portal` but instead it redirects back to `/login`.

### Caddyfile

```Caddyfile
{
	http_port 8080
	https_port 8443
	# debug

	order authenticate before respond
	order authorize before basicauth

	security {
		oauth identity provider github {env.GITHUB_CLIENT_ID} {env.GITHUB_CLIENT_SECRET}

		authentication portal myportal {
			crypto default token lifetime 3600
			crypto key sign-verify {env.JWT_SHARED_KEY}
			cookie domain localhost
			enable identity provider github
			ui {
				links {
					"My Identity" "/whoami" icon "las la-user"
				}
			}

			transform user {
				match realm github
				action add role authp/user
				ui link "XRss" https://xrss.localhost:8443/ icon "las la-star"
			}

			transform user {
				match realm github
				match sub github.com/infogulch
				action add role authp/admin
			}
		}

		authorization policy mypolicy {
			set auth url https://auth.localhost:8443/oauth2/github
			crypto key verify {env.JWT_SHARED_KEY}
			allow roles authp/admin authp/user
			validate bearer header
			inject headers with claims
		}
	}
}

(tls_config) {
	tls {$HOME}/.local/caddy/server.crt {$HOME}/.local/caddy/server.key
}

auth.localhost {
	import tls_config
	authenticate with myportal
}

xrss.localhost {
	import tls_config
	authorize with mypolicy
	root * {env.HOME}/www
	file_server
}
```

### My github app config

Configured according to https://docs.authcrunch.com/docs/authenticate/oauth/backend-oauth2-0007-github with specifically:

* Homepage URL: `https://auth.localhost:8443/`
* Callback URL: `https://auth.localhost:8443/oauth2/github/authorization-code-callback`

### How I'm building Caddy

```shell
$ go version
go version go1.22.1 linux/amd64

# Build caddy. Note: I don't think I'm getting as far as the xrss or xtemplate modules, so the fact that they are local shouldn't matter
GOFLAGS='-tags="sqlite_json"' CGO_ENABLED=1 xcaddy build --with github.com/infogulch/xrss=. --with github.com/infogulch/xtemplate=../xtemplate --with github.com/greenpau/caddy-security

$ ./caddy version
v2.7.6 h1:w0NymbG2m9PcvKWsrXO6EEkY9Ru4FJK8uQbYcev1p3A=

# Run caddy:
$ (set -a; . .env; ./caddy run)

# Caddy auth modules:
$ ./caddy list-modules --versions | grep -E "(auth|security)"
http.authentication.hashes.bcrypt v2.7.6
http.authentication.hashes.scrypt v2.7.6
http.authentication.providers.http_basic v2.7.6
http.handlers.authentication v2.7.6
tls.client_auth.leaf v2.7.6
http.authentication.providers.authorizer v1.1.29
http.handlers.authenticator v1.1.29
security v1.1.29
```

**Comment by greenpau** [comment]
@infogulch , 2 things.

First, reconfigure the portal to use /auth/

route /auth* {
		authenticate with myportal
	}

Second, try removing 

match sub github.com/infogulch

i want to see whether the matcher works.

**Comment by greenpau** [comment]
@infogulch , also, the symptom that you are describing is usually indicative to cookie not being propagated.

try adding 

cookie domain auth.localhost

**Comment by infogulch** [comment]
> First, reconfigure the portal to use /auth/

This doesn't help; now nothing renders at /.

> cookie domain auth.localhost

Ah that was it.

The problem is that a cookie set on `localhost` specifically can't be accessed by `*.localhost` subdomains. See this [StackOverflow q&a](https://stackoverflow.com/a/74714047/213246). The solution is to move everything down one subdomain level, e.g. I chose `apps.localhost`:

```
cookie domain apps.localhost

auth.apps.localhost {
}

xrss.apps.localhost {
}
```

This seems like a decent solution to host apps for testing Caddy locally, since you can simply add domains under and it works.

Thank you for your help!

**Comment by greenpau** [comment]
@infogulch , have you tried “localhost.localdomain”? It might work.

**Comment by infogulch** [comment]
I tried but it resulted in a dns error. It looks like localhost.localdomain requires explicit hosts file configuration, so it wasn't being resolved. Whereas using sites on `*.sub.localhost` worked for me right away. I'm on windows if it matters.

I'd heard of it but I didn't know anything about localhost.localdomain before you mentioned it. This looks like a decent reference: https://locall.host/localhost-localdomain/
