### ISSUE TITLE
nginx style Forward Auth example.

### ISSUE THREAD

**Issue by xpufx** [greenpau/caddy-security#35]
Hello. https://github.com/caddyserver/caddy/issues/2894 is closed citing this project's existence. Nginx' auth_request directive (https://nginx.org/en/docs/http/ngx_http_auth_request_module.html) works with a simple HTTP response code. Is this kind of functionality available? If yes, can you please direct me to the relevant documentation.

Another question while we're at it. It seems caddy-security is now a single module that includes the former authorize and portal components. Is it still possible to build it without the portal for people who already have an external authentication system in place?

**Comment by greenpau** [comment]
@xpufx, please create `Caddyfile` that would work in your setup. After that I will modify it (with some directives) to do what you are asking here.

**Comment by xpufx** [comment]
@greenpau Thank you. 

```
whoami.DOMAIN.eu {

        route /akprox* {
                reverse_proxy https://sso.DOMAIN.de
        }


        route /* {

               { # do the auth against authentik
                # auth url is   https://sso.DOMAIN.de/akprox/auth/nginx
                # last part can be traefik or nginx. I am told the difference is minor
                # and both will work for another proxy.
               }
                reverse_proxy http://10.0.10.11:14000
        }
}
```

**Comment by greenpau** [comment]
> do the auth against authentik

@xpufx , I don't know much about authentik. What is your OAuth provider? Is `authentik` play the role of auth provider?

**Comment by xpufx** [comment]
Yes. It would basically provide the client id and secret.

**Comment by greenpau** [comment]
> Yes. It would basically provide the client id and secret. (supports saml/oauth/oidc etc)

@xpufx , here is the setup for this type of proxy. I tried keeping the names descriptive.

The OAuth provider in this case is Github.

Please note the Callback URL.

![image](https://user-images.githubusercontent.com/3826416/151614234-c8a538ff-2ebc-4386-9f23-b54583e6a7ac.png)

When you will be setting up authentic you would need to change the highlighted `github` to the realm you configure for this specific provider. To setup authentic as OAuth provider you must follow the generic setup here: https://authp.github.io/docs/authenticate/oauth/backend-oauth2-0000-generic

**NOTE**: The `auth.myfiosgateway.com` in my example is your `whoami.DOMAIN.eu`.

💡  I also added a slim down version over [here](https://github.com/authp/authp.github.io/blob/main/assets/conf/oauth/authproxy/Caddyfile)

Create `~/authproxy.env` file. I added the shortcuts for backend in [v1.0.8](https://github.com/greenpau/caddy-security/releases/tag/v1.0.8) release.

```
export JWT_SHARED_KEY=1999fcc6-5499-4524-9b93-f4ad2dd46e5e
export GITHUB_CLIENT_ID="foo"
export GITHUB_CLIENT_SECRET="bar"
```

And load it:

```
source ~/authproxy.env
```


Here is the config:

```
{
        http_port 8080
        https_port 8443
        debug

        order authenticate before respond
        order authorize before basicauth

        security {
                authentication portal authz_proxy_portal {
                        crypto default token lifetime 1
                        crypto key sign-verify {env.JWT_SHARED_KEY}
                        backend github {env.GITHUB_CLIENT_ID} {env.GITHUB_CLIENT_SECRET}
                        transform user {
                                match realm github
                                action add role authp/user
                                ui link "My Website" / icon "las la-star"
                        }
                }

                authorization policy default_authz_policy {
                        # disable auth redirect
                        set auth url /authzproxy/oauth2/github/
                        crypto key sign-verify {env.JWT_SHARED_KEY}
                        allow roles authp/user authp/admin
                }
        }
}

(tlsConfig) {
        tls /home/greenpau/.local/tls/myfiosgateway/server.crt /home/greenpau/.local/tls/myfiosgateway/server.key
}

auth.myfiosgateway.com {
        import tlsConfig

        route /authzproxy* {
                # authenticate /authzproxy* with authz_proxy_portal
                authenticate with authz_proxy_portal
        }

        route {
                authorize with default_authz_policy
                respond "assetq is running"
        }
}
```

**Comment by greenpau** [comment]
The `set auth url /authzproxy/oauth2/github/` would also change to the `realm` you would assign to the authentic OAuth.

**Comment by xpufx** [comment]
Thank you. I will test and see if I can get it working.

**Comment by greenpau** [comment]
First thing you need to do is getting a successful auth from “ /authzproxy/login”.

**Comment by xpufx** [comment]
Hello greenpau. This was a bit confusing so I used the generic oauth2 configuration instead as a base. Below is my configuration. Both authentik and caddy-security are authenticating properly. However I keep going between authentik and caddy-security login (with the Generic oauth button).   Either my config is broken or authentik is not setting something caddy-security needs. I can't tell which. Do you see anything wrong with the below caddy-security oauth config?

```
{
	email MYUSER@gmail.com
	acme_dns cloudflare Skw_j5fub2S9T6VWslcWRtB5rOpJz_L-2MwvVRKI
	debug
	
	order authenticate before respond
	order authorize before basicauth

	security {
		authentication portal myportal {
			crypto key verify from file /home/MYUSER/caddy/authentik.pem
			backends {
				generic_oauth2_backend {
					method oauth2
					realm generic
					provider generic
					client_id 3af9ee1e0cf1a63fd3bdcd2c38c6a2ad82923d27
					client_secret 916ca1c2d08908d21a08e8feb4dd2857765cb27c574f52ad658d98199c7937ab823cd8e450a3431fd7f1c21443572140424ffbf62321a509d66c86db1c5e16d2
					scopes openid email profile
					base_auth_url https://sso.MYDOMAIN.de/
					metadata_url https://sso.MYDOMAIN.de/application/o/whoami-oauth/.well-known/openid-configuration
				}
			}
			cookie domain whoami.MYDOMAIN.eu
			ui {
				links {
					"My Identity" "/whoami" icon "las la-user"
				}
			}

			transform user {
				match realm generic
				action add role authp/user
				ui link "File Server" https://whoami.MYDOMAIN.eu/ icon "las la-star"
			}

			transform user {
				match realm generic
				match email MYUSER@MYDOMAIN.de
				action add role authp/admin
			}
		}

		authorization policy mypolicy {
			set auth url https://caddyauth.MYDOMAIN.de/oauth2/generic
			crypto key verify from file /home/MYUSER/caddy/authentik.pem
			allow roles authp/admin authp/user
			validate bearer header
			inject headers with claims
		}
	}
}

# for postfix/dovecot certificates
mail.MYDOMAIN.de {

}


caddyauth.MYDOMAIN.de {
	authenticate with myportal
}

whoami.MYDOMAIN.eu {
	authorize with mypolicy
	reverse_proxy	10.0.10.11:14000	

}

```

**Comment by greenpau** [comment]
@xpufx , if you just go to auth portal, you are able to authenticate and see your identity, correct? Please provide screenshots.

also, you are seeing my identity and file server links, correct?

what is you authentik configuration? Specifically callback url? Please provide screenshots.

**Comment by greenpau** [comment]
@xpufx , are you able to click the “File Server” link and browse to whoami server?

**Comment by xpufx** [comment]
Actually no. I am not seeing a File Server link or a my identity link. What I am seeing is "Successful login" in the log.

```
Jan 29 19:47:07 mail caddy[734842]: {"level":"info","ts":1643485627.7175086,"logger":"security","msg":"Successful login","session_id":"ZEkMGCLeSEnamMYF1SPK7CXnjJ7HeTrj0fduECrN97gh","request_id":"dc92423f-2a1f-4b84-90ff-4ec51bcb085f","backend":{"name":"generic_oauth2_backend","realm":"generic","method":"oauth2"},"user":{"addr":"95.70.146.4","exp":1643486527,"frontend_links":["\"File Server\" https://whoami.MYDOMAIN.eu/ icon \"las la-star\""],"groups":["Vaultwarden Users","authentik Admins","ldapadmin","user","admin","useradmins","Vaultwarden Users","authentik Admins","ldapadmin","user","admin","useradmins"],"iat":1643485627,"iss":"https://caddyauth.MYDOMAIN.de/oauth2/generic/","jti":"ZEkMGCLeSEnamMYF1SPK7CXnjJ7HeTrj0fduECrN97gh","mail":"MYUSER@MYDOMAIN.de","name":"MYUSER Altunergil","nbf":1643485567000,"origin":"generic","realm":"generic","role":"authentikuser","roles":["authp/user","authp/admin"],"sub":"e30f9d117a4e772584d6fb32bd5fa6706850a330ff880cf7e37fb24eaaf5ce0d"}}
```

**Comment by greenpau** [comment]
@xpufx , when you click the button to login to authentik, what happens next? Web browser screenshot and trace would be helpful.

**Comment by xpufx** [comment]
By the way the original topic of this issue was regarding whether caddy-security can implement the Forward Auth functionality of Nginx and Traefik as claimed by the caddy server authors.  I like the possibility of authenticating with Oauth/SAML but that's a much more complicated setup than what Forward Auth provides. (I fully realize forward auth is not something an idp should provide. It's a web proxy feature.)

Also I will open another issue regarding using just the "authorize" portion of caddy-security with a corresponding Caddyfile for use with an external idp.

**Comment by greenpau** [comment]
> whether caddy-security can implement the Forward Auth functionality of Nginx and Traefik as claimed by the caddy server authors. 

@xpufx , we are just troubleshooting here. If everything is being setup properly. The user who browsed to the file server, would be redirected to auth portal, to authentik, then back to auth portal, and back to the fileserver. The user never sees the auth portal interface.

**Comment by greenpau** [comment]
I actually don’t like the “ "role":"authentikuser",”

**Comment by greenpau** [comment]
It could be that the “role” messes up the “roles”

**Comment by greenpau** [comment]
@xpufx , so you have “groups” and “role” being passed by the authentik. Need to check what would be the desired logic here.

the goal is to be able to login to portal and see the 2 links.

**Comment by xpufx** [comment]
> I actually don’t like the “ "role":"authentikuser",”

I had actually added that bit to the authentik side because I tried to get authentication working without using caddy-auth-portal as my authentication portal. I will remove it and see if that makes a difference.

**Comment by greenpau** [comment]
@xpufx , basically, try not adding role or group for now.

I will look at the way to handle role, roles, and groups at the same time.

**Comment by greenpau** [comment]
@xpufx , once we finish the troubleshooting, you will be able to add the groups in authentic and it will propagate to the token issues by the portal.

**Comment by xpufx** [comment]
Here's some info from browser Developer Console and caddy logs.

Going to portal login, Generic icon shows. At this point the only interesting thing in the console is:

```
set-cookie: AUTHP_SESSION_ID=qvzDNbv29PFLVU8NHNrCcIjcUBaarqsvoenpygj7nFlC; Domain=whoami.MYDOMAIN.eu; Path=/; Secure; HttpOnly;
```
When I hit the Generic button it goest to authentik. (It's configured to redirect manually now when I hit continue)

```
Jan 29 20:06:18 mail caddy[734842]: {"level":"debug","ts":1643486778.5612354,"logger":"security","msg":"External login requested","session_id":"VxkdFKJrfMoyGtgdsKdqy8fku4bOazKF2NDPhE8Kgmllc","request_id":"be3da0bf-6b4d-49e5-9e41-f4c46b59606b","base_url":"https://caddyauth.MYDOMAIN.de","base_path":"/","auth_method":"oauth2","auth_realm":"generic","request_path":"/oauth2/generic"}
Jan 29 20:06:18 mail caddy[734842]: {"level":"debug","ts":1643486778.561287,"logger":"security","msg":"redirecting to OAuth 2.0 endpoint","request_id":"be3da0bf-6b4d-49e5-9e41-f4c46b59606b","redirect_url":"https://sso.MYDOMAIN.de/application/o/authorize/?client_id=3af9ee1e0cf1a63fd3bdcd2c38c6d2ad82923d27&nonce=0WoPMrLjVFeJWoILpntSOHz2YozJgx6E&redirect_uri=https%3A%2F%2Fcaddyauth.MYDOMAIN.de%2Foauth2%2Fgeneric%2Fauthorization-code-callback&response_type=code&scope=openid+email+profile&state=c3e94005-ed9e-4e24-b06e-5c3b98c36dc9"}
Jan 29 20:06:18 mail caddy[734842]: {"level":"debug","ts":1643486778.5612934,"logger":"security","msg":"Redirect to authorization server","session_id":"VxkdFKJrfMoyGtgdsKdqy8fku4bOazKF2NDPhE8Kgmllc","request_id":"be3da0bf-6b4d-49e5-9e41-f4c46b59606b","url":"https://sso.MYDOMAIN.de/application/o/authorize/?client_id=3af9ee1e0cf1a63fd3bdcd2c38c6d2ad82923d27&nonce=0WoPMrLjVFeJWoILpntSOHz2YozJgx6E&redirect_uri=https%3A%2F%2Fcaddyauth.MYDOMAIN.de%2Foauth2%2Fgeneric%2Fauthorization-code-callback&response_type=code&scope=openid+email+profile&state=c3e94005-ed9e-4e24-b06e-5c3b98c36dc9"}

```

Authentik also sets a csrf and session cookie but it shouldn't matter at this step.  Click continue, the browser goes back to the login page. I have a feeling at this point it should go to whoami.DOMAIN.com instead for this to work.

Interesting bits in log:

```
Jan 29 20:11:09 mail caddy[734842]: {"level":"info","ts":1643487069.40793,"logger":"security","msg":"Successful login","session_id":"P70Mlj7ZreWgt8q4qDyd6nnWbMPrGLTvBNxh","request_id":"6063f0e7-3fc6-45c2-bb6c-e6b2afeb6897","backend":{"name":"generic_oauth2_backend","realm":"generic","method":"oauth2"},"user":{"addr":"95.70.146.4","exp":1643487969,"frontend_links":["\"File Server\" https://whoami.MYDOMAIN.eu/ icon \"las la-star\""],"groups":["Vaultwarden Users","authentik Admins","ldapadmin","user","admin","useradmins"],"iat":1643487069,"iss":"https://caddyauth.MYDOMAIN.de/oauth2/generic/","jti":"P70Mlj7ZreWgt8q4qDyd6nnWbMPrGLTvBNxh","mail":"MYUSER@MYDOMAIN.de","name":"MYUSER Altunergil","nbf":1643487009000,"origin":"generic","realm":"generic","roles":["authp/user","authp/admin"],"sub":"e30f9d117a4e772584d6fb32bd5fa6706850a330ff880cf7e37fb24eaaf5ce0d"}}
Jan 29 20:11:09 mail caddy[734842]: {"level":"debug","ts":1643487069.5537572,"logger":"security","msg":"Redirect served","session_id":"WuZt4SOpOZg7xa6j88noZY5GEuH03lSGSM7w2Qma","request_id":"311a6d0e-b4a4-49c2-999d-8854d0ea559f","redirect_url":"https://caddyauth.MYDOMAIN.de/login","status_code":302}
Jan 29 20:11:09 mail caddy[734842]: {"level":"debug","ts":1643487069.8840265,"logger":"security","msg":"static assets","session_id":"Cum26TiXPLbKEKRIbufYWvDSYmardWFfASnWe0Zbc","request_id":"74c79aa5-19fd-4d1b-999c-cc0353c521d7","url_path":"/assets/materialize-css/css/materialize.css","request":{"session_id":"Cum26TiXPLbKEKRIbufYWvDSYmardWFfASnWe0Zbc","base_url":"https://caddyauth.MYDOMAIN.de","base_path":"/","content_type":"text/css,*/*;q=0.1"},"source_address":"95.70.146.4"}
```

msg":"Redirect served"   caught my attention. Maybe you can tell why it's redirecting back to login. As before logs say "successful login" but I get redirected and I never see a File link or a my identity button as if login was not sucessful.

It loops from here.

**Comment by greenpau** [comment]
> Authentik also sets a csrf and session cookie but it shouldn't matter at this step. Click continue, the browser goes back to the login page. I have a feeling at this point it should go to whoami.DOMAIN.com instead for this to work.

@xpufx , by the "login page," you mean the page with "Generic" button? If so, then you did not pass authentication.

I suspect the issue is with `groups`, `role`, and `roles` all being returned at the same time by the Authentik. Will look at it later today.

**Comment by greenpau** [comment]
@xpufx , please keep your Authentik config intact for now. I will release a patch and see how your auth experience changes.

**Comment by xpufx** [comment]
I already had a scope without groups set up (Dovecot xoauth2 doesn't like it) and used that instead. Here's the log for that. I don't need the groups as  I only need authentication now.

```
Jan 29 20:21:47 mail caddy[734842]: {"level":"debug","ts":1643487707.7854779,"logger":"security","msg":"decoded claims from OAuth 2.0 authorization server access token","request_id":"c7906589-eae2-4751-be8a-9200361141fd","claims":{"email":"MYUSER@MYDOMAIN.de","exp":1646079707,"iat":1643487707,"iss":"https://sso.MYDOMAIN.de/application/o/whoami-oauth/","name":"MYUSER MYLAST","sub":"e30f9d117a4e772584d6fb32bd5fa6706850a330ff880cf7e37fb24eaaf5ce0d"}}
Jan 29 20:21:47 mail caddy[734842]: {"level":"info","ts":1643487707.7854917,"logger":"security","msg":"Successful login","session_id":"4yYNnwX8BPSJTJGlzbmOJ8q2NkfG5pOOYgafOKNTHu","request_id":"c7906589-eae2-4751-be8a-9200361141fd","auth_method":"oauth2","auth_realm":"generic","user":{"email":"MYUSER@MYDOMAIN.de","exp":1646079707,"iat":1643487707,"iss":"https://sso.MYDOMAIN.de/application/o/whoami-oauth/","name":"MYUSER MYLAST","sub":"e30f9d117a4e772584d6fb32bd5fa6706850a330ff880cf7e37fb24eaaf5ce0d"}}
Jan 29 20:21:47 mail caddy[734842]: {"level":"debug","ts":1643487707.785592,"logger":"security","msg":"user transformation ended","session_id":"4yYNnwX8BPSJTJGlzbmOJ8q2NkfG5pOOYgafOKNTHu","request_id":"c7906589-eae2-4751-be8a-9200361141fd","user":{"addr":"95.70.146.4","exp":1643488607,"frontend_links":["\"File Server\" https://whoami.MYDOMAIN.eu/ icon \"las la-star\""],"iat":1643487707,"iss":"https://caddyauth.MYDOMAIN.de/oauth2/generic/","jti":"4yYNnwX8BPSJTJGlzbmOJ8q2NkfG5pOOYgafOKNTHu","mail":"MYUSER@MYDOMAIN.de","name":"MYUSER MYLAST","nbf":1643487647000,"origin":"generic","realm":"generic","roles":["authp/user","authp/admin"],"sub":"e30f9d117a4e772584d6fb32bd5fa6706850a330ff880cf7e37fb24eaaf5ce0d"}}
Jan 29 20:21:47 mail caddy[734842]: {"level":"info","ts":1643487707.78676,"logger":"security","msg":"Successful login","session_id":"4yYNnwX8BPSJTJGlzbmOJ8q2NkfG5pOOYgafOKNTHu","request_id":"c7906589-eae2-4751-be8a-9200361141fd","backend":{"name":"generic_oauth2_backend","realm":"generic","method":"oauth2"},"user":{"addr":"95.70.146.4","exp":1643488607,"frontend_links":["\"File Server\" https://whoami.MYDOMAIN.eu/ icon \"las la-star\""],"iat":1643487707,"iss":"https://caddyauth.MYDOMAIN.de/oauth2/generic/","jti":"4yYNnwX8BPSJTJGlzbmOJ8q2NkfG5pOOYgafOKNTHu","mail":"MYUSER@MYDOMAIN.de","name":"MYUSER MYLAST","nbf":1643487647000,"origin":"generic","realm":"generic","roles":["authp/user","authp/admin"],"sub":"e30f9d117a4e772584d6fb32bd5fa6706850a330ff880cf7e37fb24eaaf5ce0d"}}
Jan 29 20:21:47 mail caddy[734842]: {"level":"debug","ts":1643487707.90712,"logger":"security","msg":"Redirect served","session_id":"xohfrD7CFTXMfRKEfSEeoO0AgdQl74b9LBRai","request_id":"5ced67ed-75c9-41c3-b83c-69ce702ee2bc","redirect_url":"https://caddyauth.MYDOMAIN.de/login","status_code":302}
Jan 29 20:21:48 mail caddy[734842]: {"level":"debug","ts":1643487708.2249103,"logger":"security","msg":"static assets","session_id":"GhTLvW35rV6zIvhaLPTX6RJ2WTbRRUNCqGj9tcH","request_id":"eb513be7-3212-4fbf-8ad4-c6c6ee45ba6c","url_path":"/assets/materialize-css/css/materialize.css","request":{"session_id":"GhTLvW35rV6zIvhaLPTX6RJ2WTbRRUNCqGj9tcH","base_url":"https://caddyauth.MYDOMAIN.de","base_path":"/","content_type":"text/css,*/*;q=0.1"},"source_address":"95.70.146.4"}
```

**Comment by greenpau** [comment]
@xpufx , in auth portal config you have

```
			crypto key verify from file /home/MYUSER/caddy/authentik.pem
```

it really should be

```
			crypto key sign-verify from file /home/MYUSER/caddy/authentik.pem
```

**Comment by greenpau** [comment]
@xpufx , authentication = `sign-verify`, authorization = `verify`.

**Comment by greenpau** [comment]
It does not eliminate the issue with groups/role/roles, but it is something to try.

**Comment by xpufx** [comment]
> @xpufx , authentication = `sign-verify`, authorization = `verify`.

No change in behavior I'm afraid. At this point authentik does not return any roles/groups.

**Comment by greenpau** [comment]
@xpufx please email me the full log + create the logs of you browser.

**Comment by xpufx** [comment]
> @xpufx please email me the full log + create the logs of you browser.

Sure thing. I can also give you a temp user to see the headers yourself. How can I reach you? What's your email address?

**Comment by greenpau** [comment]
@xpufx , I totally did not see that you deviated from my example.

Instead of `cookie domain whoami.MYDOMAIN.eu` , you should have:

```
cookie domain MYDOMAIN.eu
```

My email is greenpau@outlook.com

**Comment by greenpau** [comment]
The cookie is being issued by `caddyauth.MYDOMAIN.de` for the use in `MYDOMAIN.de` domain. The `whoami.MYDOMAIN.eu` here is FQDN.

**Comment by xpufx** [comment]
> @xpufx , I totally did not see that you deviated from my example.
> 
> Instead of `cookie domain whoami.MYDOMAIN.eu` , you should have:
> 
> ```
> cookie domain MYDOMAIN.eu
> ```
> 
> My email is [greenpau@outlook.com](mailto:greenpau@outlook.com)

I tried both there but that was before everything you told me to do in this thread so it might make a difference. By the way I am kind of confused about the domain. As you can see my domains are not the same .de vs .eu. Which domain is it? portal or my app ? (I will try both of course) Or maybe same domain is required/assumed?

**Comment by xpufx** [comment]
OK with the cookie domain set to that of the portal I am able to now see My Identity and File Server (I didn't realize this was the name of my app until now :) ).   However now the loop moved elsewhere. I think I have to do some troubleshooting on the authentik side now before bugging you any further. I will hold off on sending you the logs since things will change.

**Comment by greenpau** [comment]
@xpufx , good pointing me at `.de vs .eu`. 

You cannot issue the cookie from `MYDOMAIN.de` to be used in `MYDOMAIN.eu`. That's not how browsers work.
A server in `MYDOMAIN.de` can only issue cookies in `MYDOMAIN.de` or without any domain (i.e. used only by that server).

```
caddyauth.MYDOMAIN.de {
	authenticate with myportal
}

whoami.MYDOMAIN.eu {
	authorize with mypolicy
	reverse_proxy	10.0.10.11:14000	

}
```

In sum, please use this config: https://github.com/authp/authp.github.io/blob/main/assets/conf/oauth/authproxy/Caddyfile

where `myapp.myfiosgateway.com` == `whoami.MYDOMAIN.eu`.

**Comment by xpufx** [comment]
I am aware of cross domain cookie requirements but I didn't know what it was doing in the context of this caddyfile. Of coures you're right. That's my bad. Thanks for pointing it out.

By the way somehow I saw MY Identity once but it's not working anymore. I will start again with the authproxy caddyfile.

**Comment by greenpau** [comment]
>  I will start again with the authproxy caddyfile. 

@xpufx , basics first. 

> still using two idps if I am not reading it wrong.

There are no 2 IdPs. There is 1 IdP - authentik. The portal play the role of an intermediary. Here, you are explicitly defining things in `portal`, because this is an expressive config. In this setup there is no "identity" lookup in the portal. It is just a passthrough.

**Comment by greenpau** [comment]
@xpufx , with the portal [configured](https://github.com/authp/authp.github.io/blob/main/assets/conf/oauth/authproxy/Caddyfile), you will get the seamless redirects, plus accounting, plus the redirection back to where you were when the session ended.

**Comment by greenpau** [comment]
@xpufx , there is even JS redirect: https://authp.github.io/docs/authorize/auto-redirect-url#javascript-redirect
when your URLs contains `#`, e.g. links to headings.

**Comment by xpufx** [comment]
I understand. Thank you.  If I am understanding you correctly I am to use the proxy configuration for 'github' (The backend name seems to be significant and need to be supported in the code) but use my own sso url as the auth endpoint. Is this correct?

**Comment by greenpau** [comment]
@xpufx , instead of `backend github {env.GITHUB_CLIENT_ID} {env.GITHUB_CLIENT_SECRET}`, add your configuration:

```
			backends {
				generic_oauth2_backend {
					method oauth2
					realm generic
					provider generic
					client_id 3af9ee1e0cf1a63fd3bdcd2c38c6a2ad82923d27
					client_secret 916ca1c2d08908d21a08e8feb4dd2857765cb27c574f52ad658d98199c7937ab823cd8e450a3431fd7f1c21443572140424ffbf62321a509d66c86db1c5e16d2
					scopes openid email profile
					base_auth_url https://sso.MYDOMAIN.de/
					metadata_url https://sso.MYDOMAIN.de/application/o/whoami-oauth/.well-known/openid-configuration
				}
			}
```

**Comment by greenpau** [comment]
@xpufx , also change realm to `realm authentik`. For clarity.

**Comment by xpufx** [comment]
Thank you. I am now realizing this is what you told me to do to begin with. I used the generic oauth config without realizing one was an intermediary proxy configuration while the other wasn't. Sorry about that. I am sure I'll be able to get this working now as I now have a clearer understanding of what is what. Thank you for taking the time with me to go over my config and providing the security components for caddy in general.

**Comment by greenpau** [comment]
>  Thank you for taking the time with me to go over my config and providing the security components for caddy in general.

@xpufx , I am here for you 👍 For me this whole experience is a professional development journey. I study things by coding them. Obviously there are many angles to look at a problem and find a solution. That's why there are so many good projects out there, e.g. Authentik that you are using.

This particular project was build with an "expressive" nature in mind. I want a person to read a Caddyfile and understand what is going on. Yes, there is certain complexity to it. That's the barrier to entry 😄

**Comment by greenpau** [comment]
@xpufx , release https://github.com/greenpau/caddy-security/releases/tag/v1.0.10 where groups, group, role and roles are all combined into roles.

Try to get the portal running such that you get to the identity page and you see something similar to this.

![image](https://user-images.githubusercontent.com/3826416/151678735-2bfe9e43-9d93-4e4e-b669-56903059aa10.png)

**Comment by tmeuze** [comment]
Hi, forgive me for the possibly silly question; let me know if I should create a new issue or discussion.

I've been following this thread and am trying to set up something similar with Authentik and Caddy-Security. I'm just getting started with a simple config:

```
	security {
		authentication portal atk {
			crypto key verify from file /opt/caddy/cert/atk.pem
			cookie domain DOMAIN.TLD
			backends {
				generic_oauth2_backend {
					method oauth2
					realm authentik
					provider generic
					client_id <redacted>
					client_secret <redacted>
					scopes openid email profile
					base_auth_url https://atk.DOMAIN.TLD
					metadata_url https://atk.DOMAIN.TLD/application/o/csoauth-ha/.well-known/openid-configuration
				}
			}
		}
	}
```
`atk.DOMAIN.TLD` being the location of Authentik. 

I cannot get Caddy to start with this config, due to a `connection refused` when attempting to access the metadata_url. But it just occurred to me that of course the connection is refused - because I am proxying Authentik through the same instance of Caddy that fails to start...

My question: is there a way to "invoke" Caddy-Security _after_ loading the configured site blocks? Must I proxy Authentik elsewhere? Or am I thinking about this all the wrong way?

Thank you for any help/insight you can provide!

**Comment by greenpau** [comment]
> let me know if I should create a new issue or discussion.

@tmeuze , let’s start with a new thread.

**Comment by greenpau** [comment]
@tmeuze , also, please watch https://youtube.com/watch?v=Mxbjfv47YiQ&feature=share from 45:32
