### ISSUE TITLE
breakfix: Cannot reach /settings endpoint even with authp/user role

### ISSUE THREAD

**Issue by mjwhite** [greenpau/caddy-security#358]
**Describe the issue**

I have caddy-security configured to authenticate a reverse proxy.

Password authentication works fine, but the /settings endpoint produces a page-not-found error even for authenticated users - I can't find any way to reach it.

**Configuration**

Caddyfile (hostnames etc modified):

```
{
        email name@example.com
        order authenticate before respond
        order authorize before reverse_proxy
        debug

        security {
                local identity store localdb {
                        realm local
                        path /var/lib/caddy/auth/users.json
                }

                authentication portal myportal {
                        enable identity store localdb
                        cookie domain example.com
                        cookie lifetime 86400

                        transform user {
                                match origin local
                                action add role authp/user
                                ui link "Portal Settings" /settings icon "las la-cog"
                        }
                }

                authorization policy user_policy {
                        set auth url https://auth.example.com/
                        allow roles authp/user
                }
        }
}

auth.example.com {
        authenticate with myportal
}

app.example.com {
        authorize with user_policy
        reverse_proxy https://127.0.0.1:1234 {
                transport http {
                        tls_insecure_skip_verify
                }
        }
}
```

**Version Information**

```
http.authentication.hashes.bcrypt v2.8.4
http.authentication.providers.http_basic v2.8.4
http.handlers.authentication v2.8.4
tls.client_auth.verifier.leaf v2.8.4
http.authentication.providers.authorizer v1.1.29
http.handlers.authenticator v1.1.29
security v1.1.29
```

**Expected behavior**

When logged in, the /whois endpoint works and shows the user has both the `authp/user` and `authp/guest` roles. My understanding from the docs is this should allow access to the /settings endpoint, for password change, MFA setup etc.

The result is a "Page Not Found" error, same as shown for any non-existent authentication portal path.

**Comment by greenpau** [comment]
@mjwhite , the settings page is now relocated to “/auth/profile/“. Please see reference config here: https://github.com/greenpau/caddy-security/issues/353

**Comment by mjwhite** [comment]
Thanks - got it! I do get some errors still on the new endpoint - the main Dashboard has an error (screenshot below), the MFA tab is blank and the other tabs work but give an error along the lines of 'user not found' when you save a new key.

![image](https://github.com/user-attachments/assets/1902b765-628b-4802-a40d-5e52d683c1d8)

Caddy's debug log shows this periodically:

```
{"msg":"failed to extract user metadata", ...
"error":"failed retrieving users: user not found"}
```

Any pointers on what I might be missing here gratefully received. I've aligned my Caddyfile to the example in #353 but may of course have missed something significant...

**Comment by retrodaredevil** [comment]
The documentation needs to be updated with this information, as the only way to find out about this is to look at this issue or the one linked.
