### ISSUE TITLE
question: Please tell me how to use the simplest Caddy configuration with HOTP?

### ISSUE THREAD

**Issue by daiaji** [greenpau/caddy-security#37]
I glanced at the documentation for a while, and honestly it's so complicated that I didn't even find a simple example for configuring HOTP.

**Comment by greenpau** [comment]
@daiaji , additionally, please see https://youtu.be/k8tbbffMGZk

**Comment by greenpau** [comment]
> didn't even find a simple example for configuring HOTP.

There is no example, because it is automatic once you add your keys in the "Settings" page.

**Comment by daiaji** [comment]
> There is no example, because it is automatic once you add your keys in the "Settings" page.

https://authp.github.io/docs/authenticate/local/local
Is that all there is to it? Let me try.

**Comment by greenpau** [comment]
> For example, how do I get to this caddy-security configuration page?

You create a link to browse to `/settings` page.

```
			transform user {
				match origin local
				action add role authp/user
				ui link "Portal Settings" /settings icon "las la-cog"
			}
```

Full config: https://github.com/authp/authp.github.io/blob/main/assets/conf/local/Caddyfile

It is also references in https://authp.github.io/docs/authenticate/local/local

> Is there anything else that needs to be configured in the Caddyfile?

Nothing. You can optionally enforce all users to have MFA. It is done with `require mfa` directive. https://authp.github.io/docs/authenticate/mfa#enabling-mfa

However, once you add your MFA, you will be asked to authenticate with it. If you have more than one MFA, then you will be given a choice.

>  Or is a port bound to the caddy-security configuration page by default?

What do you mean by `port bound`?

**Comment by greenpau** [comment]
>  Is that all there is to it? Let me try.

@daiaji , please watch the video about setting up local auth.  https://youtu.be/k8tbbffMGZk Once you passed that, you will have more clarity.
