### ISSUE TITLE
feature: add IP logging to failed password login attempts

### ISSUE THREAD

**Issue by Connor22** [greenpau/caddy-security#42]
> A clear and concise description of what you want the system to do.

"Password authentication failed. Please retry" error should also log the IP, not just the session_id/request_id, to allow software like Fail2Ban to work against brute force attackers.

**Comment by greenpau** [comment]
> "Password authentication failed. Please retry" error should also log the IP, not just the session_id/request_id, to allow software like Fail2Ban to work against brute force attackers.

@Connor22 , got it! Will add shortly.

Also, please watch https://github.com/greenpau/caddy-security/issues/19. It could be of interest to you.

**Comment by greenpau** [comment]
@Connor22 , the changes are [caddy-security v1.0.12](https://github.com/greenpau/caddy-security/releases/tag/v1.0.12). Please test.
