### ISSUE TITLE
feature: snippets in caddy security configuration

### ISSUE THREAD

**Issue by Matchlighter** [greenpau/caddy-security#45]
With the previous `caddy-auth-portal` and `caddy-auth-jwt` it was possible to setup a portal per-domain in separate files. This ability was useful to me since I use one Caddy instance to serve many apps, each with their own OAuth2 endpoint in my SSO. I've designed my Caddy config with one main Caddyfile that imports a directory of additional per-app Caddyfiles like so:
```
// Main Caddyfile
(sso) {
    route /auth* {
        authp {
            backends {
                generic_oauth2_backend {
                    method oauth2
                    realm ml
                    provider generic
                    metadata_url https://sso.somewhere.com/{args.0}
                    base_auth_url https://sso.somewhere.com/
                    client_id "{args.1}"
                    client_secret "{args.2}"
                    scopes openid email profile
                }
            }
        }
    }
}

(sso-jwt) {
    jwt {
        primary yes
        set auth url /auth/oauth2/ml
        allow roles authp/admin authp/user authp/guest
        inject headers with claims
    }
}

import ./apps/*.caddy

// Site Caddyfile
some.place.com {
	import sso some_place ID SECRET
	route {
		import sso-jwt
		reverse_proxy 10.1.0.5:8028 {
			// ...
		}
	}
}
```
From what I can tell with the new `caddy-security` (and please correct me if I'm wrong), the only way to setup auth "portals" is now via the global config and I can't configure any portals via my included files (since Caddy doesn't allow multiple globals blocks).

Is there any way to still use the above (or similar) file architecture with the new design of `caddy-security`?

Thanks for the project and taking a look at this question!

**Comment by greenpau** [comment]
@Matchlighter , thank you for the question!

Same idea here.

authentication portal site1portal {
…
}

authentication portal site2portal {
…
}

Authsite1.foo.bar {
  authenticate with site1portal
}

Authsite2.foo.bar {
  Authenticate with site2portal
}

Perhaps, I misunderstand the question.

Also, have you watched this? https://www.youtube.com/watch?v=Mxbjfv47YiQ&t=1s&vq=hd1080

have you seen configuration examples? https://github.com/authp/authp.github.io/tree/main/assets/conf

**Comment by Matchlighter** [comment]
I looked through the config examples and didn't see anything that matched. Hadn't come across that video though - I should be able to take a look at it tomorrow.

I had gathered that I could provide multiple `authentication portal xyz` entries, but don't they need to be in the Caddy global options block (`{ ... })` at the beginning of the main Caddyfile (and not allowed in `import`ed files) (as per Caddy docs, in reference to the global options "There can only be one at most, and it must be the first block of the Caddyfile.")? My ideal is to be able to maintain the portal config with the site config - not have the portal config in the main file and my site config in a separate file.

**Comment by greenpau** [comment]
@Matchlighter , to replay, you want to use “import” statements when configuring “security” app, correct? However, you can’t do it because it is in “global” config.

noticed you have “import ./apps/*.caddy”. In theory “security” is an “app”, so it could be in “apps” configuration section too, i.e. not only global configuration. Can you use “import” statements in “apps”?

**Comment by greenpau** [comment]
@Matchlighter , how many portal instances do you run? Which backends do they use?

Side note. I am introducing a new feature that allow a portal to be used across multiple domain. Basically you can specify “cookie <domain> enable” for each domain you want to enable under a single portal.

**Comment by Matchlighter** [comment]
Correct - each "app" is just a file with a `site.xyz { ... }` block. I've got my SSO (Authentik, similar to Okta) setup so that each "app"/site has it's own OAuth2 IdP (allowing me to use my SSO for "which-users-can-access-which-apps"-level policy). I currently have ~7 apps/sites set up this way on a single Caddy instance.

Your comment reminded me "imports", so I dug back into the Caddy docs and did a couple quick tests - it looks like snippet defintions are allowed before the global options block and that `import` is allowed _anywhere_ (unless modules need to explicitly support it, but it seems like it's more of a preprocess that Caddy does before actually parsing the file), so I should be able to do an `import  ./auth_portals/*.caddy` or `import ./apps/*.portal` in the `security` block of global options. I'd have to maintain two files per-site instead of one, but I think that will better fit my usage than modifying the main Caddyfile with portals for each app/site. Given your rename, I think we may have had parallel thoughts!

_"unless modules need to explicitly support it"_ - I think you'd know more about the details here. Given the rename, I'll keep this issue open incase explicit support _is_ needed, but if you know it's not, feel free to close this. I'm working on a test deploy my end as well - if I find that `import` is indeed implicitly universal, I'll loop back and close this as well.

Thanks for your help and quick turn around!

**Comment by greenpau** [comment]
@Matchlighter , I will open an issue in caddyserver for this. Will keep you posted here.

**Comment by greenpau** [comment]
@Matchlighter , see https://github.com/caddyserver/caddy/issues/4559#issuecomment-1030148870 
Looks like it is possible to do.

**Comment by greenpau** [comment]
@Matchlighter , just tested injecting default portal links and it worked just fine.

```
(defaultPortalLinks) {
        links {
                "API Metadata" /api/metadata icon "las la-star"
                "AuthDB" /authdb/ icon "las la-cog"
                "Cypress Videos" /videos/ icon "las la-photo-video"
                "My Website" https://assetq.myfiosgateway.com:8443/ icon "las la-star"
                "My Identity" "/whoami" icon "las la-user"
        }
}

{
        http_port 8080
        https_port 8443
        debug

        order authenticate before respond
        order authorize before basicauth

        security {
                authentication portal myportal {
                        crypto default token lifetime 3600
                        crypto key sign-verify {env.JWT_SHARED_KEY}
                        backend local {env.HOME}/.local/caddy/users.json local
                        cookie domain myfiosgateway.com
                        ui {
                                import defaultPortalLinks
                                #links {
                                #       "API Metadata" /api/metadata icon "las la-star"
                                #       "AuthDB" /authdb/ icon "las la-cog"
                                #    "Cypress Videos" /videos/ icon "las la-photo-video"
                                #               "My Website" https://assetq.myfiosgateway.com:8443/ icon "las la-star"
                                #       "My Identity" "/whoami" icon "las la-user"
                                #}
                                password_recovery_enabled yes
                        }
```

**Comment by greenpau** [comment]
@Matchlighter , next ...

Separated `portal` config into a separate file `~/tmp/authp/authdb/portal1.include`. The config includes `defaultPortalLinks` snippet.

```
        authentication portal myportal {
            crypto default token lifetime 3600
            crypto key sign-verify {env.JWT_SHARED_KEY}
            backend local {env.HOME}/.local/caddy/users.json local
            cookie domain myfiosgateway.com
            ui {
                import defaultPortalLinks
                password_recovery_enabled yes
            }
            transform user {
                match origin local
                action add role authp/user
                ui link "Portal Settings" /settings icon "las la-cog"
            }
            transform user {
                match origin local
                match sub webadmin
                action add name "Paul Greenberg"
            }
            transform user {
                match origin local
                match sub webadmin1
                action add picture "https://avatars.githubusercontent.com/u/3826416?v=4" as string
            }
        }

```

The "main" Caddyfile now references the portal.

```
(defaultPortalLinks) {
        links {
                "API Metadata" /api/metadata icon "las la-star"
                "AuthDB" /authdb/ icon "las la-cog"
                "Cypress Videos" /videos/ icon "las la-photo-video"
                "My Website" https://assetq.myfiosgateway.com:8443/ icon "las la-star"
                "My Identity" "/whoami" icon "las la-user"
        }
}

{
        http_port 8080
        https_port 8443
        debug

        order authenticate before respond
        order authorize before basicauth

        security {
        import /home/greenpau/tmp/authp/authdb/portal1.include
```

and it worked fine. 

You should be good to go.
