### ISSUE TITLE
What JWKS key types are supported in the generic OAuth2 backend?

### ISSUE THREAD

**Issue by irishismyname** [greenpau/caddy-security#48]
New to Caddy, new to OAuth & OIDC so brace yourselves. I'm trying to add OAuth/OIDC authentication to a site. I'm using [this](https://github.com/authp/authp.github.io/blob/main/assets/conf/oauth/generic/Caddyfile) config file as a reference. Things are going ok to start with, here's where (I think) I'm at:
1. It looks like Caddy is hitting my metadata_url and finding the jwks_uri field. 
2. Once it hits the jwks_uri, it appears to be reading the first key in the array whose kty (key type) is EC. 
3. Then I get this message and exit with code 1:

```provision security: backend configuration for "myportal" portal failed: failed to fetch jwt keys for OAuth 2.0 authorization server: invalid jwks key: unsupported key type EC for <my_key>```

where `<my_key>` is the EC key found at the jwks_uri. So my questions are:
1. Is the EC kty (keytype) supported?
2. If not, can I direct Caddy to use another key from the jwks_uri?
3. Have I misunderstood this completely?

**Comment by greenpau** [comment]
@irishismyname , thank you for opening the issue! What is the provider/product your are integrating with?

I will review code to see about the support for EC-based keys.

**Comment by irishismyname** [comment]
I really can't tell what product this is from my end, but I will do what I can to figure it out.

**Comment by greenpau** [comment]
> I really can't tell what product this is from my end, but I will do what I can to figure it out.

@irishismyname , please paste what you see in “ .well-known/openid-configuration”. It will help me understanding your config better.

Also, I will add support for EC-based keys this week.

**Comment by greenpau** [comment]
> provision security: backend configuration for "myportal" portal failed: failed to fetch jwt keys for OAuth 2.0 authorization server: invalid jwks key: unsupported key type EC for <my_key>

This specific error is coming from here:

https://github.com/greenpau/go-authcrunch/blob/2227dbfcebbb7c67bd5050724ef3ac9816f9476f/pkg/authn/backends/oauth2/configure.go#L467-L473

More specifically, it failed the following check. Which indeed does not support EC-based keys.

https://github.com/greenpau/go-authcrunch/blob/2227dbfcebbb7c67bd5050724ef3ac9816f9476f/pkg/authn/backends/oauth2/jwks.go#L45-L56

It is time to add `jwks_test.go` and support EC-based keys.

**Comment by greenpau** [comment]
@irishismyname , are you using `xcaddy` utility to compile Caddy? If so, then I would like you to try something.

**Comment by irishismyname** [comment]
> > I really can't tell what product this is from my end, but I will do what I can to figure it out.
> 
> @irishismyname , please paste what you see in “ .well-known/openid-configuration”. It will help me understanding your config better.
> 
> Also, I will add support for EC-based keys this week.

I removed some scopes and replaced the real uri with <uri> for readability, here's what we've got at " .well-known/openid-configuration":

```
{
    "issuer": "<uri>/fss",
    "authorization_endpoint": "<uri>/fss/as/authorization.oauth2",
    "token_endpoint": "<uri>/fss/as/token.oauth2",
    "revocation_endpoint": "<uri>/fss/as/revoke_token.oauth2",
    "userinfo_endpoint": "<uri>/fss/idp/userinfo.openid",
    "introspection_endpoint": "<uri>/fss/as/introspect.oauth2",
    "jwks_uri": "<uri>/fss/pf/JWKS",
    "registration_endpoint": "<uri>/fss/as/clients.oauth2",
    "ping_revoked_sris_endpoint": "<uri>/fss/pf-ws/rest/sessionMgmt/revokedSris",
    "ping_session_management_sris_endpoint": "<uri>/fss/pf-ws/rest/sessionMgmt/sessions",
    "ping_session_management_users_endpoint": "<uri>/fss/pf-ws/rest/sessionMgmt/users",
    "ping_end_session_endpoint": "<uri>/fss/idp/startSLO.ping",
    "device_authorization_endpoint": "<uri>/fss/as/device_authz.oauth2",
    "scopes_supported": [ "api", "address", "openid", "phone",  "MFAuth" ],
    "claims_supported": [ "country", "employeetype", "firstname", ", lastname", "location", "mail", "state", "street", "sub", "title" ],
    "response_types_supported": [ "code", "token", "id_token", "code token", "code id_token", "token id_token", "code token id_token" ],
    "response_modes_supported": [ "fragment", "query", "form_post", "pi.flow" ],
    "grant_types_supported": [ "implicit", "authorization_code", "refresh_token", "password", "client_credentials" ],
    "subject_types_supported": [ "public", "pairwise" ],
    "id_token_signing_alg_values_supported": [ "none", "HS256", "HS384", "HS512", "RS256", "RS384", "RS512", "ES256", "ES384", "ES512", "PS256", "PS384", "PS512" ],
    "token_endpoint_auth_methods_supported": [ "client_secret_basic", "client_secret_post", "private_key_jwt" ],
    "token_endpoint_auth_signing_alg_values_supported":  [ "RS256", "RS384", "RS512", "ES256", "ES384", "ES512", "PS256", "PS384", "PS512" ],
    "claim_types_supported": [ "normal" ],
    "claims_parameter_supported": false,
    "request_parameter_supported": true,
    "request_uri_parameter_supported": false,
    "request_object_signing_alg_values_supported": [ "RS256", "RS384", "RS512", "ES256", "ES384", "ES512", "PS256", "PS384", "PS512" ],
    "id_token_encryption_alg_values_supported": [ "dir", "A128KW", "A192KW", "A256KW", "A128GCMKW", "A192GCMKW", "A256GCMKW", "ECDH-ES", "ECDH-ES+A128KW", "ECDH-ES+A192KW", "ECDH-ES+A256KW", "RSA-OAEP" ],
    "id_token_encryption_enc_values_supported": [ "A128CBC-HS256", "A192CBC-HS384", "A256CBC-HS512", "A128GCM", "A192GCM", "A256GCM" ],
    "pushed_authorization_request_endpoint": "<uri>/fss/as/par.oauth2",
    "require_pushed_authorization_requests": false,
    "backchannel_authentication_endpoint": "<uri>/fss/as/bc-auth.ciba",
    "backchannel_token_delivery_modes_supported": [ "poll", "ping" ],
    "backchannel_authentication_request_signing_alg_values_supported": [ "RS256", "RS384", "RS512", "ES256", "ES384", "ES512", "PS256", "PS384", "PS512" ],
    "backchannel_user_code_parameter_supported": false,
    "code_challenge_methods_supported": [ "plain", "S256" ]
  }
```

**Comment by irishismyname** [comment]
> @irishismyname , are you using `xcaddy` utility to compile Caddy? If so, then I would like you to try something.

Yes, I'm building it in a Windows Docker image starting with `caddy:builder-windowsservercore-1809`  and `--with github.com/greenpau/caddy-security` and copying over caddy.exe from the builder to `caddy:2.4.6-windowsservercore-1809`.

**Comment by greenpau** [comment]
> Yes, I'm building it in a Windows Docker image starting wit

@irishismyname , great! Please do the following. In your Dockerfile add the following `--with` line.

```
    --with github.com/greenpau/go-authcrunch@c42d9cae65c8bab5b047a80ece6b9d6b3b083ea6
```

e.g.

```

RUN xcaddy build \
    --with github.com/greenpau/caddy-security \
    --with github.com/greenpau/caddy-trace \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/greenpau/go-authcrunch@c42d9cae65c8bab5b047a80ece6b9d6b3b083ea6
```

This would have extra debugging that I need. You will see slightly different errors and I need them.

P.S. If all goes well, I will have a fix by the EOD.

**Comment by greenpau** [comment]
@irishismyname , also based on the `.well-known/openid-configuration`, the product you use is PingIdentity (https://docs.pingidentity.com/)

**Comment by irishismyname** [comment]
The new error is:
```
provision security: backend configuration for "myportal" portal failed:
failed to fetch jwt keys for OAuth 2.0 authorization server: 
invalid jwks key: jwks key "<kid>" type "EC" processing not implemented: &{  <kid> EC  sig  P-521 <x> <y>  <nil>}
```

where `<kid>`, `<x>`, `<y>` are the values from the 1st element of the `keys` array from "fss/pf/JWKS". `<nil>` was actually in the error message.

**Comment by greenpau** [comment]
@irishismyname , this is great! Exactly what I expected. Will bake a patch and will ask you to retest.

**Comment by greenpau** [comment]
@irishismyname , please try this one and report back.

```
--with github.com/greenpau/go-authcrunch@b2a08bdcc877240e9664fa1ec3dfec888f63e140
```

Separately, could you please share your backend config? I think I will create a [shortcut](https://authp.github.io/docs/authenticate/misc#shortcuts) for `pingidentity`.

**Comment by irishismyname** [comment]
Rebuilding using `--with github.com/greenpau/go-authcrunch@b2a08bdcc877240e9664fa1ec3dfec888f63e140` and running yielded a new message:
```
backend configuration for "myportal" portal failed: 
failed to fetch jwt keys for OAuth 2.0 authorization server: 
invalid jwks key: jwks unsupported key usage enc <kid>
```

where `<kid>` is another entry from the `fss/pf/JWKS` endpoint:
```
{
      "kty": "EC",
      "kid": "<kid>",
      "use": "enc",
      "x": "<x-value>",
      "y": "<y-value>",
      "crv": "P-521"
    }
```
`<kid>` is the same as above and `<x-value>` and `<y-value>` were 88 character strings.

**Comment by greenpau** [comment]
@irishismyname , i think they are violating the RFC. Will send a new commit in a few hours for you to try.

**Comment by greenpau** [comment]
@irishismyname , please try `2dcbf8ee00a40eaff34338d5e02e3e138da19861` and report back.

**Comment by irishismyname** [comment]
`successfully configured OAuth 2.0 backend","provider":"generic"`🎉! Once have have a working, coherant backend config I will post it.

**Comment by greenpau** [comment]
> Once have have a working, coherant backend config I will post it.

@irishismyname , please keep me posted. i am here to help 👍

**Comment by irishismyname** [comment]
> `successfully configured OAuth 2.0 backend","provider":"generic"`🎉! Once have have a working, coherant backend config I will post it.

I should have read/posted more of this message 😑. I got to the login screen and noticed that the `client_id` parameter in the redirect was reading `ERROR_REPLACEMENT`. Looking closer at the logs I can see:
`:"successfully configured OAuth 2.0 backend","provider":"generic","client_id":"ERROR_REPLACEMENT"`

It's not *entirely* clear that this isn't my doing, so here's the portal config I'm using:
```
authentication portal myportal {
	crypto default token lifetime 3600
	crypto key sign-verify {"<my_key>"}
	backends {
		generic_oauth2_backend {
			method oauth2
			realm generic
			provider generic
			client_id {"<my_client_id>"}
			client_secret {"<my_client_secret>"}
			scopes openid
			base_auth_url <uri>/fss/as/authorization.oauth2
			metadata_url <uri>/fss/.well-known/openid-configuration
		}
	}
... (abbreviated)
}
```

where `<my_key>` is essentially a random string right now, `<my_client_id>` is an tested/working OAuth client ID, `<my_client_secret>` is the corresponding secret, and `<uri>` is the authorization server.

I'm using [this](https://github.com/authp/authp.github.io/blob/main/assets/conf/oauth/generic/Caddyfile) as a reference for the config file, but I've used an /auth* route instead of the auth.hostname.

**Comment by greenpau** [comment]
@irishismyname , the “{env.GENERIC_CLIENT_ID}” is the Caddy thing that says replace the “ {env.GENERIC_CLIENT_ID}” with the value of GENERIC_CLIENT_ID environment variable. If you have no env variables, it will come out blank. Are you setting the environment variables for your “env.*” placeholders?

Alternatively, instead of the “{env.GENERIC_CLIENT_ID}”, you could just type in the value of whatever that is.

**Comment by greenpau** [comment]
@irishismyname , i.e. don’t use curly brackets, unless you are using Caddy placeholders https://caddyserver.com/docs/caddyfile/concepts#placeholders

**Comment by irishismyname** [comment]
I think we're at the end of this particular quesiton/issue, but I still have some ground to cover. I'm at a point where I'm getting `"failed validating OAuth 2.0 access token: OAuth 2.0 id_token email claim not found"`. When I decode the JWT from the logs I get something like:
```
{
  "sub": "<username>",
  "aud": "<client_id>",
  "jti": "<22-characters>",
  "iss": "<uri>",
  "iat": 1644594666,
  "exp": 1644594966,
  "acr": "urn:oasis:names:tc:SAML:2.0:ac:classes:Telephony",
  "auth_time": 1644591362,
  "nonce": "<32-characters>"
}
```

I'm going to spend some more time trying to sort myself and my config file out, should I create a new issue or continue on this one?

**Comment by greenpau** [comment]
> I'm going to spend some more time trying to sort myself and my config file out, should I create a new issue or continue on this one?

@irishismyname , let's stay in this issue.

> id_token email claim not found

The `id_token` is a required field in the `generic` provider. Unfortunately, there is no Caddyfile directive to set custom `requiredTokenFields` (e.g. how it is done with Facebook).

https://github.com/greenpau/go-authcrunch/blob/c42d9cae65c8bab5b047a80ece6b9d6b3b083ea6/pkg/authn/backends/oauth2/configure.go#L244-L257

Over the weekend, I will add the Caddyfile directive for you to just set `access_token` as the only required token.

**Comment by irishismyname** [comment]
Do you suspect this is a nuance of PingID or something the auth server provider has configured?

**Comment by greenpau** [comment]
> Do you suspect this is a nuance of PingID or something the auth server provider has configured?

@irishismyname , it is a nuance of PingID. There a a few "switches" at play here (as you can see with FB). I think the "id_token" is the one I did not automate.

That's why I have defined, non-generic provider.

**Comment by greenpau** [comment]
@irishismyname , once I release, please add the following configuration directive to your `generic_oauth2_backend`:

```
generic_oauth2_backend {
  required_token_fields access_token
}
```

That would make the presence of `id_token` not required.

Also, if you have an instance of PingID tha you could share with me, then I will get it working faster 😄

**Comment by greenpau** [comment]
@irishismyname , https://github.com/greenpau/caddy-security/releases/tag/v1.0.15 is ready for you 😄

**Comment by irishismyname** [comment]
I rebuilt with the latest release

**Comment by greenpau** [comment]
@irishismyname , what is your current config?

**Comment by irishismyname** [comment]
```
authentication portal myportal {
	crypto default token lifetime 3600
	crypto key sign-verify "<random-string>"
	backends {
		generic_oauth2_backend {
			method oauth2
			realm generic
			provider generic
			required_token_fields access_token
			client_id "<client-id>"
			client_secret "<client-secret>"
			scopes openid
			base_auth_url <uri>/fss/as/authorization.oauth2
			metadata_url <uri>/fss/.well-known/openid-configuration
		}
	}
```

```
authorization policy mypolicy {
	set auth url <my-uri>/auth
	crypto key verify "<random-string-from-above>"
	allow roles authp/admin authp/user
	validate bearer header
	inject headers with claims
}
```

**Comment by greenpau** [comment]
> and a header that looks more promising

This is the state you want to be in. 

The `access_token` below is used to make a follow up call to fetch additional information from the PingID.

```
{
  "access_token": "<28-characters>",
  "refresh_token": "<42-characters>",
  "token_type": "Bearer",
  "expires_in": 7199
}
```

Unfortunately, I don't have access to an instance of PingID. However, what you need requires creating a function similar to the one used for Facebook, i.e. `fetchFacebookAccessToken`.

https://github.com/greenpau/go-authcrunch/blob/45670eee4fd8cf22070b0dc3365153a1ecace856/pkg/authn/backends/oauth2/authenticate.go#L97-L101

At the moment, you have 2 options:

1. Provision PingID instance for me to test it
2. DIY by following https://github.com/greenpau/caddy-security/blob/main/CONTRIBUTING.md#development-environment

**Comment by greenpau** [comment]
@irishismyname , I tried registering for a free demo account with PingID, but they don't provide it for personal addresses.

**Comment by greenpau** [comment]
> I'm pursuing both options. I'm going to see if we can get some support from PingID too.

@irishismyname , here, all the changes need to happen in `caddy-security`. I think your PingID is working as expected.

**Comment by irishismyname** [comment]
This problem may just be rooted in my lack of experience with OpenID. I'm finding that the JWT that's being returned when I use the `openid` scope:

## Header
```
{
  "alg": "RS256",
  "kid": "<27-characters>"
}
```

## Payload/Claims
```
{
  "sub": "<username>",
  "aud": "<client_id>",
  "jti": "<22-characters>",
  "iss": "<uri>",
  "iat": 1644594666,
  "exp": 1644594966,
  "acr": "urn:oasis:names:tc:SAML:2.0:ac:classes:Telephony",
  "auth_time": 1644591362,
  "nonce": "<32-characters>"
}
```
might be a valid OpenID response and I need to use some part of this to request the user's info from yet another endpoint. Still researching that, hopefully will find an answer shortly.

**Comment by greenpau** [comment]
> This problem may just be rooted in my lack of experience with OpenID. 

@irishismyname , the issues here is no longer OpenID. Rather, it is a specific PingID API to pull user info, i.e. `    "userinfo_endpoint": "<uri>/fss/idp/userinfo.openid",`. The `caddy-security` does not implement it.

You are getting `access_token` from PingID. Now, you need to take the `access_token` and extract user info, e.g. name and email, roles, etc. 

I've seen implementation that send email address as part of the response containing the `access_token`. The PingID does not do that.

**Comment by irishismyname** [comment]
The log entry right before the "Authentication Failed" message has the access and id_tokens:
```
{"level":"debug","ts":1644865284.7817552,"logger":"security","msg":"received OAuth 2.0 authorization server access token","request_id":"<request-id>","token":{"access_token":"<access-token>","expires_in":7199,"id_token":"<id-token>","token_type":"Bearer"}}
```

I took that access token and posted to `<uri>/fss/idp/userinfo.openid`. This endpoint was listed as `userinfo_endpoint` at the uri from the metadata_url in the Caddyfile. The user info came back as expected:
```
{
    "sub": "<username>",
    "country": "US",
    "firstname": "<firstname>",
    "phonenumber": "<phone number>",
    ... (etc)
    "email": "<email-address>",
   ... (etc)
}
```

Is this the same `email` field from the message `"error":"failed validating OAuth 2.0 access token: OAuth 2.0 id_token email claim not found"`?

**Comment by greenpau** [comment]
> "access_token":"<access-token>","expires_in":7199,"id_token":"<id-token>","token_type":"Bearer"

The `id_token` and `access_token` are present. 

> Is this the same email field from the message "error":"failed validating OAuth 2.0 access token: OAuth 2.0 id_token email claim not found"?

@irishismyname , idk. Probably not, because it would not browse to `/fss/idp/userinfo.openid`.

**Comment by greenpau** [comment]
@irishismyname , I need to see the entire exchange. If I don't have access to PingID instance, I can't really help.

**Comment by irishismyname** [comment]
> @irishismyname , I need to see the entire exchange. If I don't have access to PingID instance, I can't really help.

Understood, I think I have something spun up that you can use. Do you want to send me your email address privately or can I find it somewhere in your profile?

**Comment by greenpau** [comment]
The Caddyfile for the integration is here: https://github.com/authp/authp.github.io/blob/main/assets/conf/oauth/pingid/Caddyfile

Screenshots: https://authp.github.io/docs/authenticate/oauth/backend-oauth2-0010-pingid

Currently, only the Implicit Grant Type works. The authorization code does not work due to something on Ping Identity side.

The Redirect URL should end with `authorization-code-js-callback` (not the usual `authorization-code-callback`) and Caddyfile must have `enable js callback` directive.
