### ISSUE TITLE
feature: Enable templates for existing claims when adding new claims in user transforms

### ISSUE THREAD

**Issue by MexHigh** [greenpau/caddy-security#54]
> A clear and concise description of what you want the system to do.

I want to add a custom claim containing a Matrix ID to the JWT token. A Matrix ID is composed like `@<username>:<server>`. I want to use a user transform that adds this new claim (as documented in https://authp.github.io/docs/authenticate/user-transforms#inject-custom-claims). This claim should contain the username of the logged in user, if he has the `matrix-admin` claim, so the user `sam` would have a new claim with the value of `@sam:matrix.example.org`.

Is there a way to use pre-existing claims (like "sub") or even the username of the logged in user in this `action add` directive (like in my example below) or do I have to add a user tranform for every user?

Thanks in advance!

> What are the Caddyfile directives that need to be added.

Add Caddyfile directive:

```
{
  security {
    authentication portal main {
      backend local /etc/caddy-auth/users.json local
      cookie domain <redacted>
      cookie lifetime 43200
      crypto default token name <redacted>
      crypto default token lifetime <redacted>
      enable source ip tracking
      ui {
        custom css path "/etc/caddy-auth/styles-overwrite.css"
        logo url <redacted>
        logo description <redacted>
        links {
          <all redacted>
        }
      }
      transform user {
        match origin local
        require mfa
        action add role authp/user
      }
      transform user {
        exact match role matrix-admin
        action add "matrix_id" "@{claim:sub}:matrix.example.org" as string    # <-- HERE
      }
    }
  }
}
```

**Comment by greenpau** [comment]
@MexHigh , thank you for the issue! 👍 This is great!

To replay, you want to use "substitution/replace" functionality in user transforms based on existing claims?

Side question, what is the `matrix_id`? Where is it used?

**Comment by MexHigh** [comment]
Yes a "substitution/replace" functionality would solve this. But access to the username of the logged in user would be great, too.

To answer your side question: If you use the Matrix server implementation Synapse, you can log in using the key that was used to sign a JWT and a claim inside it containing the Matrix ID (see https://matrix-org.github.io/synapse/latest/jwt.html). I want to build an admin dashboard for our Matrix infrastructure that allows admins to manage registration tokens in a web interface with the help of your plugin :+1:

**Comment by greenpau** [comment]
> Yes a "substitution/replace" functionality would solve this. But access to the username of the logged in user would be great, too.

@MexHigh , 👍 Sounds good! Will take a look at it over the weekend.

**Comment by greenpau** [comment]
@MexHigh , here is test case I will be solving:

```

**Comment by greenpau** [comment]
@MexHigh , how is your Golang? Are you still a college/university student?

**Comment by greenpau** [comment]
Here are some of the things one could do:

Add `email` claim based on `sub` and `realm` claims:

```
  action add email {claims.sub}@{claims.realm}
```

Add multiple `roles` claim based on `realm` claim:

```
  action add roles {claims.realm}/admin {claims.realm}/user
```

Add custom `matrix_id` claim based on `sub` claim:

```
  action add matrix_id @{claims.sub}:matrix.foo.bar as string
```

A variant of the above with the addition of `email` claim:

```
  action add matrix_id @{claims.sub}:{claims.email}:matrix.foo.bar
```

**Comment by greenpau** [comment]
@MexHigh , you are all set! I will try releasing this weekend. However, if you want to try this feature right now, you could add the 
following to your `xcaddy` build:

```
--with github.com/greenpau/go-authcrunch@8295d6a26ed56f25be75fd89649a9929c0f50899
```

**Comment by greenpau** [comment]
> how is your Golang? Are you still a college/university student?

@MexHigh , if you are. I highly recommend you becoming mentee at https://mentorship.lfx.linuxfoundation.org/participate/mentee

**Comment by MexHigh** [comment]
> @MexHigh , you are all set! I will try releasing this weekend.

Thank you very much. I already tried it today using your instructions and it works as intended.

<br>

> > how is your Golang? Are you still a college/university student?
> 
> @MexHigh , if you are. I highly recommend you becoming mentee at https://mentorship.lfx.linuxfoundation.org/participate/mentee

Yes, I'm currently studying Enterprise and IT-Security but Golang is not part of the study program, sadly. I tought it myself though. I will take a look at the mentorship, thanks for sharing it.
