### ISSUE TITLE
breakfix: User registration successful, but no entry added to JSON file

### ISSUE THREAD

**Issue by dczysz** [greenpau/caddy-security#57]
**Describe the issue**

I'm doing some simple testing before migrating to this new plugin and can't seem to get user registration to work.  I'm not sure if it's an actual bug or if I'm just not not configuring it correctly.  It appears to work fine, but nothing gets populated in `registrations_db.json`.

**Configuration**

Paste full `Caddyfile` below:

```
{
	debug
	local_certs
	
	security {
		authentication portal myportal {
			crypto default token lifetime 3600
			crypto key sign-verify AnExampleSecretString123
			backend local ./users.json local
			registration {
				dropbox ./registrations_db.json
				title "User Registration"
			}
		}

		authorization policy mypolicy {
			set auth url /auth
			crypto key verify AnExampleSecretString123
			allow roles authp/admin authp/user
		}
	}
}

https:// {
	tls internal {
		on_demand
	}

	route /auth* {
		authenticate * with myportal
	}

	route /* {
		authorize with mypolicy
		reverse_proxy http://localhost:3000
	}
}
```

**Version Information**

Provide output of `caddy list-modules -versions | grep git` below:

Nothing for `git`, so these are all the non-standard modules:

```
http.authentication.providers.authorizer v1.0.11
http.handlers.authenticator v1.0.11
http.handlers.trace v1.1.8
security v1.0.11

  Non-standard modules: 4
```

**Expected behavior**

I'm expecting an entry to appear in the `users` array in `registrations_db.json`.  I noticed there wasn't even an empty `"users": []` entry in the file, but adding that didn't seem to make a difference anyway.

**Additional context**

When looking at the logs (as well as the "Thank You!" page) it seems like everything is working fine;

```
2022/02/21 19:27:36.848 ←[35mDEBUG←[0m  security        Created registration cache entry        {"session_id": "ojrli3bKBWJyhkYDDr335TY7Y5jyX9ya3ZkssVW", "request_id": "2b71e6ee-9346-42b9-b03d-c286b6aa8dc8", "registration_id": "AC0YbamCUGDy6Ey0WagrjZobS1X0qUFew1yZzKbFBeWqFVjYwswoQHtwS6fYjlcUYwWHedvHhtJ9bD5yEEnna6NN5vsEd4i"}
2022/02/21 19:27:36.849 ←[34mINFO←[0m   security        Successful user registration    {"session_id": "ojrli3bKBWJyhkYDDr335TY7Y5jyX9ya3ZkssVW", "request_id": "2b71e6ee-9346-42b9-b03d-c286b6aa8dc8", "username": "test", "email": "test@localdomain.local"}
```

I'm guessing this won't help much since it should just be the default template, but this is my `registrations_db.json` after a seemingly successful registration.

```json
{
  "version": "1.0.12",
  "policy": {
    "password": {
      "keep_versions": 10,
      "min_length": 8,
      "max_length": 128,
      "require_uppercase": false,
      "require_lowercase": false,
      "require_number": false,
      "require_non_alpha_numeric": false,
      "block_reuse": false,
      "block_password_change": false
    },
    "user": {
      "min_length": 3,
      "max_length": 50,
      "allow_non_alpha_numeric": false,
      "allow_uppercase": false
    }
  },
  "revision": 1,
  "last_modified": "2022-02-21T19:10:15.8941984Z"
}
```

**Comment by greenpau** [comment]
@dczysz , for the user registration to work, you need adding email provider.

Please see this config: https://github.com/authp/authp.github.io/blob/main/assets/conf/local/registration/Caddyfile

and an example of GMail SMTP setup: https://github.com/greenpau/caddy-security/issues/50#issuecomment-1037420658

**Comment by dczysz** [comment]
Ah ok, I figured this probably wouldn't work without an actual email setup forever.  Thanks.

**Comment by greenpau** [comment]
@dczysz , fyi, I am working on the API that would allow all the things you guys asked for in re user management.

First, this CLI would allow you to perform user management: https://github.com/greenpau/go-authcrunch/tree/main/cmd/authdbctl#authdb-management-client
Currently, it (partially) does `connect`.

Next step, would be adding user management.

**Comment by greenpau** [comment]
@dczysz , please watch https://github.com/greenpau/caddy-security/issues/16

**Comment by dczysz** [comment]
Thanks for the CLI link! Hadn't seen that before, so I'll definitely be trying that out.

> @dczysz , please watch #16
Will do, glad to see a specific issue for it.  Can't wait to replace our hacky solution!

Thanks again for all the help, Paul
