### ISSUE TITLE
question: Possible to change JWT cookie name?

### ISSUE THREAD

**Issue by jmfotokite** [greenpau/caddy-security#58]
Hi!

Is it possible to change the name of the cookie which contains the JWT?
By default, it is `access_token`. I tried `crypto default token name my_cookie_name`, but nothing changed.
I suspect that `access_token` is hardcoded in https://github.com/greenpau/go-authcrunch, is that right?

Background is that we'd like to smoothly transition from our old Caddy v1 installation, which used https://github.com/BTBurke/caddy-jwt with a custom cookie name.

Thanks!

**Comment by greenpau** [comment]
@jmfotokite , yes, it is possible. Please post the config you are working with. Preliminary you could do “crypto key token name foo”, but I want to see you connected the dots in your config. Also, please provide the version output from caddy.

**Comment by jmfotokite** [comment]
Wow, that was quick :scream: 

This is my config so far. It contains only the auth portal, the services which need auth are hosted somewhere else and will then use the authorize directive.

```
{
	admin off

	log {
		format json
	}

	order authenticate before respond
	security {
		authentication portal internal-auth-portal {
			crypto default token name internal_auth_jwt
			crypto default token lifetime 172800 # 48 h
			crypto key sign-verify {env.JWT_SHARED_KEY}

			backends {
				google_oauth2_backend {
					method oauth2
					realm google
					provider google
					client_id {env.GOOGLE_CLIENT_ID}.apps.googleusercontent.com
					client_secret {env.GOOGLE_CLIENT_SECRET}
					scopes email
				}
			}

			cookie domain internal.mydomain.com
			cookie lifetime 172800 # 48 h
			cookie insecure off
			cookie samesite strict

			ui {
				links {
					"My Identity" "/whoami" icon "las la-user"
				}
			}
		}
	}
}

http://:{$PORT} {
	bind 0.0.0.0
	log {
		format json
	}

	authenticate with internal-auth-portal
}
```

**Comment by jmfotokite** [comment]
I'll have a look at the video too.

**Comment by greenpau** [comment]
@jmfotokite , some preliminary thoughts on this.

```
http://:{$PORT} {
	bind 0.0.0.0
	log {
		format json
	}

	authenticate with internal-auth-portal
}
```

The portal might not work with HTTP, unless you `set cookie insecure on` ... you have it `on`  [link](https://authp.github.io/docs/authenticate/auth-cookie#intra-domain-cookies) 

Instead of `http://:{$PORT} {`, you can just do:

```
(logging) {
  	log {
		format json
	}
}

internal.mydomain.com {
  	import logging
	authenticate with internal-auth-portal
}
```

Instead of:

```
			backends {
				google_oauth2_backend {
					method oauth2
					realm google
					provider google
					client_id {env.GOOGLE_CLIENT_ID}.apps.googleusercontent.com
					client_secret {env.GOOGLE_CLIENT_SECRET}
					scopes email
				}
			}
```

You could do a [shortcut](https://authp.github.io/docs/authenticate/misc#shortcuts), unless you want to keep your scope to `email`:

```
backend google {env.GOOGLE_CLIENT_ID} {env.GOOGLE_CLIENT_SECRET}
```

https://github.com/greenpau/caddy-security/blob/7f0bac7999efd09f7f0c8c1b57115de276670ceb/caddyfile_authn_backend_shortcut.go#L46-L56

**Comment by greenpau** [comment]
@jmfotokite , also, I recommend having longer cookie (x+8h) lifetime than token (x) lifetime.

```
	security {
		authentication portal internal-auth-portal {
			crypto default token lifetime 172800 # 48 h
			cookie lifetime 172800 # 48 h
```

The “cookie lifetime” is the max lifetime of a cookie in a browser cache.

The “crypto key lifetime” is the lifetime of the JWT token inside the cookie.

When the token expires, the cookie carrying it is still “alive” and serves as a clue for a redirection.

**Comment by jmfotokite** [comment]
Thank you, that was very helpful!

* using `crypto key token name my_name` did the trick for the cookie name
* the `http://:{$PORT}` part is a bit misleading in my config, this is actually running on a managed container service which terminates HTTPS for us, so all fine
* I am using the shortcut now
* and I have extended the cookie life time

Again, thank you, I am blown away with how quickly and helpfully you answered! I am going to close this now, as my question is answered.

**Comment by greenpau** [comment]
@jmfotokite , enjoy! Please do not hesitate asking questions! See https://github.com/greenpau/caddy-security/issues/14#issue-1111599735
