### ISSUE TITLE
configure roles and bypass from site config

### ISSUE THREAD

**Issue by lbreitk** [greenpau/caddy-security#60]
First off, I really like the new configuration, I think it's much better.

But I liked being able to specify the role and bypass URLs within the site definition. Looks like now, you have to define policies in the global scope, and then attach the policies to the site. The problem is, this doesn't scale as well for us - we manage access by having a single role per site that we assign in LDAP and then grant that role access. This means, if we have 20 sites, that's 20 different policies that have to be defined. The best solution I can come up with at the moment, is to create a directory for policy sub-configs, and then import them into the main security configurations, but this means that for every site config, I'll have to *also* deploy a security config. I feel like there could be a better way that utilizes the best of both worlds.

**Comment by greenpau** [comment]
>  I feel like there could be a better way that utilizes the best of both worlds.

@lbreitk , another good question! 👍 I will try figuring out how allow override of changes at a handler level.

What are the settings that you need right now? Please provide Caddyfile snippet.

**Comment by greenpau** [comment]
> What are the settings that you need right now? 

@lbreitk , please provide Caddyfile snippets for the type of configuration you want.

**Comment by greenpau** [comment]
> This means, if we have 20 sites, that's 20 different policies that have to be defined.

@lbreitk , I would recommend using snippets **with args** to manage your configuration. Please see my explanation in https://github.com/greenpau/caddy-security/issues/69#issuecomment-1075722666

Additionally, you might find it helpful to use `labels`. See https://caddyserver.com/docs/caddyfile/patterns#redirect-www-subdomain

Note how creative you could get:

```
www.example-one.com, www.example-two.com {
	import authPolicy {labels.1}{labels.0}
}
```

Where `authPolicy` is a snippet with arguments.
