### ISSUE TITLE
{url} not parsing?

### ISSUE THREAD

**Issue by lbreitk** [greenpau/caddy-security#61]
**Describe the issue**

In previous versions I could pass the variable `{url}` to the "forbidden" URL. Now I get an `ERROR_REPLACEMENT` value instead

**Configuration**

```
authorization policy test {
  set auth url https://test-auth.<domain>
  set forbidden url "https://test-auth.<domain>/assets/403?referral={url}"
  crypto key <key>
  allow roles res-test-role
}
```

**Version Information**

```
v2.4.6
http.authentication.providers.authorizer v1.0.16
http.handlers.authenticator v1.0.16
http.handlers.teapot v0.0.2
security v1.0.16
```

**Expected behavior**

The URL the user was attempting to access to be displayed instead

**Additional context**

Previous Versions:
![image](https://user-images.githubusercontent.com/77999616/155420166-a58de7d0-c1e8-4c2d-8d1a-66cc6d33bf8e.png)

Current Version:
![image](https://user-images.githubusercontent.com/77999616/155420266-83d15c28-8c96-435e-aa98-2a66648dbff2.png)

**Comment by thermoscookies** [comment]
Having the same issue when trying to use {} with set auth url, it replaces it with ERROR_REPLACMENT
set auth url https://{host}/auth/

**Comment by greenpau** [comment]
@lbreitk , @thermoscookies , will try looking into it this weekend.

**Comment by greenpau** [comment]
> Having the same issue when trying to use {} with set auth url, it replaces it with ERROR_REPLACMENT
set auth url https://{host}/auth/

@thermoscookies, if it is the same host, just set it to “/auth/“

**Comment by greenpau** [comment]
>   set forbidden url "https://test-auth.<domain>/assets/403?referral={url}"

@lbreitk , I am having trouble finding the `{url}` placeholder [here](https://caddyserver.com/docs/caddyfile/concepts). Where did you get it?

**Comment by thermoscookies** [comment]
> 

I am using multiple domains, only 3 so easy enough to work with, but i end up having to have multiple policies. I changed back to auth.domain.name to make my Caddyfile cleaner. When I was using /auth it wouldnt work well because i use subdomains, so my auth url was domain1.com/auth, when i would go to wiki.domain1.com it would redirect to wiki.domain1.com/auth

I've worked around my issue using the following and it's working great so far but I could reduce that down to one if the {} would populate properly. Other than I'm happy with the switch over to caddy-security from auth-portal, great job!

`		authorization policy mypolicy {
			set auth url https://auth.domain1.com/
			crypto key verify 000
			allow roles authp/admin authp/user
		}
		authorization policy mypolicy2 {
			set auth url https://auth.domain2.com/
			crypto key verify 000
			allow roles authp/admin authp/user`

**Comment by greenpau** [comment]
> I am using multiple domains, 

@thermoscookies , please open a separate issue for this one and provide your current config. I will show you how to optimize your configuration via snippets with arguments.

**Comment by greenpau** [comment]
> set forbidden url "https://test-auth.<domain>/assets/403?referral={url}"

@lbreitk , I found where the `url` comes into play. 

https://github.com/greenpau/go-authcrunch/blob/ee3afe757838f11c33c871a4aa1ed9e1c8929be7/pkg/authz/authenticate.go#L172-L186

I confirmed this bug. It did not replace `{url}`. Will work on it right now.

**Comment by greenpau** [comment]
@lbreitk , the issue with `{url}` is now fixed in https://github.com/greenpau/caddy-security/releases/tag/v1.0.17

**Comment by lbreitk** [comment]
> @lbreitk , the issue with `{url}` is now fixed in https://github.com/greenpau/caddy-security/releases/tag/v1.0.17

Thanks so much for fixing this!
