### ISSUE TITLE
question: How can I access claims in http handlers?

### ISSUE THREAD

**Issue by simaotwx** [greenpau/caddy-security#66]
Say, I have configured the authentication portal and authorization which is working.

Now I want to use claims in handlers, e. g.:

```
example.org {
  respond "{http.authentication.providers.authorizer.claims.sub}"
}
```

Accessing example.org as authenticated user "foo" would respond with "foo".

**Comment by simaotwx** [comment]
I found out you can kind of do this by injecting headers and using the headers as values.
Not the best way to do this inside the Caddyfile but can certainly help in some situations.

**Comment by greenpau** [comment]
> Now I want to use claims in handlers, e. g.:

@simaotwx , the claims are populated here, inside Caddy user Metadata.

https://github.com/greenpau/caddy-security/blob/800f3878242fb043045e10ac1d92643783f8128b/plugin_authz.go#L120-L132

You also need `authorize` prior to the `respond`:

```
example.org {
  authorize ...
  respond "{http.authentication.providers.authorizer.claims.sub}"
}
```

Based on the code [here](https://github.com/caddyserver/caddy/blob/03b5debd958a324d5c00cc37f887130b0198e747/modules/caddyhttp/caddyauth/caddyauth.go#L91-L95), I suspect that you would need the following:

```
"http.auth.user."+k, v
```

i.e. 

```
"{http.auth.user.id}"
"{http.auth.user.claim_id}"
"{http.auth.user.sub}"
"{http.auth.user.email}"
"{http.auth.user.name}"
"{http.auth.user.roles}"
```

**Comment by greenpau** [comment]
@simaotwx , confirmed. It works.

![image](https://user-images.githubusercontent.com/3826416/159597859-e42c2fd6-cb2e-4edc-a0e6-9c34ac6ad70e.png)

The config:

```
    route /metadata* {
       authorize with admin_policy
       respond "{http.auth.user.id} {http.auth.user.roles}"
    }

```

**Comment by simaotwx** [comment]
Thank you very much, that's exactly what I needed!
