### ISSUE TITLE
feature: Ability to provide scopes from the request into the security backends

### ISSUE THREAD

**Issue by dbranco-sdc** [greenpau/caddy-security#70]
# WHY
Nowadays we have a use case where we can have different scopes based on certain user data. Since the scopes are fixed, we are forced to create different backends containing the specific scopes for the different flags from user data.

This also require the creation of different policies and routes to apply one or another set of scopes. The idea is to  have a directives to set scopes from the client request and relief configuration mess.

# Proposal

Support Caddyfile directive to set scopes:

```
{
  authorization policy POLICY_NAME {

            ...
            set scopes source <header | cookie | queryParam> <ContainerName>  
  }
}
```

**Comment by greenpau** [comment]
@dbranco-sdc , thank you for the issue! 👍 

After reading this, I don't think I am understanding the use case well. Here are some of my follow up questions.

What does `ContainerName` means here?

Say you implement `set scopes source cookie foo`, what happens on the "wire"? Do you expect the plugin to add something to the cookie?

How do this relate to "header injection"? https://authp.github.io/docs/authorize/headers#custom-headers

**Comment by dbranco-sdc** [comment]
@greenpau, thanks for your triage and quick answer!

The use case we had is the following:

In caddyfile:

```
# General config
{
    ...
    security {
        authentication portal customerAuth {
            ...

            backends {
                customer {
                    ...
                    realm customerRealm
                    scopes openid profile scope1
                }
                
                customer_with_flag1 {
                    ...
                    realm customerRealmWithFlag1
                    scopes openid profile scope1 scope2
                }
                
            }
        }

        authorization policy policy_customer {

            ...

            set auth url /auth/oauth2/customerRealm
        }
       
        authorization policy policy_customer_with_flag1 {
            ...
            set auth url /auth/oauth2/customerRealmWithFlag1
        }
        
    }
}

:8080 {

    ...

    @confirm_personal_data_with_flag1 {
        path /confirm-personal-data
        query flag1=true
    }

    route @confirm_personal_data_with_flag1 {
        authorize with policy_customer_with_flag1

        try_files {path} {file} /index.html
        file_server
    }

    @customer_protected_routes {
        path /confirm-personal-data
        ...
    }

    route @customer_protected_routes {
        authorize with customer

        try_files {path} {file} /index.html
        file_server
    }

    ...

    # No consent redirection

    @no_consent {
        path /auth/oauth2/customerRealm/authorization-code-callback
        path /auth/oauth2/customerRealmWithFlag1/authorization-code-callback
        query error=consent_required
    }

    route @no_consent {
        redir * /no-consent
    }

    # Auth provider config

    route /auth* {
        authenticate with customerAuth
    }
}
```

Now it was required that when we have some other info from the customer we need to require more scopes. So, we were forced to add backends with 2 other realms in case the flag2 is alone or with the flag1, 2 more authorizations, 2 more routes to ask for the flag2 query parameters....

As you can see the scopes force us to duplicate configuration when they should be pass from the requester. The idea is to have a way to pass those scopes into the backends. The proposal is to be able set them from the policies that are called from the route, so this policies can retrieve the values and pass it to the backends. 

Taking your example `set scopes source cookie foo` will read the cookie `foo` which should contains a list of scopes and pass it into the backend to add more scopes dynamically. So setting the scopes in this way we can remove all the backends and routes and configure only one, and then the client can specify which scope need or not.

You mentioned the header injection, but the scopes are not headers they are query params in the IDP request [auth-request](https://www.oauth.com/oauth2-servers/authorization/the-authorization-request/)

Hope this clarifies the use case.

**Comment by greenpau** [comment]
> As you can see the scopes force us to duplicate configuration when they should be pass from the requester. The idea is to have a way to pass those scopes into the backends. The proposal is to be able set them from the policies that are called from the route, so this policies can retrieve the values and pass it to the backends.

@dbranco-sdc , apologies for the late reply. I think I understand the use case here.

* How would you inject the cookie into the user?
* What is the logic for the determination of the right scope?

Generally speaking, the issue is that there is no identity prior to users' authentication ... Also, say with Github or Google, you define your application and associated scopes. A user will be prompted for all the associated scopes, not only the scopes the user passes in the request. How would you overcome the need for multiple Application definitions in OAuth Provider (and subsequently, the need to have multiple oauth2 endpoint in auth portal)?

**Comment by dbranco-sdc** [comment]
> > As you can see the scopes force us to duplicate configuration when they should be pass from the requester. The idea is to have a way to pass those scopes into the backends. The proposal is to be able set them from the policies that are called from the route, so this policies can retrieve the values and pass it to the backends.
> 
> @dbranco-sdc , apologies for the late reply. I think I understand the use case here.
> 
> * How would you inject the cookie into the user?
> * What is the logic for the determination of the right scope?
> 
> Generally speaking, the issue is that there is no identity prior to users' authentication ... Also, say with Github or Google, you define your application and associated scopes. A user will be prompted for all the associated scopes, not only the scopes the user passes in the request. How would you overcome the need for multiple Application definitions in OAuth Provider (and subsequently, the need to have multiple oauth2 endpoint in auth portal)?

Hello @greenpau,

About your first question, the client will be in charge of setting the cookie or query param, and it will be forwarded to the caddy-security plugin.

About the second question, the responsibility will be entirely from the client who knows what is the business logic behind to require one or another scope, there will not be any business logic in caddyfile at this point.

To complement your following thoughts, the idea is that the backend will have some base scopes defined, and if the queryParam or cookie has been provided to the policy, then this (the policy) will forward the provided scopes, and then the backend will merge it with its current scopes.

**Comment by greenpau** [comment]
> queryParam or cookie has been provided to the policy, then this (the policy) will forward the provided scopes, and then the backend will merge it with its current scopes

@dbranco-sdc , could try doing it with query parameters. It would be very similar to loginhint query parameters.

**Comment by dbranco-sdc** [comment]
This has been implemented into the main branch, with the following commits:

- https://github.com/greenpau/caddy-security/commit/c741828ab78829c1ac96400c3865a4faf948c35b
- https://github.com/greenpau/go-authcrunch/commit/1bd079281c0fb329cdc573a6ca87a10da04b1036
- https://github.com/authp/authp.github.io/commit/2660f96e3067a747c384933656696ff41c31b070

**Comment by greenpau** [comment]
@dbranco-sdc 👍
