### ISSUE TITLE
question: Unable to setup local + basic auth

### ISSUE THREAD

**Issue by srijan** [greenpau/caddy-security#71]
Hi.

I was trying to setup local auth which supports optional basic auth as well. (I think this is supported, but not sure).

Here's my Caddyfile (replaced my domain with example.com below)

```
{

  order authenticate before respond
  order authorize before basicauth

  security {

    authentication portal localportal {
      crypto default token lifetime 3600
      crypto key sign-verify {env.JWT_SHARED_KEY}
      backend local /config/users.json local
      cookie domain example.com
      transform user {
        match origin local
        action add role authp/user
      }
    }
    authorization policy users_policy {
      with basic auth realm local
      set auth url https://auth.example.com/
      allow roles authp/admin authp/user
      crypto key verify {env.JWT_SHARED_KEY}
      acl rule {
        comment allow users
        match role authp/user
        allow stop log info
      }
      acl rule {
        comment default deny
        match any
        deny log warn
      }
    }
  }
}

auth.example.com {
  route {
    authenticate with localportal
  }
}

example.com {
  handle_path /public/* {
    reverse_proxy http://127.0.0.1:12345
  }
  handle /private/* {
    authorize with users_policy
    reverse_proxy http://127.0.0.1:12346
  }
}

```

This is working as expected if I open example.com/private/ from my browser - it's redirecting to auth.example.com and redirecting back after successful authentication.

But, if I try using basic auth using `curl`, it's failing:

```
curl -I -u "user:pass" https://example.com/private/
HTTP/2 302 
location: https://auth.example.com/?redirect_url=https%3A%2F%2Fexample.com%2Fprivate%2F
server: Caddy
content-type: text/plain; charset=utf-8
content-length: 5
```

Caddy's log has this:
`{"level":"error","ts":1646933018.3283975,"logger":"http.handlers.authentication","msg":"auth provider returned error","provider":"authorizer","error":"user authorization failed: src_ip=<redacted>, src_conn_ip=<redacted>, reason: idp catalog: provider context does not registered"}`

I expected this to directly authorize the request without redirecting to the auth portal.

Is this something that's possible? Am I missing any steps?

Thanks.

**Comment by greenpau** [comment]
> {"level":"error","ts":1646933018.3283975,"logger":"http.handlers.authentication","msg":"auth provider returned error","provider":"authorizer","error":"user authorization failed: src_ip=<redacted>, src_conn_ip=<redacted>, reason: idp catalog: provider context does not registered"}

@srijan, thank you for the issue! 👍 

The error your are getting stems from `with basic auth realm local`. 

https://github.com/greenpau/go-authcrunch/blob/587eeac3858fd923b1a44da21c194dffb500ccf3/pkg/shared/idp/provider.go#L56-L64

Try changing it to just  `with basic auth`.

Side note, I recommend to change the route handling in this way.

```
example.com {
  route /private* {
    authorize with users_policy
    reverse_proxy http://127.0.0.1:12346
  }
  route {
    reverse_proxy http://127.0.0.1:12345
  }
}
```

Please test and reply back. I don't expect it to work, but I want to rule out `handle_path` directive.

**Comment by srijan** [comment]
> Try changing it to just `with basic auth`.

How would it know which realm backend to use?

Anyway, I tried the above change, also tried the route handling changes as you suggested, but same result and same error in the logs.

**Comment by greenpau** [comment]
> How would it know which realm backend to use?

@srijan , I will take a look at (and test) the code this week. Busy at work. 

Generally speaking, the realm is derived from `backend local /config/users.json local`.

**Comment by NilsOlavKvelvaneJohansen** [comment]
Hey again! I get the same problem with basic auth. I tried changing it to just `with basic auth` but I still get the same: 
`
1.6475936945092561e+09  debug   security        token validation error  {"session_id": "", "request_id": "e220eda4-4c4a-43aa-8e88-a6653ffc9d52", "error": "idp catalog: provider context does not registered"}"`Caddy log:

Thanks.

**Comment by greenpau** [comment]
@srijan , @NilsOlavKvelvaneJohansen , starting working on it now.

**Comment by greenpau** [comment]
FYI, found couple of issues:

1. API/Basic auth integration was not registering
2. The token issued by the API/Basic auth integration have `nbf` error: `Token is not valid yet`. This needs to be addresses with changes to `pkg/authn/idp_apikey_auth.go`.

Additionally, there will be a need to specify portal name, e.g. `localportal`

```
with basic auth context <PORTAL_NAME> realm <REALM_NAME>
with basic auth context localportal realm local
```

**Comment by greenpau** [comment]
@srijan , @NilsOlavKvelvaneJohansen , you should be good to go with https://github.com/greenpau/caddy-security/releases/tag/v1.0.18

**Comment by greenpau** [comment]
@srijan , @NilsOlavKvelvaneJohansen , FYI, I am changing syntax with next release:

```
with basic auth portal <PORTAL_NAME> realm <REALM_NAME>
with api key auth portal <PORTAL_NAME> realm <REALM_NAME>
```

https://github.com/authp/authp.github.io/issues/6
