### ISSUE TITLE
 Can't enable local authentication setup

### ISSUE THREAD

**Issue by agucova** [greenpau/caddy-security#72]
**Describe the issue**

Hi,

I'm trying to replicate https://github.com/authp/authp.github.io/blob/main/assets/conf/local/Caddyfile but I keep getting server timeouts on all authentication domains. 

This is caddy latest built from the page with caddy-security under Linux ARM64.

The logs themselves aren't really helpful, and seem completely normal.

My objective is to have an authentication domain (`lepton.agucova.dev`) and use it to authorize access to internal apps on other subdomains.

**Configuration**

The minimally reproducible example is something like:
```Caddyfile
{
	  security {
	      authentication portal myportal {
			  cookie domain agucova.dev
	          backend local {env.HOME}/.local/caddy/users.json local
	      }
	  }
}

lepton.agucova.dev {
    route {
        authenticate with myportal
    }
    tls {
        dns cloudflare REDACTED
    }
}
```

**Version Information**

Provide output of `caddy list-modules -versions | grep git` below:

No output.

**Expected behavior**

The auth portal should appear.

**Comment by greenpau** [comment]
No response.
