### ISSUE TITLE
Can't get local authentication to work 

### ISSUE THREAD

**Issue by dwaynelarose** [greenpau/caddy-security#74]
I am just trying to understand how this plug in works but I am not having much luck. 
I am using caddy-security wrapped up in a dockerfile.

My normal Caddyfile that forwards user to my Guacamole server with this setup but my updated Caddyfile does not work 
  
**Configuration**
Updated Caddyfile
```
{
    #Ports to open for caddy  
    http_port 80
    https_port 443

    debug

    security {
      authorization policy mypolicy {
        set auth url https://auth.mydomain.org/
        
        #This sets the local of the user database file and will be auto created
        
        backend local /data/.users/users.json local
        
        #This sets the domain used for the auth cookie 
        cookie domain mydomain.org

        ui {
                #After you authenticate, the links below will show up on the portal
                links {
                        "My Website" https://mydomain.org icon "las la-star"
                        "My Identity" "/whoami" icon "las la-user"
                        "Portal Settings" /settings icon "las la-cog"
                }
      }
    }
  }

  auth.mydomain.org:443 {
    authenticate * with myportal
  }

  mydomain.org:443 {
    
    route {
        authenticate with myportal
    }

    reverse_proxy 172.16.15.7:8228
    redir / /guacamole/ 308
  }
```

```
/srv # caddy list-modules -versions | grep auth
http.authentication.hashes.bcrypt v2.4.6
http.authentication.hashes.scrypt v2.4.6
http.authentication.providers.http_basic v2.4.6
http.handlers.authentication v2.4.6
http.authentication.providers.authorizer v1.0.17
http.handlers.authenticator v1.0.17
/srv # 
```
**Version Information**
/srv # caddy version 
v2.4.6 h1:HGkGICFGvyrodcqOOclHKfvJC0qTU7vny/7FhYp9hNw=
/srv # 

Provide output of `caddy list-modules -versions | grep git` below:
```
No output 
```

**Expected behavior**

I was hoping to get the portal page to authenticate when i go to mydomain.org right now I get nothing 
My logs are seen below 

Thanks for your help.

[caddylogs.txt](https://github.com/greenpau/caddy-security/files/8308417/caddylogs.txt)

**Comment by greenpau** [comment]
@dwaynelarose , thank you for the issue! Did you have a chance to see how your config differs from a sample https://github.com/authp/authp.github.io/blob/main/assets/conf/local/Caddyfile

if not, please give it a try. If yes, I will draft a sample tomorrow. (Currently on mobile)

**Comment by jpbaril** [comment]
The route should instead have some "authorize" directive, which in turn would bring the user to an url that would use some portal definition.

**Comment by dwaynelarose** [comment]
I think I got it working with the following:


{
	http_port 80
	https_port 443
	debug

	order authenticate before respond
	order authenticate before redir

	security {
		authentication portal myportal {
			crypto default token lifetime 3600
			backend local /data/users.json local
			cookie domain mydomain.org
			ui {
				links {
					"Remote Access" https://mydomain.org/guacamole icon "las la-star"
                    "BT" https://bt.mydomain.org icon "las la-star"
					"My Identity" "/whoami" icon "las la-user"
				}
				password_recovery_enabled no
			}
			transform user {
				match origin local
				action add role authp/user
				ui link "Portal Settings" /settings icon "las la-cog"
			}
			
		}

		authorization policy guests_policy {
			# disable auth redirect
			set auth url https://auth.mydomain.org
			allow roles authp/admin authp/user
			acl rule {
				comment allow guests only
				match role guest authp/guest
				allow stop log info
			}
			acl rule {
				comment default deny
				match any
				deny log warn
			}
		}

		authorization policy users_policy {
			set auth url https://auth.mydomain.org
			allow roles authp/admin authp/user
			acl rule {
				comment allow users
				match role authp/user
				allow stop log info
			}
			acl rule {
				comment default deny
				match any
				deny log warn
			}
		}

		authorization policy admins_policy {
			set auth url https://auth.mydomain.org
			allow roles authp/admin authp/user
			acl rule {
				comment allow users
				match role authp/user
				allow stop log info
			}
			acl rule {
				comment default deny
				match any
				deny log warn
			}
		}
	}
}


auth.mydomain.org:443 {
	route {
		authenticate with myportal
	}
}

bt.mydomain.org:443 {

	route {
		authorize with users_policy
		reverse_proxy 172.16.15.8:8888
	}
}


mydomain.org:443 {
	route /guests* {
		authorize with guests_policy
		respond * "assetq - guests only" 200
	}

	route /users* {
		authorize with users_policy
		respond * "assetq - users" 200
	}

	route /admins* {
		authorize with admins_policy
		respond * "assetq - admins" 200
	}

	route {
		authorize with users_policy
        redir / /guacamole/ 308
		reverse_proxy 172.16.15.7:8228
	}
}
Any attempts to go to https://bt.mydomain.org and https://mydomain.org get pushed to confirm ID first

I'm pretty sure I can clear the guest users policy 
Now just need help to copy a user in the users.json. Where does one user start and the other one end?
I THINK I copy everything after:

 "users": [ 

and before the last ] then  after the last ] put:

,[

Dump the copied user here and 

] to close before the last } 

Thanks for the great software.. going to rate it now!

**Comment by greenpau** [comment]
> I think I got it working with the following:

@dwaynelarose , awesome! 👍 Here are some additional things.

* Fix your `order` directives. Here is what you would need.

```
order authenticate before respond
order authorize before basicauth
```

* You don't need the below if you are using default ports:

```
http_port 80
https_port 443
```

* If auth portal is the only route, you replace this:

```
auth.mydomain.org:443 {
	route {
		authenticate with myportal
	}
}
```

with:

```
auth.mydomain.org {
  authenticate with myportal
}
```

* Same idea is the a single route and authorization. (this probably did not work without `route`, b/c you were missing `order authorize before basicauth`)

```
bt.mydomain.org:443 {
  authorize with users_policy
  reverse_proxy 172.16.15.8:8888
}
```

* I would recommend not to do anything with the ordering of `redir` and create two separate routes:

```
route /guacamole* {
  authorize with users_policy
  reverse_proxy 172.16.15.7:8228
}

route {
  redir / /guacamole/ 308
}
```

> Now just need help to copy a user in the users.json. 

Please review how JSON documents are structured. 

You would know things worked out for you when you the following command succeeds:

```
cat users.json | jq
```
