### ISSUE TITLE
question: how can I build for arm64 

### ISSUE THREAD

**Issue by ippocratis** [greenpau/caddy-security#76]
> A clear and concise description of what you want to accomplish.

I'm running caddy on a raspberry pi400 running manjaro arm. 
I'd love to try the 2fa feature.
Is the an arm64 version? 
If not how can I build it?

**Comment by greenpau** [comment]
@ippocratis , thank you for the question 👍 

The `caddy` (together with its plugins) is build with [`xcaddy`](https://github.com/caddyserver/xcaddy).

Step 1: Build `xcaddy`:

```
go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
```

Step 2: Build `caddy` with the plugins for arm using `GOOS` and `GOARCH` env variables:

```
GOOS=linux GOARCH=arm64 xcaddy build \
    --with github.com/greenpau/caddy-security \
    --with github.com/greenpau/caddy-trace \
    --with github.com/caddy-dns/cloudflare
```
