### ISSUE TITLE
question: skip kid ckeck option?

### ISSUE THREAD

**Issue by teodorescuserban** [greenpau/caddy-security#77]
> A clear and concise description of what you want to accomplish.

I am trying to authenticate to an (apparently) broken oauth2 server which does not provide the `kid` in the `id_token`.

The error in the logs is this:

```
{"level":"warn","ts":1647959353.70759,"logger":"security","msg":"Authentication failed","session_id":"lbcuPQRrdw8Sdwi7jCuohVyiLsViBe8wXoPGY0zsGrylm","request_id":"759dd92c-3464-4568-9dc8-6e90ffd6b93b","error":"failed validating OAuth 2.0 access token: OAuth 2.0 failed to parse id_token: OAuth 2.0 kid not found in id_token"}
```

I have verified the `id_token` (by enabling debug in the caddy config), it does not contain the `kid` - see the `id_token` header below:
```
{
  "typ": "JWT",
  "alg": "RS256"
}
```

PS: Github and gitlab configurations are working just fine, but I do get the `kid` in their `id_token`.
PPS: I also had a look on #48 and tried `required_token_fields access_token` with no luck. I get the same error.

**Comment by greenpau** [comment]
@teodorescuserban , thank you for the issue! 👍 

> oauth2 server

* What is the server? 
* Please enabled debug and paste the content of the token you receive. If it is not in the logs, enable https://github.com/greenpau/caddy-trace plugin and get it from the trace logs.

**Comment by teodorescuserban** [comment]
@greenpau, thank you for having a look at this!

- the server is a drupal with oauth2 server module (see [here](https://www.drupal.org/node/1938218)); it's pretty old but I have no control over it; it does have at least an issue about the kid not being added - see [here](https://github.com/bshaffer/oauth2-server-php/issues?q=is%3Aissue+kid) and [here](https://www.drupal.org/project/issues/oauth2_server?text=kid&status=Open&priorities=All&categories=All&version=All&component=All)
- the entire log line is pasted below (domain changed).

```
caddy_1  | {"level":"debug","ts":1647961278.1857638,"logger":"security","msg":"OAuth 2.0 access token response received","body":"eyJhY2Nlc3NfdG9rZW4iOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpTVXpJMU5pSjkuZXlKcFpDSTZJamczTmpVd05USTRZVEk1WmpkalpUQTBNR1V6TldJM09XTTRPVFU1T1RjNFl6SmhOemxqTnpRaUxDSnFkR2tpT2lJNE56WTFNRFV5T0dFeU9XWTNZMlV3TkRCbE16VmlOemxqT0RrMU9UazNPR015WVRjNVl6YzBJaXdpYVhOeklqb2lhSFIwY0hNNlhDOWNMMlJsZGk1aGRYUm9MbUZvWTI5dWRTNXZjbWRjTHlJc0ltRjFaQ0k2SW1OaFpHUjVJaXdpYzNWaUlqb2lNeUlzSW1WNGNDSTZNVFkwTnprMk5EZzNPQ3dpYVdGMElqb3hOalEzT1RZeE1qYzRMQ0owYjJ0bGJsOTBlWEJsSWpvaVltVmhjbVZ5SWl3aWMyTnZjR1VpT2lKbGJXRnBiQ0J2Y0dWdWFXUWdjSEp2Wm1sc1pTSjkuVS1XNEZhTERQOXRyMHM3azExNE9JTWZNelB2b05rNV9oQkVfWGloajQ3ekN0QTk1V0pYVjFkdkhnMmtrNjY4bWJOcjJkT0k4cG1pZS02OVdiVm1YOWNlTmRfRjVHNkQ1LU5aMVNicmdTMTdQTGx5NjlsU1lSdnBRb0tWUENqeVU3Rmg2YlZYdlZOSGZtQ3dYajhjeG5wdHZFWldlOUNRMGVKbUh2ajNJX1lhOFczMmRuSUJpWWs4YzFDNWpKUlZmbzhOeDl3eUlwMEo2b1k4LVBCMTJTSWM3RGVxdFI1RFB4aGtuMzZabXg2MDM5alVHU1ZMRTFOMnFvUzdvU014QjdubmJiQXNfT0cwazJMQU5mUjA4eW8xXzJIam5FVDVlclZDd3I2SDV2LUptaFl5WXdZeVRUcWplZURMdXZaM0lZVDROR3ZlWE44RmthQXBoZG12S0FBIiwiZXhwaXJlc19pbiI6MzYwMCwidG9rZW5fdHlwZSI6ImJlYXJlciIsInNjb3BlIjoiZW1haWwgb3BlbmlkIHByb2ZpbGUiLCJpZF90b2tlbiI6ImV5SjBlWEFpT2lKS1YxUWlMQ0poYkdjaU9pSlNVekkxTmlKOS5leUpwYzNNaU9pSm9kSFJ3Y3pwY0wxd3ZaR1YyTG1GMWRHZ3VZV2hqYjI1MUxtOXlaMXd2SWl3aWMzVmlJam9pTXlJc0ltRjFaQ0k2SW1OaFpHUjVJaXdpYVdGMElqb3hOalEzT1RZeE1qYzNMQ0psZUhBaU9qRTJORGM1TmpRNE56Y3NJbUYxZEdoZmRHbHRaU0k2TVRZME56azJNVEkzTnl3aWJtOXVZMlVpT2lKVE5XSlRORWd4WVZOWk0yWmpTa1o0Ums5dVJGbE9aRVZvZFc5cU16bHFTQ0o5LkQ1Q3lrdFBGeEp2SWFkX0thOTFvTzA0cjFkWDZiWVZrSUtjbXB6TGF3VTQtWjdIX2hGUEZJZHFQTjJQalFLcTVBUHZ3anNUTlI4cktqSVZCUE53cXBlcElERzRMUFozNGI3U1pIeHJUQXRLNktBdHJleHRIenppeXgtU0ZwRGtnS2l0M29mOWJLMnJ5MEJfU0NLS1V4Y3ROcFhlUFNUOUVXNjBtMXRidEI2WDhKWDR4bVNoNm9wMHBBdjNMLWsyeXZMUXlSTG5QMkw1RHVuMEN1dGRUbnFpV3dYNGE2VW52UnkwOE5uLUlsQmNzbGVNTFA0MUtjNENpeXZuVkFOTnMtUVV1WThaM1FOZW9MNVdXNlNObDd3TWIwNDQtSTUtcFZPU1FJWXJ4MEExd0tFcERpRVZ1dmkweGVkVmtMWGZCUkhqYXYwVGRGNWh6aEVkUmxHVmhvdyJ9","redirect_uri":"https://auth.example.com/oauth2/generic/authorization-code-callback"}
```

**Comment by greenpau** [comment]
@teodorescuserban , perfect! 👍 Will work on it.

**Comment by greenpau** [comment]
Note to self ... if there are no key id, then we need to add logic for the handling "default" key ID (aka implicit kid 0) 

https://github.com/greenpau/go-authcrunch/blob/8ef3221a880870a24415ca7c35445610d5c29b95/pkg/authn/backends/oauth2/configure.go#L501-L506

**Comment by teodorescuserban** [comment]
```
"jwks_keys":{"imdJ68aHmcw4JrQjfhSca3mJNWBi6xXZIiF1TyeRtzM":{"alg":"RS256","e":"AQAB","kid":"imdJ68aHmcw4JrQjfhSca3mJNWBi6xXZIiF1TyeRtzM","kty":"RSA","n":"qHDS6x7E9QUalXYC7Ah8bO3B9v0LyEPKllqUH9v0mN7tRHVeKeq7KsDf8UB1FgR0mub9VIAcGB1sKg6Ba2e8VSmlO73qUuLdAeR6OjZExEtErg06cPJOp0PD1ljvL+m1QTvAkavGYYquRsWtopiX5Wgx78kK6Am+dNjMIpLBdb5Pt69OowoHyygij14kbsA+8irXjuvo4uzsWxMhKjDDjqdr9dTNmaFCJAsFCI6PWDNHrFBxqkeX41TmLEPOOHAZN9QQlxn6Ct1YDvdKfkOjCdXXBKBm0jK0UTN0c0W98tzPSaR7cl+2s+xYYzrZfu/Tn+5GmyU2ZZbuIEcGVWnrIw==","use":"sig"}}
```

the url is [this](https://dev.auth.ahconu.org/oauth2/jwk)

**Comment by greenpau** [comment]
>the url is [this](https://dev.auth.ahconu.org/oauth2/jwk)

@teodorescuserban , great! If you don't hear from me by April 10th, please ping me here to remind.

**Comment by greenpau** [comment]
@teodorescuserban , the solution: If key id is not found in the header, then try the first available key.

**Comment by greenpau** [comment]
@teodorescuserban , you should be good to go with `v1.0.19`. See https://github.com/greenpau/caddy-security/issues/83#issue-1186529107 for configuration changes.

**Comment by teodorescuserban** [comment]
@greenpau, I had some time to test it out (I built with version 1.1.1)
After amending the config with the new format I am still unable to login, getting once again the caddy-security "Unauthorized" window and in logs ```"error":"failed validating OAuth 2.0 access token: OAuth 2.0 id_token email claim not found"```

Any idea? :(

The full config below (tried without success to comment out or remove `email` from the `scopes`).

```
{
        debug
        order authenticate before respond
        order authorize before basicauth

        security {
                oauth identity provider generic {
                        realm generic
                        driver generic
                        client_id {env.GENERIC_CLIENT_ID}
                        client_secret {env.GENERIC_CLIENT_SECRET}
                        scopes openid email profile
                        base_auth_url https://dev.auth.*****.org/oauth2/authorize
                        metadata_url https://dev.auth.*****.org/.well-known/openid-configuration
                }
                authentication portal myportal {
                        enable identity provider generic
                        crypto default token lifetime 3600
                        crypto key sign-verify {env.JWT_SHARED_KEY}
                        cookie domain *****.org
                        transform user {
                                match realm generic
                                action add role authp/user
                        }
                }
                authorization policy mypolicy {
                        set auth url https://auth.t.*****.org/oauth2/generic
                        crypto key verify {env.JWT_SHARED_KEY}
                        allow roles authp/admin authp/user
                        validate bearer header
                        inject headers with claims
                }
        }
}

auth.t.*****.org {
        authenticate with myportal
}
so.t.*****.org {
        reverse_proxy siteoauth_so_1 80
        authorize with mypolicy
}
```

**Comment by greenpau** [comment]
@teodorescuserban , the token you are getting from oauth provider, actually contains one or more other tokens: id_ token and access_token. The error you are getting is from that nested access_token. 

Will check how to address this today.

**Comment by greenpau** [comment]
@teodorescuserban , I will add a configuration parameter to disable the email check shortly. 

https://github.com/greenpau/go-authcrunch/blob/706707308213fddfe4884454e38247217d493d3e/pkg/idp/oauth/validator.go#L93-L95

**Comment by greenpau** [comment]
@teodorescuserban , please use https://github.com/greenpau/caddy-security/releases/tag/v1.1.2 and add `disable email claim check`

```
                oauth identity provider generic {
                        realm generic
                        driver generic
                        client_id {env.GENERIC_CLIENT_ID}
                        client_secret {env.GENERIC_CLIENT_SECRET}
                        scopes openid email profile
                        base_auth_url https://dev.auth.*****.org/oauth2/authorize
                        metadata_url https://dev.auth.*****.org/.well-known/openid-configuration
                        disable email claim check
                }
```

Please test and report back.

**Comment by teodorescuserban** [comment]
Nope, getting this error: 

```
"logs":"[ERROR]  Removing invalid block: parsing caddy file tokens for 'security': invalid identity provider config: found unsupported \"email_claim_check_disabled\" field
```

I looked [here](https://github.com/greenpau/caddy-security/compare/v1.1.1...v1.1.2#diff-e191c87a3ffc310ddb1545ab6798b0b8c82668880948167cb7997368bd4292a6R136) and tried `disable key verification` to see if I get errors. I do not. Probably something else missing to deal with the `email_claim_check_disabled` case?

**Comment by greenpau** [comment]
@teodorescuserban, please verify you are using the latest release of caddy security.

https://github.com/greenpau/go-authcrunch/blob/68b0339e49c65753d54cb144222becd6807e52aa/pkg/idp/oauth/config.go#L89

**Comment by greenpau** [comment]
@teodorescuserban , looking into it.

**Comment by greenpau** [comment]
@teodorescuserban , side note. reverse the order.

```
so.t.*****.org {
        authorize with mypolicy
        reverse_proxy siteoauth_so_1 80
}
```

**Comment by greenpau** [comment]
@teodorescuserban , found the error! Will patch and release shortly.

**Comment by greenpau** [comment]
> It still matters if I also have in global order authenticate before respond ?

@teodorescuserban , it does not. Nevertheless, it shows the intent.

**Comment by greenpau** [comment]
> It still matters if I also have in global order authenticate before respond ?

Just to be clear. The `order authenticate before respond` has nothing to do with `authorize`. The `order authorize before basicauth` is what prioritized the `authorize`.

**Comment by teodorescuserban** [comment]
ping @greenpau for Monday 😄

**Comment by greenpau** [comment]
> ping @greenpau for Monday 😄

@teodorescuserban , you should be good to go now! I work on this stuff only on weekends or after work. This week was busy and did not get a chance to finish the work. 

If this does not work, please re-open 🤣

**Comment by teodorescuserban** [comment]
Awesome, @greenpau it is indeed working with the latest tag.

If I may, there is one issue piece of the puzzle that is left for me and that is how do I inject custom headers to downstream from the userinfo.

And of course, I would really like to be able to use those details in the caddy auth policies.

Should I open a new issue or just reopen this one to keep the whole history?

Thank you so much for your help and awesome work you're doing!

Below is an example of userInfo:

```
{
    "sub": "37",
    "email": "john.doe.developer@gmail.com",
    "email_verified": true,
    "name": "john.doe.developer",
    "preferred_username": "john.doe.developer",
    "zoneinfo": "Europe\\/Berlin",
    "profile": {},
    "display_name": "John Doe",
    "groups": [
        "PROJ1",
        "PROJ2",
        "PROJ3",
        "mailhog",
        "snapshots",
        "developer:dev-004",
        "developer:mailhog",
        "developer:snapshots",
        "developer:PROJ1",
        "developer:PROJ2",
        "developer:PROJ3"
    ],
    "departments": [
        "DEPT1"
    ],
    "projects": [
        "PROJ1",
        "PROJ2",
        "PROJ3",
    ],
    "services": [
        "dev-004",
        "mailhog",
        "snapshots"
    ],
    "roles": [
        "authenticated",
        "nomfa"
    ]
}
```

**Comment by greenpau** [comment]
@teodorescuserban , please open separate issues for the above.
