### ISSUE TITLE
question: Migrating from caddy-auth-portal, and functionality.

### ISSUE THREAD

**Issue by tetricky** [greenpau/caddy-security#8]
It seems there's been a refactor to bring portal and authorize into this project. Your readme says "Please open an issue if you need help migrating configurations from caddy-auth-portal and caddy-authorize (aka caddy-auth-jwt)."

That sounds like exactly what I want to do! I am assuming that I need to use this repository (to build into my container), rather than the old auth-portal, and authorize? Do I need to add anything else (aaasf)?

Is this currently the same syntax and functionality, but a building block towards expanded functionality...or is there something in here that expands on the previous functionality?

**Comment by greenpau** [comment]
@tetricky , the syntax is the same. Please see https://github.com/greenpau/caddy-security/blob/main/assets/config/Caddyfile

to get an idea of what needs to change. I think it is intuitive (my wishful thinking? 😃 ). Anyways, please let me know if you “get it”. Meanwhile, I am working on Youtube video ;-)

**Comment by tetricky** [comment]
If I am creating a container, to utilise this refactored code, what do I need to install. previously this was caddy-auth-portal and authorize. Is it now caddy-security and aaasf?

Is there any added functionality in this current release, or is it a refactoring to allow for future expanded functionality?

**Comment by greenpau** [comment]
@tetricky , @MVethana . I will answer shortly. Will be creating a docker image.

**Comment by greenpau** [comment]
> Specifically what I noticed starting to move some stuff from caddy-authorize over, authorize has changed to utilize policies now

@MVethana , yes! 👍 I went away from having `primary`/`secondary` context and synchronization related to it (was fun to write, but the config was not expressive enough)

**Comment by greenpau** [comment]
> If I am creating a container, to utilise this refactored code, what do I need to install. previously this was caddy-auth-portal and authorize. Is it now caddy-security and aaasf?

@tetricky , no you need to forget that `caddy-auth-portal` and `caddy-authorize` existed 😄  Just `caddy-security`.

> Is there any added functionality in this current release, or is it a refactoring to allow for future expanded functionality?

It is the latter. Refactoring to allow future expansion, e.g. registration email with OTP (not easily possible right now).

> I will also want to mount persistent volumes to be able to manipulate any configuration files, and persist the users database. Is there documentation available (or will there be) for the locations of this sort of thing?

Will add/explain.

**Comment by greenpau** [comment]
The docker image is here: https://github.com/greenpau/caddy-security/pkgs/container/authp

**Comment by tetricky** [comment]
Will you open source the Dockerfile, to allow for a self-build of the container (excuse me if this is here somewhere, but I can't find it). This will allow for the potential of further customisation, and audit, which is important to me when concerned with operation of a security level. One of my reasons for using this project, rather than something more comprehensive...it's easier to read and understand.

**Comment by greenpau** [comment]
> Will you open source the Dockerfile, to allow for a self-build of the container 

That's done! The [authp](https://github.com/greenpau/caddy-security/pkgs/container/authp) package.

```
docker pull ghcr.io/greenpau/authp:latest
```

> Apologies, found it in assets/docker/authp/Dockerfile . Is there any functional impact on taking out cloudfare and caddy-trace?

@tetricky , no there is none.

**Comment by greenpau** [comment]
Opened https://github.com/greenpau/caddy-security/issues/15 to track the development of the new auth portal image.
