### ISSUE TITLE
question: mfa to selfhosted services

### ISSUE THREAD

**Issue by ippocratis** [greenpau/caddy-security#82]
> A clear and concise description of what you want to accomplish.

maybe i missunderstud the purpose of the plug in .
and most likely i missconfigured the Caddyfile
i'm not verry familiar with caddy 
i love it coz it addds ssl's to my selfhosted services
i already reverse proxy them with it
so
what i want is to add mfa to them
as far as i can understand i access and secure myportal  with mfa 
then i can add various links whick will lead to my varius sevices e.g. nextcloud,radicale,photoprism,whatever etc and those will be authorised with mypolicy

did i get it completely wrong?
how can i acomplish that?

thanks

**Comment by greenpau** [comment]
@ippocratis , did you get chance to watch this video? https://youtu.be/poOkq_jb1B0

**Comment by ippocratis** [comment]
@greenpau yes i can use aegis authenticactor to log in to myportal
what i dont understand is how to set up links so i can "launch" my "apps/services" from within the porttal
is that even posible?

**Comment by greenpau** [comment]
Here is about creating links https://authp.github.io/docs/authenticate/ui-features#portal-links

you could also create “conditional” links based on user transforms https://authp.github.io/docs/authenticate/user-transforms#add-ui-links

is that what you need?

**Comment by ippocratis** [comment]
@greenpau 
This issue #10 , the users convoys and your suggestions there helped me really helped  me out
Thanks
