### ISSUE TITLE
need help to getting started

### ISSUE THREAD

**Issue by mariomare22** [greenpau/caddy-security#84]
Hello!
I am trying to go through your video and using Caddy-security with local auth using the caddyfile you provided
https://gist.github.com/greenpau/dbfadd3c9fee21dbb0a0d3902a8d0ec0#file-localauth_caddyfile

I am currently running a fresh raspiOS with installed Caddy + caddy-security module.
I am having an error when starting Caddy using the sample.

is it possible to do a test using just the IP of the raspberry? I am not able to use my domain and ports 443/80 since they are in use by a different proxy on a different device.

```
➜  bin sudo systemctl status caddy
● caddy.service - Caddy
     Loaded: loaded (/lib/systemd/system/caddy.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2022-03-30 18:17:47 CEST; 12min ago
       Docs: https://caddyserver.com/docs/
    Process: 7744 ExecStart=/usr/bin/caddy run --environ --config /etc/caddy/Caddyfile (code=exited, status=1/FAILURE)
   Main PID: 7744 (code=exited, status=1/FAILURE)
        CPU: 292ms

Mar 30 18:17:47 sandbox caddy[7744]: JOURNAL_STREAM=8:29751
Mar 30 18:17:47 sandbox caddy[7744]: {"level":"info","ts":1648657067.0205774,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapt>
Mar 30 18:17:47 sandbox caddy[7744]: {"level":"warn","ts":1648657067.0281086,"msg":"input is not formatted with 'caddy fmt'","adapter":"caddyfile","file":"/etc/cadd>
Mar 30 18:17:47 sandbox caddy[7744]: {"level":"info","ts":1648657067.032992,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_>
Mar 30 18:17:47 sandbox caddy[7744]: {"level":"info","ts":1648657067.0334222,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","ca>
Mar 30 18:17:47 sandbox caddy[7744]: {"level":"info","ts":1648657067.0334737,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","ca>
Mar 30 18:17:47 sandbox caddy[7744]: run: loading initial config: loading new config: loading tls app module: provision tls: loading certificates: open /var/lib/cad>
Mar 30 18:17:47 sandbox systemd[1]: Started Caddy.
Mar 30 18:17:47 sandbox systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
Mar 30 18:17:47 sandbox systemd[1]: caddy.service: Failed with result 'exit-code'.
lines 1-18/18 (END)
```

**Comment by greenpau** [comment]
@mariomare22 , thank you for the issue! 

Could you please provide full log?

```
Mar 30 18:17:47 sandbox caddy[7744]: run: loading initial config: loading new config: loading tls app module: provision tls: loading certificates: open /var/lib/cad>
```

Based on the partial error, you are having issue with Caddy itself (tls plugin), not caddy security.

Additionally, I need to know versions:

```
caddy list-modules -versions | grep auth
```

**Comment by mariomare22** [comment]
WOW! thank you for your lightning fast answer
```
➜  bin caddy list-modules -versions | grep auth
http.authentication.hashes.bcrypt v2.4.6
http.authentication.hashes.scrypt v2.4.6
http.authentication.providers.http_basic v2.4.6
http.handlers.authentication v2.4.6
http.authentication.providers.authorizer v1.0.18
http.handlers.authenticator v1.0.18
➜  bin
```
when entering the following I can access sandbox.local on https (with certificate warning) and the proxy redirects me correctly.
```
sandbox.local {
        root * /usr/share/caddy
        reverse_proxy 192.168.1.2:3000
}
```

**Comment by greenpau** [comment]
> when entering the following I can access sandbox.local on https (with certificate warning) and the proxy redirects me correctly. and http gets redirected to https

@mariomare22 , what is not working then?

**Comment by mariomare22** [comment]
The Caddyfile in the gist with localauth
https://gist.github.com/greenpau/dbfadd3c9fee21dbb0a0d3902a8d0ec0#file-localauth_caddyfile

**Comment by greenpau** [comment]
@mariomare22 , if you took that file, how do you deal with `tls {env.HOME}/.local/caddy/server.crt {env.HOME}/.local/caddy/server.key`?

What is the error besides `Mar 30 18:17:47 sandbox caddy[7744]: run: loading initial config: loading new config: loading tls app module: provision tls: loading certificates: open /var/lib/cad>`?

**Comment by mariomare22** [comment]
I have no clue! this is exactly why I came here in the first place

**Comment by greenpau** [comment]
@mariomare22 , I would recommend first getting things works without any security. 

See here: https://caddyserver.com/docs/quick-starts/static-files

After you get it running, then add security aspects to it.

**Comment by greenpau** [comment]
> is it possible to do a test using just the IP of the raspberry? 

Yes. Just be conscious about the ports. In my config sample I  use 8443 and 8080.

**Comment by mariomare22** [comment]
```
sandbox.local:8443 192.168.1.18:8443 {
        reverse_proxy 192.168.1.2:3000
}
```
With this configuration I can reach the reversed proxy with the hostname and with the IPs using https://
and the certificate (I guess) is self signed by caddy
