### ISSUE TITLE
🔥 announcement 🔥: introducing user registration section

### ISSUE THREAD

**Issue by greenpau** [greenpau/caddy-security#85]
Will be abandoning the `registration` inside `portal` section. Instead the registration will have its own configuration section.

This change will be released in: `v1.1.2`

***Note*** if you are not using user registration, then this is not a "breaking" change.

Previously, your  `registration` config was a part of `authentication portal`.

```
{
  security {
    authentication portal myportal {
      registration {
        dropbox {env.HOME}/.local/caddy/registrations.json
        title "User Registration"
        code "NY2020"
        require accept terms
        require domain mx
        admin email barbaz@bar.baz foobar@foo.bar
      }
    }
  }
}
```

Now, it has its own section. Here, the user registration is tied to an email messaging provider, `localhost-smtp-server`.

```
{
        security {
                user registration localdbRegistry {
                        dropbox {$HOME}/.local/caddy/registrations.json
                        title "User Registration"
                        code "NY2020"
                        require accept terms
                        require domain mx
                        admin email barbaz@bar.baz foobar@foo.bar
                        email provider localhost-smtp-server
                        identity store localdb
                }

                local identity store localdb {
                        realm local
                        path {$HOME}/.local/caddy/localdb/users.json
                }

                authentication portal myportal {
                        identity store localdb
                }

                credentials root@localhost {
                        username root
                        password foobar
                }

                messaging email provider localhost-smtp-server {
                        address 127.0.0.1:1025
                        protocol smtp
                        passwordless
                        sender root@localhost "My Auth Portal"
                        credentials root@localhost
                        bcc greenpau@localhost
                }
        }
}
```

**Comment by tpansino** [comment]
@greenpau - is this a breaking change? Will my Caddy instance break if I download this plugin without updating my config file first?

SemVer isn't about versioning your API endpoints (I don't, but I do follow SemVer). It's about communicating to users when you're breaking a previously-establish contract they depend on. That includes changing a config file parser. 

Without that, you're expecting users like me to check your GitHub Issue board for an Announcement post with every single release. I don't have time to do that for the 30+ Docker services I run, not to mention all of the other software I use daily. I don't have time to post a support ticket either and deal with the back-and-forth. Clear communication and documentation is critical.

Instead of releasing these breaking changes one-off like this, why not get them all working on a `v2` branch, get your docs updated as well, and merge and release all of that change as a major release? Make a big announcement of it, celebrate the progress. That flow makes the change a lot easier for a user like me to process, and let's me celebrate along with you. 🤷

**Comment by greenpau** [comment]
> @greenpau - is this a breaking change? Will my Caddy instance break if I download this plugin without updating my config file first?

@tpansino , if you are not using user registration, then it is non-breaking.

> Instead of releasing these breaking changes one-off like this, why not get them all working on a v2 branch, get your docs updated as well, and merge and release all of that change as a major release? 

When you build caddy, you can lock a specific version of a specific plugin. This way, your will be locked to whichever version you choose.

https://github.com/greenpau/caddy-security/blob/059a464f90b0de31d352dfa6bbfb3eee2daa2908/Makefile#L17-L19

It works the same when you use Caddy download page.

![image](https://user-images.githubusercontent.com/3826416/161442653-01f5593a-a3e3-4178-b3ee-41d139a2626c.png)

You can lock your builds to a specific version.

> Without that, you're expecting users like me to check your GitHub Issue board for an Announcement post with every single release. 

Yes, I do expect people to skim through the announcements. If a person is running an authentication server, the person needs to keep it up-to-date and understand recent changes. 

Side note: You did mention another authentication project in another issue. I don't appreciate the mentions like that. That's why I deleted your comment. Also, I will delete these comments too because they are not useful.

**Comment by helmut72** [comment]
The examples should be also updated:
https://raw.githubusercontent.com/greenpau/caddy-security/main/assets/config/Caddyfile

Of course configurations changes from time to time. But it looks like it's a bigger refactoring. I think it's my 3rd reconfiguration in just some weeks. ;) Do you have a road map when it's finished?

**Comment by greenpau** [comment]
> Of course configurations changes from time to time. But it looks like it's a bigger refactoring. I think it's my 3rd reconfiguration in just some weeks. ;) Do you have a road map when it's finished?

@helmut72 , this would be the last one big refactoring for some time! 😃 Hopefully, I will finish it this weekend. It is just super tedious work converting stuff to be interface-driven.

Next, I will be working on redesigning UI. There will be no configuration changes there.

**Comment by helmut72** [comment]
Thanks for info 😀

**Comment by bdr99** [comment]
I think the documentation here needs to be updated: https://authp.github.io/docs/authenticate/local/user-registration

With the new registration section, is it required to use an email provider? The old example didn't use an email provider, but it seems it is required now. When I try to set it up without an email provider, I get this error:
`reload: adapting config using caddyfile: parsing caddyfile tokens for 'security': user registration configuration for "localfileregistry" instance failed: email provider is not set`

**Comment by greenpau** [comment]
@bdr99 , thank you for pointing it out. Please create an issue in https://github.com/authp/authp.github.io/issues/new for tracking

> Also, with the new registration section, is it required to use an email provider? 

Yes, please see complete example:

https://github.com/authp/authp.github.io/blob/main/assets/conf/local/registration/Caddyfile#L38

**Comment by bdr99** [comment]
> @bdr99 , thank you for pointing it out. Please create an issue in https://github.com/authp/authp.github.io/issues/new for tracking

Thanks! Will open an issue in the website repo.

> > Also, with the new registration section, is it required to use an email provider?
> 
> Yes, please see complete example:
> 
> https://github.com/authp/authp.github.io/blob/main/assets/conf/local/registration/Caddyfile#L38

Is there a reason why it was changed to be tied to an email provider? This seems like a bit of a step backward, since it was possible before to configure registration without an email provider. It's not a big deal to me, but I'm just curious of the reasoning that went into this change.
