### ISSUE TITLE
breakfix: Trouble with Token Verification through Organizr tokens: "reason: no token found"

### ISSUE THREAD

**Issue by rubinghv** [greenpau/caddy-security#86]
**Describe the issue**

I want to use Caddy to use a logged in [Organizr](https://docs.organizr.app) user to validate access to various subdomains. I'm using [Token Verification](https://authp.github.io/docs/authorize/token-verification) for this.

Caddy has [some documentation](https://docs.organizr.app/features/server-authentication) on how to get the Name/UUID of the token and the secret/hash (this documentation is out of date, as new location is: `/config/www/organizr/data/config/config.php`)

However, I get the values (they are stable), enter them in the config below, but end up with some errors in my logs:
```
{"level":"error","ts":1649326672.7983973,"logger":"http.handlers.authentication","msg":"auth provider returned error","provider":"authorizer","error":"user authorization failed: src_ip=62.14.197.61, src_conn_ip=162.158.23.19, reason: no token found"
```

I've tried playing around with various combinations. Looking at my [cookie jar in the browser](https://snipboard.io/FBkpP3.jpg) the values don't match, but then again these seem to be newly generated every time so that checks out?
 
I think I'm probably messing up slightly in the syntax, or the naming/values, but I'm having a hard time out finding where exactly. Any pointers would be appreciated

Note: I also have Cloudflare setup, but I don't think this should affect this (let me know if it might)

**Configuration**

Paste full `Caddyfile` below:

```
{
    order authenticate before respond
    order authorize before basicauth

    security {
        authorization policy organizrpolicy {
            crypto key verify <REDACTED_ORGANIZR_HASH> 
            crypto key token name <REDACTED_ORGANIZR_UUID>
            allow roles User Admin
        }
    }


*.myserver.com {
    tls {
        dns cloudflare <redacted_secret>
    }


    @server host server.myserver.com 
	handle @server {
            reverse_proxy organizr:80
	}

    @tv host tv.myserver.com 
	handle @tv {
            authorize with organizrpolicy
            reverse_proxy sonarr:8989
	}
```

**Version Information**

Provide output of `caddy list-modules -versions | grep git` below:

```
v2.4.6
(command doesn't work in docker container, nothing mentioning git)
```

**Expected behavior**

Caddy detects the cookie that's present from Organizr, and uses this to authenticate on the specific subdomain.

**Additional context**

**Comment by greenpau** [comment]
@rubinghv , thank you for the issue! 👍 

Did you have a chance to go over https://github.com/greenpau/caddy-security/issues/9 ? If not, please do and let me know what is the difference between it and yours.

**Comment by rubinghv** [comment]
Ah cool, didn't notice that issue before (Google doesn't seem to index GitHub issues well, or at all)

Looks like it worked first time after doing changes you suggested! Let me know if below Caddyfile makes sense and if there's anything I'm overlooking. I'll try to make sure Organizr documentation gets updated :)

My updated Caddyfile:

```
{
    order authenticate before respond
    order authorize before basicauth

    security {
        authorization policy organizrpolicy {
            set auth url "https://server.mydomain.com"
            crypto key verify <ORGANIZR_HASH_TOKEN>
            crypto key token name organizr_token_<ORGANIZR_UUID>
            set token sources cookie header query
            validate bearer header

             acl rule {
                 comment allow admins only
                  match iss Organizr
                  match role Admin
                  allow stop log info
            }
             acl rule {
                  comment default deny
                  match iss any
                  deny log warn
            }
        }
    }
}


*.mydomain.com {
    tls {
        dns cloudflare <CLOUDFLARE_KEY>
    }

    @server host server.mydomain.com
	handle @server {
        reverse_proxy organizr:80
    }

    @tv host tv.mydomain.com
	handle @tv {
        authorize with organizrpolicy
        reverse_proxy sonarr:8989
    }

    # other subdomains redacted

```

Thanks a lot!

**Comment by rubinghv** [comment]
Yeah it's working as intended! Just wanted to post the Caddyfile for posterity and to check if there's anything that doesn't make sense

**Comment by greenpau** [comment]
>  Yeah it's working as intended! Just wanted to post the Caddyfile for posterity and to check if there's anything that doesn't make sense

@rubinghv , awesome! 👍  Here are some insight about your config.

```
            set token sources cookie header query
            validate bearer header
```


The `cookie header query` instructs the plugin to search for the token in these places and in the order they are listed.

If you are using only Authorization header, then consider trying:

```
            set token sources header
            validate bearer header
```

**Note**: Please consider contributing https://github.com/greenpau/caddy-security/issues/14
