### ISSUE TITLE
question: inject headers from userinfo object

### ISSUE THREAD

**Issue by teodorescuserban** [greenpau/caddy-security#87]
@greenpau, thank you for your awesome work!

Everything seems to be working correctly talking to a quaint oauth2 server.

To have a complete and useful setup, there is one piece of the puzzle that is left for me and that is how do I inject custom headers to downstream from the userinfo object.

And of course, I would really like to be able to use those details in the caddy auth policies.

In my setup I currently use vouch to get additional information from the userinfo object.

I have attempted `inject header "X-Custom-Projects" from projects` with no success (I get no error either, but I don't seem to get the new header).

I do see two additional headers when I add `inject headers with claims` to the config, unfortunately that is not quite enough for my setup.

Also `inject header "X-Custom-Roles" from roles` works (although I get the caddy-secutiry roles, not the ones in the userInfo object).

Below is an example of userInfo:

```
{
    "sub": "37",
    "email": "john.doe.developer@gmail.com",
    "email_verified": true,
    "name": "john.doe.developer",
    "preferred_username": "john.doe.developer",
    "zoneinfo": "Europe\\/Berlin",
    "profile": {},
    "display_name": "John Doe",
    "groups": [
        "PROJ1",
        "PROJ2",
        "PROJ3",
        "mailhog",
        "snapshots",
        "developer:dev-004",
        "developer:mailhog",
        "developer:snapshots",
        "developer:PROJ1",
        "developer:PROJ2",
        "developer:PROJ3"
    ],
    "departments": [
        "DEPT1"
    ],
    "projects": [
        "PROJ1",
        "PROJ2",
        "PROJ3",
    ],
    "services": [
        "dev-004",
        "mailhog",
        "snapshots"
    ],
    "roles": [
        "authenticated",
        "nomfa"
    ]
}
```

**Comment by greenpau** [comment]
@teodorescuserban , please browse to `/whoami` endpoint in auth portal and paste what you see there. It is the parts that you see  there that could be injected in.

**Comment by teodorescuserban** [comment]
@greenpau, ok, the info I am looking for is not in there and after sweeping though caddy-security and go-authcrunch, I think this ticket should be moved to a feature request rather than a question... because I suppose there is no easy way to grab those details from userInfo and pass them downstream...

**Comment by greenpau** [comment]
>  ok, the info I am looking for is not in there

@teodorescuserban , that I understand 😃 Nevertheless, I need to see it. What we would need to do is bring some fields from OAuth token into auth portal token. That would require some work.

**Comment by greenpau** [comment]
@teodorescuserban , I also need to see all the tokens passed in OAuth session. Please email me at `greenpau<>outlook.com`.

**Comment by teodorescuserban** [comment]
@greenpau, thank you, I just sent the info requested.

**Comment by greenpau** [comment]
@teodorescuserban , got it 👍

**Comment by teodorescuserban** [comment]
@greenpau, as an additional info, I am curently using [vouch](https://github.com/vouch/vouch-proxy) to talk to the oauth server and the key to get those groups is the `VOUCH_HEADERS_CLAIMS: email,name,groups` env var injected in vouch container. Hopefully this helps.

**Comment by greenpau** [comment]
> I am curently using [vouch](https://github.com/vouch/vouch-proxy) to talk to the oauth server and the key to get those groups is the VOUCH_HEADERS_CLAIMS: email,name,groups env var injected in vouch container. Hopefully this helps.

@teodorescuserban , yes, it is along the lines of my throughts.

I would need to create a new directive:

```
oauth identity store myoautherver {
  # extract <field1> <fieldN> from userinfo
  extract email name groups from userinfo
}
```

Hopefully I will find some time to do it this weekend.

**Comment by teodorescuserban** [comment]
> oauth identity store myoautherver {
>   # extract <field1> <fieldN> from userinfo
>   extract email name groups from userinfo
> }
This is so assertive and cool.
Hopefully nobody needs to extract the field `from` 😄 
Looking forward to it.
Thank you!

**Comment by greenpau** [comment]
@teodorescuserban , I will be injecting OAuth userinfo to `userinfo` field in the token:

![image](https://user-images.githubusercontent.com/3826416/163736991-5d18bfe9-2d9e-46d6-9f9a-885addfe146e.png)

I here is my current config:

```
        oauth identity provider generic {
            driver generic
            realm generic
            client_id {env.CLIENT_ID}
            client_secret {env.CLIENT_SECRET}
            scopes openid email profile groups
            metadata_url https://foo.bar.com/.well-known/openid-configuration
            extract all from userinfo
        }
```

**Comment by greenpau** [comment]
Here is how it looks like with partial fields from `userinfo`:

```
        oauth identity provider generic {
            extract custom_groups name zoneinfo from userinfo
        }
```

![image](https://user-images.githubusercontent.com/3826416/163739033-8b3bc6da-b20e-4f0a-b971-ed1d9efeebc6.png)

**Comment by greenpau** [comment]
Next, I want to inject `userinfo.custom_groups` to HTTP headers.

Starting point: https://authp.github.io/docs/authorize/headers#custom-headers

Currently, with the following injection

```
authorization policy mypolicy {
  inject header "X-User-Info" from userinfo
  inject header "X-User-Sub" from sub
}
```

I get 

![image](https://user-images.githubusercontent.com/3826416/163741203-f42d38cb-af0a-4a8d-9803-e9da4f1a896a.png)

Next, let's try traversing the map.

The desired state is being able to inject nested data, where `|` (pipe) signals the traversal path:

```
authorization policy mypolicy {
  inject header "X-User-Custom-Groups" from "userinfo|custom_groups"
  inject header "X-User-Timezone" from "userinfo|timezone"
  inject header "X-User-Name" from "userinfo|name"
}
```

**Comment by greenpau** [comment]
@teodorescuserban , please test with [v1.1.4](https://github.com/greenpau/caddy-security/releases/tag/v1.1.4). If it does not work, please email logs to me.

**Comment by teodorescuserban** [comment]
@greenpau, this looks amazing! I was able to configure everything successfully! Thank you!

**Comment by teodorescuserban** [comment]
Post thoughts: 

My previous solution used vouch and nginx auth-request.

The authorization worked by having nginx do an internal auth request to `/validate` which would proxy the request to vouch.
This way, there were no sensitive headers passed back and for the the client and the upstream, therefore the headers could not be forged. I am wondering if there is any way to have the nginx auth request go to a specific caddy endpoint that will provide the above headers.

My whole reason is to be able to delegate some of the authorization part to the upstream, especially in cases that would be too long and cumbersome to configure and maintain (e.g. multiple folders, each folder having a specific set of users and groups allowed).

I was on the fence wether to open yet another ticket, I guess I'll ate limit myself for a while 😸

**Comment by greenpau** [comment]
@teodorescuserban , 😄 new issue 

Also, please add a diagram to your explanation.

**Comment by teodorescuserban** [comment]
@greenpau, sorry for delay, got tangled in other things. I tried to forge the custom headers from the client and it looks like they are not making it to the backend server, so I think all is good! I really liked the last change with automatically adding the roles fields from userinfo into the roles, awesome!
