### ISSUE TITLE
Check organisation membership in github oauth

### ISSUE THREAD

**Issue by sakisv** [greenpau/caddy-security#91]
Hi 👋 

I have github org and I've created a Github App to use with caddy-security. Right now I'm using the approach described in the examples[^1] and it works fine 👍 

However, instead of having to maintain a list of approved users, I would like to check they are member of my organisation and allow them if they are.

Github seems to have a way of doing this[^2] but I don't know if it's relevant and if I could use it. Other projects allow providing a list of "allowed orgs"[^3] which seems more approriate, but this doesn't seem to be supported here, so I am a bit at a loss here.

Any help or pointers would be greatly appreciated :) 

[^1]: https://github.com/authp/authp.github.io/blob/main/assets/conf/oauth/github/Caddyfile#L29-L33
[^2]: https://docs.github.com/en/rest/orgs/orgs#list-organizations-for-the-authenticated-user
[^3]: https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#github-auth-provider

**Comment by greenpau** [comment]
@sakisv, i don’t use github organizations. If you an organization with multiple users, please email me your setup privately (you would need to create a new app for testing and provide me with client id/secret, etc.) and I will try figuring out how to make it happen.

**Comment by greenpau** [comment]
@sakisv , I do similar thing with Gitlab. https://authp.github.io/docs/authenticate/oauth/backend-oauth2-0009-gitlab

I also think that what you are asking already exists, but undocumented. It is somewhere here: https://github.com/greenpau/go-authcrunch/blob/63fee4d8534d935a06882539d35c2148b3bb7dbe/pkg/idp/oauth/user.go#L266

**Comment by rubydotexe** [comment]
I don't know if this is helpful, but I created an organization and made a GitHub app under the organization. I then added my members. Upon testing, the GitHub portal automatically only allowed organization members, I didn't need to do any additional configuration. Or at least, when I tested it with a dummy github account that wasn't in my org, they weren't able to log in.

**Comment by greenpau** [comment]
Stale.
