### ISSUE TITLE
using custom claims

### ISSUE THREAD

**Issue by wnke** [greenpau/caddy-security#93]
Some oauth providers allow adding custom claims such as [auth0](https://auth0.com/blog/adding-custom-claims-to-id-token-with-auth0-actions/)

Is it possible to use this claims in match directives and also to inject them as http headers?

example
```
  transform user {
    exact match  "https://dogfy.com/random_dog" "puppy"
    action add role puppy
  }

```
```
{
  security {
    authorization policy mypolicy {
      inject headers with claims
      inject header "X-Picture" from picture
      inject header "X-Dog" from "https://dogfy.com/random_dog"
    }
  }
}

```

**Comment by greenpau** [comment]
@wnke , please add “extract all from userinfo” and see whether oauth provider data propagates to the token displayed in “/whoami”.

also, please see  https://github.com/greenpau/caddy-security/issues/87#issuecomment-1101015496  , it looks like this is what your are looking for.

**Comment by wnke** [comment]
Hey @greenpau !

thank for the hint! the `extract all from userinfo` really helped out!

with that directive enabled this now works
```
{
  security {
    authorization policy mypolicy {
      inject headers with claims
      inject header "X-Picture" from picture
      inject header "X-Dog" from "userinfo|https://dogfy.com/random_dog"
    }
  }
}
```

But this still will not:
```
  transform user {
    exact match "userinfo|https://dogfy.com/random_dog" "puppy"
    action add role puppy
  }
```
Failing with the error:
```
caddy_1  | run: loading initial config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'authentication': provision http.handlers.authentication: loading authentication providers: module name 'authorizer': provision http.authentication.providers.authorizer: loading security app module: provision security: invalid rule syntax: invalid condition syntax, failed creating rule condition: exact match userinfo|https://dogfy.com/random_dog puppy
```

Is the userinfo no available for matches?

**Comment by greenpau** [comment]
> But this still will not:
> exact match "userinfo|https://dogfy.com/random_dog" "puppy"

@wnke , the "nested" field match is not supported yet. This would be a feature request.

**Comment by greenpau** [comment]
@wnke , btw, the `match` is based on the same subsystem as authorization ACLs: https://authp.github.io/docs/authorize/acl-rbac#conditions

**Comment by greenpau** [comment]
@wnke , generally speaking, the reason there is no nested matches is ... Your OAuth provider can have any of these four fields: `roles`, `groups`, `group`, `roles` at the top level of the token it issues. If found, the values from the fields will be added to `roles`. So ... configure your OAuth provider to send `groups` or `roles` field.

**Comment by wnke** [comment]
Hey @greenpau !

Thank you very much for the tips and the interest in this ticket, it is very appreciated!

Unfortunately, at least for auth0, only namepaced custom claims are allowed making it impossible to add `roles`. I can only add something like `https://dogfy.com/roles`, to follow from example above.

From the [auth0 docs](https://auth0.com/docs/secure/tokens/json-web-tokens/create-namespaced-custom-claims):

By default, Auth0 always enforces namespacing; any custom claims with non-namespaced identifiers will be silently excluded from tokens and silently ignored in Actions and Rules.

We do allow non-OIDC claims without a namespace for legacy tenants using a non-OIDC-conformant pipeline with the Legacy User Profile enabled; however, we strongly recommend that legacy tenants migrate to an OIDC-conformant flow.

**Comment by greenpau** [comment]
> We do allow non-OIDC claims without a namespace for legacy tenants using a non-OIDC-conformant pipeline with the Legacy User Profile enabled; however, we strongly recommend that legacy tenants migrate to an OIDC-conformant flow.

@wnke , I will think how to best resolve it. Perhaps, I would add the following:

```
extract https://dogfy.com/roles from userinfo as roles
```

Please paste the token with `userinfo` field issued by auth portal.

**Comment by greenpau** [comment]
@wnke , the image similar to this one: ![](https://user-images.githubusercontent.com/3826416/163739033-8b3bc6da-b20e-4f0a-b971-ed1d9efeebc6.png)

**Comment by wnke** [comment]
That would be great!

Using the `extract all from userinfo` I got:

```json
{
  "authenticated": true,
  "email": "email@gmail.com",
  "exp": 1651526561,
  "expires_at_utc": "Mon May  2 21:22:41 UTC 2022",
  "iat": 1651522961,
  "iss": "https://example.com/oauth2/generic/",
  "issued_at_utc": "Mon May  2 20:22:41 UTC 2022",
  "jti": "zoGlTMMp83Vc3v41gUj2zhaTWInT4Zby42lNVgy",
  "name": "",
  "nbf": 1651522901,
  "not_before_utc": "Mon May  2 20:21:41 UTC 2022",
  "origin": "generic",
  "picture": "https://s.gravatar.com/avatar/34b96091d8d838817e08eb08d26e5?s=480\u0026r=pg\u0026d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fsi.png",
  "roles": [
    "authp/guest"
  ],
  "sub": "auth0|626eab8f7170b37661",
  "userinfo": {
    "email": "email@gmail.com",
    "email_verified": true,
    "https://example.com/roles": [
      "top",
      "best"
    ],
    "name": "email@gmail.com",
    "nickname": "email",
    "picture": "https://s.gravatar.com/avatar/34b96091d8d8381d408eb08d26e5?s=480\u0026r=pg\u0026d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fsi.png",
    "sub": "auth0|626eab8f7170b37661",
    "updated_at": "2022-05-02T18:52:22.658Z"
  }
}
```

In this case I got the roles as a list as one user can have several.

**Comment by greenpau** [comment]
> That would be great!

@wnke , I will go with `extract https://example.com/roles from userinfo as roles list`

```
extract <userInfoFieldName> from userinfo as <topLevelFieldName> [list]
```

**Comment by wnke** [comment]
This is fantastic! Thank you so much!

**Comment by greenpau** [comment]
@wnke , I tried many different things and none of them fit nicely into an existing design ... so ... If `userinfo` map has a key that ends with `roles` (`https://example.com/roles`) or `groups`, I am going to automatically take entries from there and place them into top level `roles`.

**Comment by greenpau** [comment]
Documentation task: https://github.com/authp/authp.github.io/issues/19
