### ISSUE TITLE
How can I capture the access token and send request with authorization bearer?

### ISSUE THREAD

**Issue by alirf81** [greenpau/caddy-security#96]
Hi!
Thank you for your contribution.

I am trying to use caddy-security with Keycloak as IDP and it seems like work well for browser login.
But I have some API clients and want to get access token and send request with authorization bearer set in header.

Can you kindly guide me how I can make this?

**Comment by greenpau** [comment]
@alirf81 , here is info on bearer token https://authp.github.io/docs/authorize/token-discovery

and API auth https://authp.github.io/docs/authenticate/misc#authenticate

Is this what you are looking for?

**Comment by alirf81** [comment]
yes, looks great. thank you!
Btw, I have one more issue, it uses the JWT token and it seems a bit long.
Can we use any other token which is shorter?

**Comment by greenpau** [comment]
> Can we use any other token which is shorter?

@alirf81 , in settings, create API key for a user. Then enable API key usage on your authorization policy. https://authp.github.io/docs/authorize/basic_api_key_auth

After that, you can pass API key via X-API-Token header in a request.

**Comment by alirf81** [comment]
1. Does JSON Authenticate API works when I use Keycloak IDP? https://authp.github.io/docs/authenticate/misc#authenticate
2. I cannot access setting page, I can see portal page in /auth/portals but cannot see setting page under /auth/settings
3. Are there JSON API for setting API token programmatically?
Kindly give me your comment pls.

**Comment by greenpau** [comment]
@alirf81 , FYI, Keycloak docs are here: https://authp.github.io/docs/authenticate/oauth/backend-oauth2-0011-keycloak#realm-roles

> Does JSON Authenticate API works when I use Keycloak IDP? https://authp.github.io/docs/authenticate/misc#authenticate

No.

> I cannot access setting page, I can see portal page in /auth/portals but cannot see setting page under /auth/settings

That page only works with "local" identity store. I have https://github.com/greenpau/caddy-security/issues/23 issue in my backlog. The gist is connecting OAuth-authenticated users to "local" identity store.

> Are there JSON API for setting API token programmatically?

Not at the moment.

**Comment by greenpau** [comment]
@alirf81, I am looking to add testimonial sections to https://authcrunch.com. Could you please write one and send it to me at greenpau@outlook.com?
