### ISSUE TITLE
question: OAuth with Keycloak

### ISSUE THREAD

**Issue by alirf81** [greenpau/caddy-security#98]
I am using Keycloak as IDP.

https://github.com/authp/authp.github.io/blob/main/assets/conf/oauth/keycloak/Caddyfile
This configuration works well but I have a question here,

Can I use Keycloak's JWT after authentication?
As I understood, after authentication, caddy-security issues its own JWT which would be used in authorization.
Can I configure it to use Keycloak's JWT in authentication and decrypt it with Keycloak's pub key in authorization?

Kindly give me your comments.
Thanks

**Comment by greenpau** [comment]
> Can I use Keycloak's JWT after authentication?

@alirf81 , no.
